import { IconArrowLeft,IconBolt,IconChevronRight,IconCrosshair,IconHeartRateMonitor,IconRefresh,IconShield,IconTargetArrow,IconTool } from "@tabler/icons-react";
import { Button } from "@lucky-arcade/ui";
import { useEffect,useMemo,useRef,useState } from "react";
import { createGflRun,RECOMMENDED_FORMATIONS,reduceGflRun } from "../core.ts";
import type { GflAction,GflContentPack,GflRunState,Intervention,RouteNode,Tactic } from "../contracts.ts";
import { LittleJsBattleAdapter } from "./runtime/littlejs-adapter.ts";

export interface GflEmberScreenProps{pack:GflContentPack;initialState:GflRunState|null;onPersist(previous:GflRunState,next:GflRunState,action:GflAction):Promise<void>;onExit():void;}

export function GflEmberScreen({pack,initialState,onPersist,onExit}:GflEmberScreenProps){
  const [runNonce,setRunNonce]=useState(0),[state,setState]=useState(()=>initialState??createGflRun(pack,`${new Date().toISOString().slice(0,10)}:0`));
  const dispatch=(action:GflAction)=>{try{const next=reduceGflRun(pack,state,action);if(next===state)return;setState(next);void onPersist(state,next,action);}catch(error){console.warn(error);}};
  const newRun=()=>{const next=createGflRun(pack,`${new Date().toISOString().slice(0,10)}:${runNonce+1}`);setRunNonce((value)=>value+1);setState(next);};
  return <main className="gfl-shell"><header className="gfl-topbar"><button className="icon-button" onClick={onExit} aria-label="오락실로 돌아가기"><IconArrowLeft/></button><div><span>BUILT-IN CABINET · NO LLM</span><h1>소녀전선: 잔불 작전</h1></div><div className="gfl-run-status"><span>구간 <b>{Math.min(state.depth+1,7)}/7</b></span><span>보급 <b>{state.supplies}</b></span></div></header>
    {state.phase==="formation"&&<Formation pack={pack} onConfirm={(ids)=>dispatch({type:"set_formation",dollIds:ids})}/>}
    {state.phase==="route"&&<Route state={state} onChoose={(nodeId)=>dispatch({type:"choose_node",nodeId})} onRetreat={()=>dispatch({type:"retreat"})}/>}
    {state.phase==="battle-ready"&&<BattleReady state={state} pack={pack} onTactic={(tactic)=>dispatch({type:"choose_tactic",tactic})} onIntervention={(intervention,round)=>dispatch({type:"schedule_intervention",intervention,round})} onStart={()=>dispatch({type:"resolve_battle"})}/>}
    {state.phase==="battle-report"&&state.transcript&&<BattlePlayback state={state} pack={pack} onContinue={()=>dispatch({type:"acknowledge_battle"})}/>}
    {state.phase==="reward"&&<Rewards state={state} onChoose={(rewardId)=>dispatch({type:"choose_reward",rewardId})}/>}
    {state.phase==="finished"&&<Ending state={state} onRetry={newRun} onExit={onExit}/>}
  </main>;
}

function Formation({pack,onConfirm}:{pack:GflContentPack;onConfirm(ids:string[]):void}){const [selected,setSelected]=useState<string[]>([...RECOMMENDED_FORMATIONS.balanced]);const toggle=(id:string)=>setSelected((current)=>current.includes(id)?current.filter((value)=>value!==id):current.length<6?[...current,id]:current);return <section className="gfl-panel formation-panel"><div className="gfl-section-title"><span>STEP 01</span><h2>첫 제대를 편성하세요</h2><p>전열은 공격을 받아내고, 후열은 화력을 집중합니다.</p></div><div className="preset-row"><button onClick={()=>setSelected([...RECOMMENDED_FORMATIONS.balanced])}>균형 제대</button><button onClick={()=>setSelected([...RECOMMENDED_FORMATIONS.firepower])}>화력 제대</button><button onClick={()=>setSelected([...RECOMMENDED_FORMATIONS.defense])}>방어 제대</button></div><div className="doll-grid">{pack.dolls.map((doll)=><button key={doll.id} className={selected.includes(doll.id)?"selected":""} onClick={()=>toggle(doll.id)}><Portrait pack={pack} id={doll.id}/><span>{doll.class} · ★{doll.grade}</span><strong>{doll.name}</strong><small>전투력 {doll.power}</small></button>)}</div><div className="gfl-sticky-action"><span><b>{selected.length}</b>/6명 선택</span><Button disabled={selected.length!==6} onClick={()=>onConfirm(selected)}>작전 지도 진입 <IconChevronRight size={18}/></Button></div></section>}

function Route({state,onChoose,onRetreat}:{state:GflRunState;onChoose(id:string):void;onRetreat():void}){return <section className="gfl-panel route-panel"><div className="gfl-section-title"><span>ROUTE {state.depth+1}/7</span><h2>다음 작전 경로를 선택하세요</h2><p>위험한 길은 더 강한 적과 보상을 품고 있습니다.</p></div><div className="route-history">{state.route.map((column,index)=><div key={index} className={index<state.depth?"done":index===state.depth?"current":"locked"}><b>{index+1}</b>{index===state.depth&&column.map((node)=><NodeButton key={node.id} node={node} onChoose={onChoose}/>)}</div>)}</div><button className="text-button" onClick={onRetreat}>현재 전리품을 보존하고 철수</button></section>}
function NodeButton({node,onChoose}:{node:RouteNode;onChoose(id:string):void}){const icon=node.type==="repair"?<IconTool/>:node.type==="supply"?<IconHeartRateMonitor/>:node.type==="scout"?<IconTargetArrow/>:node.type==="boss"?<IconCrosshair/>:<IconBolt/>;return <button className={`route-node ${node.type}`} onClick={()=>onChoose(node.id)}>{icon}<strong>{node.label}</strong><small>위험도 {"◆".repeat(node.danger)}</small></button>}

function BattleReady({state,pack,onTactic,onIntervention,onStart}:{state:GflRunState;pack:GflContentPack;onTactic(t:Tactic):void;onIntervention(i:Intervention,r:number):void;onStart():void}){const node=state.route[state.depth]?.find((item)=>item.id===state.currentNodeId);return <section className="gfl-panel battle-ready"><div className="gfl-section-title"><span>TACTICAL BRIEFING</span><h2>{node?.label} 준비</h2><p>전술과 한 번뿐인 지휘 개입을 예약하면 판정 코어가 전투 전체를 계산합니다.</p></div><div className="tactic-grid">{([['focus','집중','화력↑ 피격↑'],['balanced','균형','안정적인 교전'],['cover','엄폐','피격↓ 명중↓']] as const).map(([id,label,detail])=><button key={id} className={state.tactic===id?"selected":""} onClick={()=>onTactic(id)}><strong>{label}</strong><small>{detail}</small></button>)}</div><div className="intervention-row"><label>지휘 개입<select value={state.intervention?.type??"brace"} onChange={(event)=>onIntervention(event.target.value as Intervention,state.intervention?.round??3)}><option value="focus">집중 사격</option><option value="brace">긴급 엄폐</option><option value="barrage">제압 사격</option></select></label><label>발동 라운드<input type="number" min="1" max="8" value={state.intervention?.round??3} onChange={(event)=>onIntervention(state.intervention?.type??"brace",Number(event.target.value))}/></label></div><div className="formation-strip">{state.formation.map((id)=><div key={id}><Portrait pack={pack} id={id}/><span>{pack.dolls.find((d)=>d.id===id)?.name}</span></div>)}</div><Button className="gfl-launch" onClick={onStart}><IconCrosshair/> 전투 영수증 확정</Button></section>}

function BattlePlayback({state,pack,onContinue}:{state:GflRunState;pack:GflContentPack;onContinue():void}){const host=useRef<HTMLDivElement>(null),[done,setDone]=useState(false),[speed,setSpeed]=useState<1|2|4>(2);useEffect(()=>{if(!host.current||!state.transcript)return;let alive=true;const adapter=new LittleJsBattleAdapter(pack.assets);void adapter.mount(host.current).then(async()=>{await adapter.preload(state.formation.flatMap((id)=>[`portrait:${id}:natural`,`portrait:${id}:angry`,`portrait:${id}:default`]));if(alive){await adapter.play(state.transcript!,{speed});if(alive)setDone(true);}});const visibility=()=>document.hidden?adapter.pause():adapter.resume();document.addEventListener("visibilitychange",visibility);return()=>{alive=false;document.removeEventListener("visibilitychange",visibility);adapter.destroy();}},[state.transcript,state.formation,pack.assets,speed]);const transcript=state.transcript!;return <section className="gfl-battle-stage"><div ref={host}/><div className="battle-controls"><div><button onClick={()=>{setDone(false);setSpeed(1)}} className={speed===1?"active":""}>1×</button><button onClick={()=>{setDone(false);setSpeed(2)}} className={speed===2?"active":""}>2×</button><button onClick={()=>{setDone(false);setSpeed(4)}} className={speed===4?"active":""}>4×</button></div><span>{transcript.outcome==="victory"?"전투 승리":"제대 전멸"} · {transcript.rounds.length}라운드</span><Button disabled={!done} onClick={onContinue}>{done?"전투 보고 확인":"재생 중…"}</Button></div></section>}

function Rewards({state,onChoose}:{state:GflRunState;onChoose(id:string):void}){return <section className="gfl-panel reward-panel"><div className="gfl-section-title"><span>SALVAGE</span><h2>하나를 회수하세요</h2><p>제대 상태와 남은 경로를 보고 다음 선택을 준비하세요.</p></div><div className="reward-grid">{state.rewards.map((reward)=><button key={reward.id} onClick={()=>onChoose(reward.id)}><IconShield/><strong>{reward.label}</strong><small>{reward.detail}</small></button>)}</div></section>}
function Ending({state,onRetry,onExit}:{state:GflRunState;onRetry():void;onExit():void}){const won=state.outcome==="victory";return <section className={`gfl-panel ending ${won?"won":""}`}><span className="eyebrow">OPERATION COMPLETE</span><h2>{won?"잔불 작전 완수":state.outcome==="retreated"?"안전 철수":"작전 실패"}</h2><p>{state.visited.length}개 구간 돌파 · 장비 {state.inventory.length}개 회수</p><div><Button onClick={onRetry}><IconRefresh size={18}/> 새 작전</Button><Button onClick={onExit}>오락실로 돌아가기</Button></div></section>}

function Portrait({pack,id}:{pack:GflContentPack;id:string}){const definition=pack.dolls.find((doll)=>doll.id===id)??(pack.boss.id===id?pack.boss:null),src=pack.assets[`portrait:${id}:natural`]??pack.assets[`portrait:${id}:default`];return <div className="gfl-portrait">{src?<img src={src} alt={definition?.name??id} loading="lazy" decoding="async"/>:<span>{definition?.name??id}</span>}</div>}
