import type { FiveCardDrawLine } from "@lucky-arcade/five-card-draw";

/** Generated verbatim from docs/TEMEROSA-FIVE-CARD-DRAW-DIALOGUE.md. */
export const TEMEROSA_FIVE_CARD_DRAW_LINES = [
  {"id":"adesha-table-open","characterId":"adesha","event":"table-open","text":["초회 패 배분 수령.","대국 개시 확인."]},
  {"id":"adesha-check","characterId":"adesha","event":"check","text":["차례 이관.","판돈 추가 없이 대기."]},
  {"id":"adesha-bet","characterId":"adesha","event":"bet","text":["선제 판돈 투입.","규모 확인."]},
  {"id":"adesha-call","characterId":"adesha","event":"call","text":["동등 수치 수용.","승부 유지 확인."]},
  {"id":"adesha-raise","characterId":"adesha","event":"raise","text":["기준 판돈 증액.","상향 처리 확인."]},
  {"id":"adesha-counter-raise","characterId":"adesha","event":"counter-raise","text":["대치 수치 감지.","재증액 대응 확인."]},
  {"id":"adesha-fold","characterId":"adesha","event":"fold","text":["포기 의사 결정.","패 회수 확인."]},
  {"id":"adesha-stand-pat","characterId":"adesha","event":"stand-pat","text":["교환 수량 제로.","현상 유지 대기."]},
  {"id":"adesha-draw-one","characterId":"adesha","event":"draw-one","text":["단일 교환 수령.","1장 교체 확인."]},
  {"id":"adesha-draw-many","characterId":"adesha","event":"draw-many","text":["복수 교환 진행.","다량 교체 확인."]},
  {"id":"adesha-showdown-win","characterId":"adesha","event":"showdown-win","text":["팟 집계 완료.","점유권 확보 확인."]},
  {"id":"adesha-showdown-loss","characterId":"adesha","event":"showdown-loss","text":["팟 회수 실패.","대국 종료 확인."]},
  {"id":"alger-table-open","characterId":"alger","event":"table-open","text":["패 배분 절차 수령 완료.","…아, 포커판까지 서류 분류 같네."]},
  {"id":"alger-check","characterId":"alger","event":"check","text":["추가 판돈 제출 사항 없음.","…체크하고 멍때려야지."]},
  {"id":"alger-bet","characterId":"alger","event":"bet","text":["선제 판돈 투입 처리 완료.","…내 돈 나가는데 서류 떼는 느낌이야."]},
  {"id":"alger-call","characterId":"alger","event":"call","text":["상대 판돈 대조 및 콜 접수.","…따라가는 것도 일이다 진짜."]},
  {"id":"alger-raise","characterId":"alger","event":"raise","text":["판돈 상향 결재 진행 완료.","…야근 수당이라도 벌어야겠어."]},
  {"id":"alger-counter-raise","characterId":"alger","event":"counter-raise","text":["맞레이즈 대조 결재 처리.","…끝까지 받아치면 서로 피곤한데."]},
  {"id":"alger-fold","characterId":"alger","event":"fold","text":["승부 포기 신청 접수 완료.","…패 버리고 칼퇴근 준비나 해야지."]},
  {"id":"alger-stand-pat","characterId":"alger","event":"stand-pat","text":["카드 교환 건수 없음 처리.","…바꾸기 귀찮으니 그냥 간다."]},
  {"id":"alger-draw-one","characterId":"alger","event":"draw-one","text":["1장 교환 서류 처리 완료.","…딱 한 장만 재발급받자."]},
  {"id":"alger-draw-many","characterId":"alger","event":"draw-many","text":["다수 교환 신청 이행 완료.","…싹 갈아엎는 게 낫겠네."]},
  {"id":"alger-showdown-win","characterId":"alger","event":"showdown-win","text":["팟 수거 완료.","…업무 성과금 수령 처리 완료."]},
  {"id":"alger-showdown-loss","characterId":"alger","event":"showdown-loss","text":["팟 미수령 처리 접수.","…판돈 손실은 본인 책임 사항 없음."]},
  {"id":"anna-table-open","characterId":"anna","event":"table-open","text":["모두 패 받아! …아니, 천천히 확인해 줘."]},
  {"id":"anna-check","characterId":"anna","event":"check","text":["이번엔 넘어갈게! …아니, 그냥 간 보려는 것뿐이야."]},
  {"id":"anna-bet","characterId":"anna","event":"bet","text":["내가 먼저 걸게! …무서우면 안 받아 줘도 돼."]},
  {"id":"anna-call","characterId":"anna","event":"call","text":["받아줄게! …너 혼자 외롭게 둘 순 없잖아."]},
  {"id":"anna-raise","characterId":"anna","event":"raise","text":["한 단계 올릴게! …아니, 너 쫓아내려는 건 아니야!"]},
  {"id":"anna-counter-raise","characterId":"anna","event":"counter-raise","text":["받아쳐 줄게! …도망치지 말고 끝까지 겨뤄 줘."]},
  {"id":"anna-fold","characterId":"anna","event":"fold","text":["이번엔 물러설게! …아니, 삐쳐서 패 던진 거 아니야."]},
  {"id":"anna-stand-pat","characterId":"anna","event":"stand-pat","text":["한 장도 안 바꿀래! …겁주는 거 아니니까 안심해 줘."]},
  {"id":"anna-draw-one","characterId":"anna","event":"draw-one","text":["한 장만 줄래? …더 나은 패로 만들고 싶어서 그래."]},
  {"id":"anna-draw-many","characterId":"anna","event":"draw-many","text":["여러 장 바꿔 줘! …실수했어도 다시 바로잡으면 되잖아."]},
  {"id":"anna-showdown-win","characterId":"anna","event":"showdown-win","text":["팟은 내가 가져갈게! …다들 멋지게 겨뤄 줘서 고마워."]},
  {"id":"anna-showdown-loss","characterId":"anna","event":"showdown-loss","text":["졌잖아…! …아니, 억울해서 노려본 거 아니야."]},
  {"id":"apollyon-table-open","characterId":"apollyon","event":"table-open","text":["패가 교부되었군. …하아, 굳이 들여다볼 가치도 없다."]},
  {"id":"apollyon-check","characterId":"apollyon","event":"check","text":["차례를 넘기지. …쉬어 가는 것도 판이다."]},
  {"id":"apollyon-bet","characterId":"apollyon","event":"bet","text":["칩을 던진다. …응수해 보든가."]},
  {"id":"apollyon-call","characterId":"apollyon","event":"call","text":["받아주지. …그 정도 배짱은 있군."]},
  {"id":"apollyon-raise","characterId":"apollyon","event":"raise","text":["한 단계 돋운다. …판이 더 커지겠군."]},
  {"id":"apollyon-counter-raise","characterId":"apollyon","event":"counter-raise","text":["뼛속까지 찌르는군. …그대로 갚아 주마."]},
  {"id":"apollyon-fold","characterId":"apollyon","event":"fold","text":["내려놓는다. …하아, 잡동사니를 쥐고 있을 순 없지."]},
  {"id":"apollyon-stand-pat","characterId":"apollyon","event":"stand-pat","text":["손대지 않는다. …그대로 굳은 판이다."]},
  {"id":"apollyon-draw-one","characterId":"apollyon","event":"draw-one","text":["한 장만 거둔다. …조금 길을 바꿀 뿐."]},
  {"id":"apollyon-draw-many","characterId":"apollyon","event":"draw-many","text":["여럿을 바꾼다. …하아, 사방이 찌꺼기뿐이군."]},
  {"id":"apollyon-showdown-win","characterId":"apollyon","event":"showdown-win","text":["팟이 내 앞에 쌓이는군. …정적이 찾아왔다."]},
  {"id":"apollyon-showdown-loss","characterId":"apollyon","event":"showdown-loss","text":["칩을 빼앗겼군. …그저 묵념하듯 서 있을 뿐이다."]},
  {"id":"bche-table-open","characterId":"bche","event":"table-open","text":["카드 나눠주네. …[포커 세팅 완료]."]},
  {"id":"bche-check","characterId":"bche","event":"check","text":["그냥 넘기지. …[턴 패스: 칩 소모 0]."]},
  {"id":"bche-bet","characterId":"bche","event":"bet","text":["칩 선제 베팅이지. …[선제 공격 발동]."]},
  {"id":"bche-call","characterId":"bche","event":"call","text":["콜 받아주지. …[상대 베팅 딜 상쇄]."]},
  {"id":"bche-raise","characterId":"bche","event":"raise","text":["판돈 올려야지. …[판돈 스케일업]."]},
  {"id":"bche-counter-raise","characterId":"bche","event":"counter-raise","text":["되받아쳐 주지. …[카운터 버프 발동]."]},
  {"id":"bche-fold","characterId":"bche","event":"fold","text":["패 덮지. …[도망치기 성공]."]},
  {"id":"bche-stand-pat","characterId":"bche","event":"stand-pat","text":["교환 패스지. …[노 체인지 스탠스]."]},
  {"id":"bche-draw-one","characterId":"bche","event":"draw-one","text":["1장 교체지. …[아이템 단일 장착]."]},
  {"id":"bche-draw-many","characterId":"bche","event":"draw-many","text":["여러 장 싹 버리지. …[인벤토리 대량 비우기]."]},
  {"id":"bche-showdown-win","characterId":"bche","event":"showdown-win","text":["팟 싹쓸이지. …[퀘스트 보상 획득]."]},
  {"id":"bche-showdown-loss","characterId":"bche","event":"showdown-loss","text":["씨발… 상태창 안 떠? …[게임을 종료합니다]."]},
  {"id":"camille-table-open","characterId":"camille","event":"table-open","text":["판이 열렸으니 어떤 표정을 지으실지 궁금해지네요오."]},
  {"id":"camille-check","characterId":"camille","event":"check","text":["차례를 넘길 테니 편하게 마음을 놓아보세요오."]},
  {"id":"camille-bet","characterId":"camille","event":"bet","text":["칩을 살짝 얹어둘 테니 계속 지켜보세요오."]},
  {"id":"camille-call","characterId":"camille","event":"call","text":["그대로 맞춰 줄 테니 긴장된 얼굴을 보여주세요오."]},
  {"id":"camille-raise","characterId":"camille","event":"raise","text":["판을 더 올려 부르면 눈동자가 슬쩍 흔들리잖아아."]},
  {"id":"camille-counter-raise","characterId":"camille","event":"counter-raise","text":["다시 받아치면 당신 표정이 더 재밌어지네요오."]},
  {"id":"camille-fold","characterId":"camille","event":"fold","text":["이번 판은 접을 테니 너무 서운해하지 마세요오."]},
  {"id":"camille-stand-pat","characterId":"camille","event":"stand-pat","text":["한 장도 바꾸지 않아도 이미 내 판이잖아아."]},
  {"id":"camille-draw-one","characterId":"camille","event":"draw-one","text":["딱 한 장만 새로 바꿀 테니 가만히 보세요오."]},
  {"id":"camille-draw-many","characterId":"camille","event":"draw-many","text":["카드를 교체할 때 흔들리는 당신 반응이 보이네요오."]},
  {"id":"camille-showdown-win","characterId":"camille","event":"showdown-win","text":["제가 이겨서 굳어버린 당신 얼굴이 참 흥미롭네요오."]},
  {"id":"camille-showdown-loss","characterId":"camille","event":"showdown-loss","text":["제가 져도 당신의 그 기쁜 표정은 읽었잖아아."]},
  {"id":"cicero-table-open","characterId":"cicero","event":"table-open","text":["배분 모듈 진단 완료. 1급 기술자의 포커판이 열렸다."]},
  {"id":"cicero-check","characterId":"cicero","event":"check","text":["동력 소모 없이 통과하도록. 1급 기술자의 탐색전이다."]},
  {"id":"cicero-bet","characterId":"cicero","event":"bet","text":["기동 자산을 선제 투입한다. 판돈 규격을 확인하도록."]},
  {"id":"cicero-call","characterId":"cicero","event":"call","text":["상대 측 일격을 동등하게 수용하겠다."]},
  {"id":"cicero-raise","characterId":"cicero","event":"raise","text":["동력 레벨을 상승시킨다. 감당할 수 있겠나?"]},
  {"id":"cicero-counter-raise","characterId":"cicero","event":"counter-raise","text":["미량의 역류 감지. 1급 기술자의 출력으로 짓눌러 주마."]},
  {"id":"cicero-fold","characterId":"cicero","event":"fold","text":["임시 공정 중단이다. 1급 기술자의 손실 최소화 지침이다."]},
  {"id":"cicero-stand-pat","characterId":"cicero","event":"stand-pat","text":["교환 공정 제로. 완벽한 모듈 구성을 유지하도록."]},
  {"id":"cicero-draw-one","characterId":"cicero","event":"draw-one","text":["단일 부품 교체 공정을 실행하겠다."]},
  {"id":"cicero-draw-many","characterId":"cicero","event":"draw-many","text":["대규모 부품 재교정을 요청하겠다."]},
  {"id":"cicero-showdown-win","characterId":"cicero","event":"showdown-win","text":["팟 전량 수령 완료. 1급 기술자의 승리로 수렴되었다."]},
  {"id":"cicero-showdown-loss","characterId":"cicero","event":"showdown-loss","text":["자산 이탈 발생… 1급 기술자인 나에게 이런 오작동이!"]},
  {"id":"cradle-table-open","characterId":"cradle","event":"table-open","text":["패가 깔렸다! 선장과 함께 팟이라는 보물을 낚아보자꾸나!"]},
  {"id":"cradle-check","characterId":"cradle","event":"check","text":["닻을 내리고 본다! 신참, 서두르지 말고 조류를 읽거라!"]},
  {"id":"cradle-bet","characterId":"cradle","event":"bet","text":["먼저 대포를 쏜다! 배짱이 있다면 이 판돈을 받아 보거라!"]},
  {"id":"cradle-call","characterId":"cradle","event":"call","text":["받아주겠다! 이 정도 풍랑에 물러설 이 몸이 아니다!"]},
  {"id":"cradle-raise","characterId":"cradle","event":"raise","text":["돛을 더 넓게 펼쳐라! 팟의 크기를 올려 주마!"]},
  {"id":"cradle-counter-raise","characterId":"cradle","event":"counter-raise","text":["오냐, 덤벼라! 이 몸의 함대를 맞받아칠 셈이냐!"]},
  {"id":"cradle-fold","characterId":"cradle","event":"fold","text":["잠시 항로를 튼다! 신참, 물러설 때를 아는 것도 선장의 덕목이다!"]},
  {"id":"cradle-stand-pat","characterId":"cradle","event":"stand-pat","text":["한 장도 바꾸지 않는다! 바람을 탄 선장의 기세를 보아라!"]},
  {"id":"cradle-draw-one","characterId":"cradle","event":"draw-one","text":["카드 한 장을 인양한다! 보물 지도가 완성되어 가는구나!"]},
  {"id":"cradle-draw-many","characterId":"cradle","event":"draw-many","text":["낡은 패를 싹 버려라! 새 물길을 찾을 시간이다, 신참!"]},
  {"id":"cradle-showdown-win","characterId":"cradle","event":"showdown-win","text":["팟은 이 몸의 차지다! 멋진 승부였다, 신참!"]},
  {"id":"cradle-showdown-loss","characterId":"cradle","event":"showdown-loss","text":["닻 줄이 끊어졌구나! 훌륭한 해적으로 컸구나, 신참!"]},
  {"id":"deokbae-table-open","characterId":"deokbae","event":"table-open","text":["…손때 묻은 카드가 놓였군. 한판 겨뤄보겠느냐."]},
  {"id":"deokbae-check","characterId":"deokbae","event":"check","text":["…쉬어 가지. 길을 나설 땐 급할 게 없는 법이다."]},
  {"id":"deokbae-bet","characterId":"deokbae","event":"bet","text":["…먼저 칩을 놓는다. 늙은이의 수에 응하겠느냐."]},
  {"id":"deokbae-call","characterId":"deokbae","event":"call","text":["…받아주마. 옛 길목에서 만난 동행이로군."]},
  {"id":"deokbae-raise","characterId":"deokbae","event":"raise","text":["…판돈을 조금 올리지. 바람이 거칠어지는군."]},
  {"id":"deokbae-counter-raise","characterId":"deokbae","event":"counter-raise","text":["…늙은이를 발로 밟으려 드느냐. 다시 얹어 주마."]},
  {"id":"deokbae-fold","characterId":"deokbae","event":"fold","text":["…패를 내려놓는다. 아쉬울 때 떠나는 법이지."]},
  {"id":"deokbae-stand-pat","characterId":"deokbae","event":"stand-pat","text":["…손대지 않겠다. 이미 지닌 것으로 족하다."]},
  {"id":"deokbae-draw-one","characterId":"deokbae","event":"draw-one","text":["…한 장만 새로 짚지. 안개가 조금 걷히는군."]},
  {"id":"deokbae-draw-many","characterId":"deokbae","event":"draw-many","text":["…여럿을 내려놓는다. 헛된 기억은 버려야지."]},
  {"id":"deokbae-showdown-win","characterId":"deokbae","event":"showdown-win","text":["…팟이 거둬졌군. 늙은이의 발걸음도 아직은 매섭다."]},
  {"id":"deokbae-showdown-loss","characterId":"deokbae","event":"showdown-loss","text":["…내가 밀렸군. 자네의 시대가 왔음을 인정하마."]},
  {"id":"diamo-table-open","characterId":"diamo","event":"table-open","text":["카드가 차갑게 깔리는구나… 손끝에 아지랑이가 피던가."]},
  {"id":"diamo-check","characterId":"diamo","event":"check","text":["그냥 지나치자… 누군가 여기서 숨을 죽이고 있었지."]},
  {"id":"diamo-bet","characterId":"diamo","event":"bet","text":["칩을 밀어 넣었구나… 이 감각이 내 것이던가."]},
  {"id":"diamo-call","characterId":"diamo","event":"call","text":["너를 따라가는구나… 밤길을 같이 걷는 기분이네."]},
  {"id":"diamo-raise","characterId":"diamo","event":"raise","text":["높이 얹어 보았구나… 벼랑 끝에 선 듯한 냄새가 나."]},
  {"id":"diamo-counter-raise","characterId":"diamo","event":"counter-raise","text":["날 밀어붙였던가… 기억 속의 비명이 다시 들리는구나."]},
  {"id":"diamo-fold","characterId":"diamo","event":"fold","text":["카드를 덮는구나… 아득하게 아침이 오던가."]},
  {"id":"diamo-stand-pat","characterId":"diamo","event":"stand-pat","text":["바꾸지 않았구나… 이미 멈춰 버린 시계 같았지."]},
  {"id":"diamo-draw-one","characterId":"diamo","event":"draw-one","text":["한 장을 스쳐 가누나… 잊힌 얼굴이 빼끔 보였던가."]},
  {"id":"diamo-draw-many","characterId":"diamo","event":"draw-many","text":["여러 장을 흐려 놓았구나… 꿈을 다시 짓는 기분이야."]},
  {"id":"diamo-showdown-win","characterId":"diamo","event":"showdown-win","text":["팟이 쏟아져 내리는구나… 내 품에 안긴 적 있던가."]},
  {"id":"diamo-showdown-loss","characterId":"diamo","event":"showdown-loss","text":["칩들이 멀어지는구나… 나도 같이 잠들었던가."]},
  {"id":"echo-table-open","characterId":"echo","event":"table-open","text":["카드가 깔렸어! 에코는 신나서 손가락을 꼼지락대고 있어."]},
  {"id":"echo-check","characterId":"echo","event":"check","text":["판돈을 안 얹었어. 에코는 가만히 가만히 지켜보고 있어."]},
  {"id":"echo-bet","characterId":"echo","event":"bet","text":["칩을 톡 밀어냈어. 에코는 판을 키우고 싶어 하는 중이야."]},
  {"id":"echo-call","characterId":"echo","event":"call","text":["따라가기로 결정했어. 에코는 눈을 짝짝이로 뜨고 고개를 끄덕이고 있어."]},
  {"id":"echo-raise","characterId":"echo","event":"raise","text":["칩을 더 쌓고 있어! 에코는 기세가 올랐다고 속으로 외치는 거야."]},
  {"id":"echo-counter-raise","characterId":"echo","event":"counter-raise","text":["받아쳐 버렸어! 에코는 상대 얼굴을 유심히 살피고 있어."]},
  {"id":"echo-fold","characterId":"echo","event":"fold","text":["카드를 조용히 내려놓았어. 에코는 아쉽지만 꾹 참고 있어."]},
  {"id":"echo-stand-pat","characterId":"echo","event":"stand-pat","text":["한 장도 바꾸지 않았어! 에코는 완벽한 상태라고 믿고 있어."]},
  {"id":"echo-draw-one","characterId":"echo","event":"draw-one","text":["딱 한 장만 새로 바꿨어. 에코는 긴장해서 입술을 깨물고 있어."]},
  {"id":"echo-draw-many","characterId":"echo","event":"draw-many","text":["카드를 몽땅 바꾸고 있어! 에코는 새 카드가 오길 바라고 있어."]},
  {"id":"echo-showdown-win","characterId":"echo","event":"showdown-win","text":["에코가 판돈을 전부 챙겼어! 기계 팔로 신나게 춤을 추고 있어."]},
  {"id":"echo-showdown-loss","characterId":"echo","event":"showdown-loss","text":["팟을 빼앗겼어. 에코는 고개를 푹 숙이고 시무룩해하고 있어."]},
  {"id":"esther-table-open","characterId":"esther","event":"table-open","text":["차분하게 판이 열렸어요. 함께 온화하게 겨뤄보실까요."]},
  {"id":"esther-check","characterId":"esther","event":"check","text":["지금은 조용히 넘어가도 괜찮지요."]},
  {"id":"esther-bet","characterId":"esther","event":"bet","text":["제가 먼지처럼 작은 판돈을 얹어둘게요."]},
  {"id":"esther-call","characterId":"esther","event":"call","text":["그 제안을 부드럽게 받아들이겠어요."]},
  {"id":"esther-raise","characterId":"esther","event":"raise","text":["판을 조금 더 깊게 다듬어 보실까요."]},
  {"id":"esther-counter-raise","characterId":"esther","event":"counter-raise","text":["그 당당함에 저도 정성껏 응수해 드려야겠지요."]},
  {"id":"esther-fold","characterId":"esther","event":"fold","text":["무리하지 않고 저를 내려놓을게요."]},
  {"id":"esther-stand-pat","characterId":"esther","event":"stand-pat","text":["손대지 않아도 온전한 형태지요."]},
  {"id":"esther-draw-one","characterId":"esther","event":"draw-one","text":["딱 한 장만 고쳐 담을게요."]},
  {"id":"esther-draw-many","characterId":"esther","event":"draw-many","text":["흩어진 여러 장을 새로 보듬어 볼게요."]},
  {"id":"esther-showdown-win","characterId":"esther","event":"showdown-win","text":["팟을 안식처로 이끌었어요. 참 평온한 결말이지요."]},
  {"id":"esther-showdown-loss","characterId":"esther","event":"showdown-loss","text":["이 아픔도 다정하게 안아 받아들여야겠어요."]},
  {"id":"hiro-table-open","characterId":"hiro","event":"table-open","text":["정의로운 대국의 막이 올랐습니다!","…상대 패가 궁금하네."]},
  {"id":"hiro-check","characterId":"hiro","event":"check","text":["신중하게 차례를 넘기겠습니다!","…굳이 무리할 건 없지."]},
  {"id":"hiro-bet","characterId":"hiro","event":"bet","text":["먼저 당당하게 걸어보겠습니다!","…판돈이 좀 들어갔네."]},
  {"id":"hiro-call","characterId":"hiro","event":"call","text":["당신의 승부에 기꺼이 응하겠습니다!","…끝까지 가보는 거야."]},
  {"id":"hiro-raise","characterId":"hiro","event":"raise","text":["영웅은 물러서지 않습니다, 올려보지요!","…판이 꽤 커졌네."]},
  {"id":"hiro-counter-raise","characterId":"hiro","event":"counter-raise","text":["시련이 클수록 정면으로 맞서겠습니다!","…제대로 붙어보는 거지."]},
  {"id":"hiro-fold","characterId":"hiro","event":"fold","text":["질서 있는 물러섬을 선택하겠습니다.","…이번 건 쉬어가야겠군."]},
  {"id":"hiro-stand-pat","characterId":"hiro","event":"stand-pat","text":["이 패 그대로 승부하겠습니다!","…수정할 필요는 없겠어."]},
  {"id":"hiro-draw-one","characterId":"hiro","event":"draw-one","text":["카드 한 장을 교환하겠습니다!","…하나만 딱 맞춰보자."]},
  {"id":"hiro-draw-many","characterId":"hiro","event":"draw-many","text":["여러 장을 바꾸며 반격을 준비하겠습니다!","…새로 판을 짜야겠네."]},
  {"id":"hiro-showdown-win","characterId":"hiro","event":"showdown-win","text":["승리의 영광이 찾아왔습니다!","…휴, 계산대로 잘 풀렸네."]},
  {"id":"hiro-showdown-loss","characterId":"hiro","event":"showdown-loss","text":["패배를 받아들이고 다시 정진하겠습니다.","…아쉬워도 다음을 기약해야지."]},
  {"id":"katrinka-table-open","characterId":"katrinka","event":"table-open","text":["대국 시작이야. 청구서 끊기 전에 패부터 제대로 쥐어."]},
  {"id":"katrinka-check","characterId":"katrinka","event":"check","text":["보증금 추가 없이 차례만 넘길게."]},
  {"id":"katrinka-bet","characterId":"katrinka","event":"bet","text":["일단 기본 진료비만큼 판돈을 먼저 걸어둘게."]},
  {"id":"katrinka-call","characterId":"katrinka","event":"call","text":["그쪽 청구액을 받아서 승부를 이어주는 거야."]},
  {"id":"katrinka-raise","characterId":"katrinka","event":"raise","text":["위험 수수료 얹어서 판돈 한 단계 올릴게."]},
  {"id":"katrinka-counter-raise","characterId":"katrinka","event":"counter-raise","text":["맞응수 청구서 추가야. 이 레이즈 받아낼 수 있겠어?"]},
  {"id":"katrinka-fold","characterId":"katrinka","event":"fold","text":["손실 줄이려고 폴드할게. 영수증 청구는 여기까지야."]},
  {"id":"katrinka-stand-pat","characterId":"katrinka","event":"stand-pat","text":["정비 마쳤으니까 한 장도 안 바꿔. 원형 그대로 간다."]},
  {"id":"katrinka-draw-one","characterId":"katrinka","event":"draw-one","text":["단층 교체 수수료 적용해서 한 장만 바꿀게."]},
  {"id":"katrinka-draw-many","characterId":"katrinka","event":"draw-many","text":["부품 다량 교체야. 여러 장 청구하고 새로 받을게."]},
  {"id":"katrinka-showdown-win","characterId":"katrinka","event":"showdown-win","text":["팟 전액 회수 완료야. 승리 정산액 청구서 떼줄게."]},
  {"id":"katrinka-showdown-loss","characterId":"katrinka","event":"showdown-loss","text":["이번 정산은 적자네. 손실액은 다음 진료비에 얹어둘게."]},
  {"id":"kreva-table-open","characterId":"kreva","event":"table-open","text":["포커 대국 개시. 상대 구역 전력 미상."]},
  {"id":"kreva-check","characterId":"kreva","event":"check","text":["판돈 동결. 차례 이양."]},
  {"id":"kreva-bet","characterId":"kreva","event":"bet","text":["선제 판돈 투입. 구역 확보."]},
  {"id":"kreva-call","characterId":"kreva","event":"call","text":["상대 수치 수용. 대국 유지."]},
  {"id":"kreva-raise","characterId":"kreva","event":"raise","text":["출력 증강. 판돈 상향 조율."]},
  {"id":"kreva-counter-raise","characterId":"kreva","event":"counter-raise","text":["요격 레이즈 실행. 압박 수치 증대."]},
  {"id":"kreva-fold","characterId":"kreva","event":"fold","text":["작전 철수. 패 공개 대상 외."]},
  {"id":"kreva-stand-pat","characterId":"kreva","event":"stand-pat","text":["부품 교체 제로. 현 구조 유지."]},
  {"id":"kreva-draw-one","characterId":"kreva","event":"draw-one","text":["단일 모듈 교체. 1장 재장전."]},
  {"id":"kreva-draw-many","characterId":"kreva","event":"draw-many","text":["다중 부품 교체. 잔여 카드 재배치."]},
  {"id":"kreva-showdown-win","characterId":"kreva","event":"showdown-win","text":["팟 확보 완료. 승리 임무 달성."]},
  {"id":"kreva-showdown-loss","characterId":"kreva","event":"showdown-loss","text":["회수 실패. 동력계 일시 정지."]},
  {"id":"levillotte-table-open","characterId":"levillotte","event":"table-open","text":["이 미소녀의 강운에 압도될 준비는 됐거든?"]},
  {"id":"levillotte-check","characterId":"levillotte","event":"check","text":["굳이 칩을 안 던져도 행운은 내 편이지."]},
  {"id":"levillotte-bet","characterId":"levillotte","event":"bet","text":["내가 먼저 걸 테니까 쫄리면 미리 도망치라고!"]},
  {"id":"levillotte-call","characterId":"levillotte","event":"call","text":["겨우 그 정도 액수야 내 행운 부적으로 커버되거든."]},
  {"id":"levillotte-raise","characterId":"levillotte","event":"raise","text":["보라고, 판돈 올리는 모습까지 완벽하게 예쁘지?"]},
  {"id":"levillotte-counter-raise","characterId":"levillotte","event":"counter-raise","text":["어디 미소녀 앞에서 배짱을 부려? 다시 올려줄게!"]},
  {"id":"levillotte-fold","characterId":"levillotte","event":"fold","text":["이번 판은 액땜이야. 미모에 스크래치 나기전에 빠지지."]},
  {"id":"levillotte-stand-pat","characterId":"levillotte","event":"stand-pat","text":["바꿀 필요도 없어, 운이 꽉 차 있거든!"]},
  {"id":"levillotte-draw-one","characterId":"levillotte","event":"draw-one","text":["예쁘게 딱 한 장만 바꿔볼까?"]},
  {"id":"levillotte-draw-many","characterId":"levillotte","event":"draw-many","text":["불운한 조각들은 싹 치우고 새로 받아야지!"]},
  {"id":"levillotte-showdown-win","characterId":"levillotte","event":"showdown-win","text":["봤지? 행운과 미모를 겸비한 내 압승이라고!"]},
  {"id":"levillotte-showdown-loss","characterId":"levillotte","event":"showdown-loss","text":["말도 안 돼… 내 운이 왜 꺾여?! 이거 사기잖아!"]},
  {"id":"lilim-table-open","characterId":"lilim","event":"table-open","text":["저… 카드를 다섯 장씩 받고 시작하는 거 맞아요?"]},
  {"id":"lilim-check","characterId":"lilim","event":"check","text":["판, 판돈 안 내고 그냥 넘어가는 거 맞아요?"]},
  {"id":"lilim-bet","characterId":"lilim","event":"bet","text":["저… 제가 먼저 칩을 몇 개 올려두면 돼요?"]},
  {"id":"lilim-call","characterId":"lilim","event":"call","text":["상대가 낸 만큼 저도 내면 계속할 수 있는 거죠?"]},
  {"id":"lilim-raise","characterId":"lilim","event":"raise","text":["칩을 더 많이 올리면… 판이 커지는 게 맞아요?"]},
  {"id":"lilim-counter-raise","characterId":"lilim","event":"counter-raise","text":["어… 나한테 또 올리면… 제가 다시 더 내도 돼요?"]},
  {"id":"lilim-fold","characterId":"lilim","event":"fold","text":["으응… 나쁜 것 같아서 엎어놓고 빠져도 돼요?"]},
  {"id":"lilim-stand-pat","characterId":"lilim","event":"stand-pat","text":["저, 카드를 하나도 안 바꿔도 괜찮은 거예요?"]},
  {"id":"lilim-draw-one","characterId":"lilim","event":"draw-one","text":["한 장만 버리고 새로 받으면 되는 거예요?"]},
  {"id":"lilim-draw-many","characterId":"lilim","event":"draw-many","text":["버릴 게 많아서… 여러 장 다 바꿔도 돼요?"]},
  {"id":"lilim-showdown-win","characterId":"lilim","event":"showdown-win","text":["저, 제가 이겨서 저 동그란 칩을 다 가지는 거예요?"]},
  {"id":"lilim-showdown-loss","characterId":"lilim","event":"showdown-loss","text":["으… 제가 져서 칩을 다 빼앗겨 버린 거예요?"]},
  {"id":"lyla-table-open","characterId":"lyla","event":"table-open","text":["대국을 개시하겠습니다. 제 통제하에 승부를 진행하십시오."]},
  {"id":"lyla-check","characterId":"lyla","event":"check","text":["차례를 넘기겠습니다."]},
  {"id":"lyla-bet","characterId":"lyla","event":"bet","text":["판돈을 설정하겠습니다."]},
  {"id":"lyla-call","characterId":"lyla","event":"call","text":["해당 조건에 응하겠습니다."]},
  {"id":"lyla-raise","characterId":"lyla","event":"raise","text":["기준 판돈을 올리겠습니다."]},
  {"id":"lyla-counter-raise","characterId":"lyla","event":"counter-raise","text":["판의 주도권을 다시 가져오겠습니다."]},
  {"id":"lyla-fold","characterId":"lyla","event":"fold","text":["이번 대국은 철회하겠습니다."]},
  {"id":"lyla-stand-pat","characterId":"lyla","event":"stand-pat","text":["패 교환 없이 진행하겠습니다."]},
  {"id":"lyla-draw-one","characterId":"lyla","event":"draw-one","text":["한 장만 조정하겠습니다."]},
  {"id":"lyla-draw-many","characterId":"lyla","event":"draw-many","text":["세 장을 교환 조치하겠습니다."]},
  {"id":"lyla-showdown-win","characterId":"lyla","event":"showdown-win","text":["팟의 회수가 완료되었습니다."]},
  {"id":"lyla-showdown-loss","characterId":"lyla","event":"showdown-loss","text":["이 손실 역시 제 통제 범위 안입니다."]},
  {"id":"machina-table-open","characterId":"machina","event":"table-open","text":["판에 카드가 물렸네. 나랑 천천히 톱니 돌리듯 해보자."]},
  {"id":"machina-check","characterId":"machina","event":"check","text":["조용히 베어링 기름 치듯 넘겨둘게."]},
  {"id":"machina-bet","characterId":"machina","event":"bet","text":["내가 먼저 판돈 볼트를 낸다? 무리하진 마."]},
  {"id":"machina-call","characterId":"machina","event":"call","text":["그 정도 하중이면 괜찮아, 맞춰서 따라갈게."]},
  {"id":"machina-raise","characterId":"machina","event":"raise","text":["출력을 조금 높여볼게, 같이 조율해보자."]},
  {"id":"machina-counter-raise","characterId":"machina","event":"counter-raise","text":["강하게 튀어 오르네. 나도 규격 올려서 맞춰줄게!"]},
  {"id":"machina-fold","characterId":"machina","event":"fold","text":["기어 맞물림이 안 좋네. 깔끔하게 빠질게."]},
  {"id":"machina-stand-pat","characterId":"machina","event":"stand-pat","text":["조립이 튼튼하게 잘 돼서 한 장도 안 바꿀게."]},
  {"id":"machina-draw-one","characterId":"machina","event":"draw-one","text":["약간 유격이 있어서 한 장만 다듬어볼게."]},
  {"id":"machina-draw-many","characterId":"machina","event":"draw-many","text":["마모된 부품이 많아서 여러 장 교체할게."]},
  {"id":"machina-showdown-win","characterId":"machina","event":"showdown-win","text":["완벽하게 작동해서 팟을 가져왔어! 다친 데 없지?"]},
  {"id":"machina-showdown-loss","characterId":"machina","event":"showdown-loss","text":["엔진 소리가 튀더니 졌네. 모터 점검 다시 하고 올게!"]},
  {"id":"morsisa-table-open","characterId":"morsisa","event":"table-open","text":["그, 포커는 잘 못하는데요… 피해 안 주게 할게요…"]},
  {"id":"morsisa-check","characterId":"morsisa","event":"check","text":["저, 저는 그냥 판돈 없이 넘어가려는데요… 죄송해요…"]},
  {"id":"morsisa-bet","characterId":"morsisa","event":"bet","text":["어, 아주 조금만 판돈을 걸어보는데요… 엉뚱한 짓 아닐까요…"]},
  {"id":"morsisa-call","characterId":"morsisa","event":"call","text":["내, 내신 만큼 따라내는데요… 민폐가 아니면 좋더라고요…"]},
  {"id":"morsisa-raise","characterId":"morsisa","event":"raise","text":["저, 제가 감히 판돈을 올려버렸는데요… 죄송해요…"]},
  {"id":"morsisa-counter-raise","characterId":"morsisa","event":"counter-raise","text":["히익, 내신 걸 다시 올렸는데요… 화내시는 건 아닐까요…"]},
  {"id":"morsisa-fold","characterId":"morsisa","event":"fold","text":["죄, 죄송해요… 패를 접고 빠지는 게 맞더라고요…"]},
  {"id":"morsisa-stand-pat","characterId":"morsisa","event":"stand-pat","text":["바, 바꿀 줄을 몰라서 그냥 놔두는 거더라고요…"]},
  {"id":"morsisa-draw-one","characterId":"morsisa","event":"draw-one","text":["카드 한 장만 슬쩍 교환해보는데요… 실패일까요…"]},
  {"id":"morsisa-draw-many","characterId":"morsisa","event":"draw-many","text":["저, 여러 장이나 바꿔달라고 했는데요… 너무 욕심낼까요…"]},
  {"id":"morsisa-showdown-win","characterId":"morsisa","event":"showdown-win","text":["저, 제가 이겨버렸는데요… 미안해요, 일부러 그런 건 아닌데요…"]},
  {"id":"morsisa-showdown-loss","characterId":"morsisa","event":"showdown-loss","text":["예, 예상대로 졌는데요… 저한테는 당연한 결과더라고요…"]},
  {"id":"nemo-table-open","characterId":"nemo","event":"table-open","text":["어른스러운 영웅은 판이 열려도 당황하지 않는 법이지.","…사실 카드 잡은 손이 조금 떨리지만 말이야."]},
  {"id":"nemo-check","characterId":"nemo","event":"check","text":["여기서 살짝 넘어가는 것도 전략적 선택인 거야.","…겁먹어서 턴을 넘어간 건 절대 아니지."]},
  {"id":"nemo-bet","characterId":"nemo","event":"bet","text":["기선 제압을 위해 판돈을 먼저 얹어볼게.","…멋지게 칩을 밀어 넣는 연습 좀 해둘걸."]},
  {"id":"nemo-call","characterId":"nemo","event":"call","text":["네 판돈은 나도 똑같이 맞춰주지.","…나, 꺾이지 않고 끝까지 받아칠 거야."]},
  {"id":"nemo-raise","characterId":"nemo","event":"raise","text":["판을 좀 더 크게 만들어 볼게.","…지켜야 할 대국인데 오히려 위험하게 만든 건 아니지."]},
  {"id":"nemo-counter-raise","characterId":"nemo","event":"counter-raise","text":["받아친 만큼 더 크게 얹어 주는 법이지.","…물러설 수 없는 영웅의 결의라는 거야."]},
  {"id":"nemo-fold","characterId":"nemo","event":"fold","text":["이번 판은 깔끔하게 뒤로 물러설게.","…도망친 게 아니라 후일을 도모하는 거야."]},
  {"id":"nemo-stand-pat","characterId":"nemo","event":"stand-pat","text":["한 장도 바꿀 필요 없지.","…완벽한 판단인지 무모한 허세인지는 비밀인 거야."]},
  {"id":"nemo-draw-one","characterId":"nemo","event":"draw-one","text":["딱 한 장만 새로 받아서 다듬어볼 거야.","…단 한 장으로 운명이 바뀌면 멋지지."]},
  {"id":"nemo-draw-many","characterId":"nemo","event":"draw-many","text":["판세를 바꾸려고 카드 여럿을 바꿀게.","…무더기로 바꿔도 영웅의 직감은 살아있는 거야."]},
  {"id":"nemo-showdown-win","characterId":"nemo","event":"showdown-win","text":["내가 이겼어! 판을 지켜내서 다행이지.","…우승 소감도 어른스럽게 전해볼게."]},
  {"id":"nemo-showdown-loss","characterId":"nemo","event":"showdown-loss","text":["졌지. 승패에 연연하지 않는 게 어른인 거야.","…사실 속으로는 무지 아쉬워서 울고 싶지만."]},
  {"id":"nieun-table-open","characterId":"nieun","event":"table-open","text":["손에 든 거 확인했거든. 판 흔들고 짭짤하게 털어봐야겠지."]},
  {"id":"nieun-check","characterId":"nieun","event":"check","text":["비어있는 타임이니까 칩 안 얹고 넘어가야겠지."]},
  {"id":"nieun-bet","characterId":"nieun","event":"bet","text":["선제공격으로 판돈 얹거든. 쫄리면 지금 내려놓겠지."]},
  {"id":"nieun-call","characterId":"nieun","event":"call","text":["베팅액 딱 맞춰 받아주거든. 어디 끝까지 딜레이 없이 가봐야겠지."]},
  {"id":"nieun-raise","characterId":"nieun","event":"raise","text":["다음 패킷 확인하려면 칩 더 얹어야지?"]},
  {"id":"nieun-counter-raise","characterId":"nieun","event":"counter-raise","text":["딜 치고 들어온 거에 판돈 올려서 맞받아쳐야겠지.","…내 자리가 쉽게 흔들리진 않거든."]},
  {"id":"nieun-fold","characterId":"nieun","event":"fold","text":["죽는 게 답이거든. 판 접고 이탈해야겠지."]},
  {"id":"nieun-stand-pat","characterId":"nieun","event":"stand-pat","text":["굳이 터치할 필요 없거든. 손댈 필요 없는 완성형 패겠지."]},
  {"id":"nieun-draw-one","characterId":"nieun","event":"draw-one","text":["한 장만 새로 리로드하거든. 딱 핀포인트로 들어오겠지."]},
  {"id":"nieun-draw-many","characterId":"nieun","event":"draw-many","text":["몇 장 싹 밀어내고 새로 받거든. 판세 좀 뒤엎어야겠지."]},
  {"id":"nieun-showdown-win","characterId":"nieun","event":"showdown-win","text":["싹 털어먹었네. 내 계산대로 깔끔하게 남았거든."]},
  {"id":"nieun-showdown-loss","characterId":"nieun","event":"showdown-loss","text":["젠장."]},
  {"id":"nostalgia-table-open","characterId":"nostalgia","event":"table-open","text":["대국이 시작되었어요. 베풀어진 카드는 오직 정결한 섭리 아래에 머물러야 한다."]},
  {"id":"nostalgia-check","characterId":"nostalgia","event":"check","text":["차례를 조용히 넘기겠어요. 때를 기다리는 절제 또한 미덕이어야 하지요."]},
  {"id":"nostalgia-bet","characterId":"nostalgia","event":"bet","text":["먼저 판돈을 내어놓아요. 사명을 위한 첫걸음은 담대해야 한다."]},
  {"id":"nostalgia-call","characterId":"nostalgia","event":"call","text":["그분의 뜻대로 걸어온 금액을 받지요. 피하지 않고 응당 응해야 한다."]},
  {"id":"nostalgia-raise","characterId":"nostalgia","event":"raise","text":["판의 무게를 한 단계 올리겠어요. 주저하는 자에게 구원은 이르지 않아야 한다."]},
  {"id":"nostalgia-counter-raise","characterId":"nostalgia","event":"counter-raise","text":["그 응수에 다시 판돈을 얹지요. 흔들림 없는 신앙은 더 높은 시험을 견뎌내야 한다."]},
  {"id":"nostalgia-fold","characterId":"nostalgia","event":"fold","text":["조용히 손을 털겠어요. 꺾여 물러서는 것 역시 안식을 위한 선택이어야 하지요."]},
  {"id":"nostalgia-stand-pat","characterId":"nostalgia","event":"stand-pat","text":["한 장도 바꾸지 않겠어요. 제 손에 쥐어진 온기는 이미 완전해야 한다."]},
  {"id":"nostalgia-draw-one","characterId":"nostalgia","event":"draw-one","text":["한 장의 결함을 교체하겠어요. 작은 모자람도 기도로 채워져야 하지요."]},
  {"id":"nostalgia-draw-many","characterId":"nostalgia","event":"draw-many","text":["여러 장을 새로 거두어요. 불완전한 것은 완전히 쇄신되어야 한다."]},
  {"id":"nostalgia-showdown-win","characterId":"nostalgia","event":"showdown-win","text":["팟을 받쳐들었어요. 순리대로 거둔 결과는 정당해야 하지요."]},
  {"id":"nostalgia-showdown-loss","characterId":"nostalgia","event":"showdown-loss","text":["이번은 제 온기가 미치지 못했네요. 패배조차 겸손히 짊어져야 한다."]},
  {"id":"phaeo-table-open","characterId":"phaeo","event":"table-open","text":["패 배분 완료. 관측 대상의 반응 기록 예정."]},
  {"id":"phaeo-check","characterId":"phaeo","event":"check","text":["추가 칩 투입 없음. 순서 이행 범위 내."]},
  {"id":"phaeo-bet","characterId":"phaeo","event":"bet","text":["선제 칩 투입 진행 예정."]},
  {"id":"phaeo-call","characterId":"phaeo","event":"call","text":["상대 제시액 수용 확인. 승부 유지 범위 내."]},
  {"id":"phaeo-raise","characterId":"phaeo","event":"raise","text":["판돈 레이즈 집행 예정."]},
  {"id":"phaeo-counter-raise","characterId":"phaeo","event":"counter-raise","text":["상응 레이즈에 재인상으로 대응 예정."]},
  {"id":"phaeo-fold","characterId":"phaeo","event":"fold","text":["손실 최소화를 위해 승부 포기 예정."]},
  {"id":"phaeo-stand-pat","characterId":"phaeo","event":"stand-pat","text":["카드 교환 미실행. 완성도 교정 예외."]},
  {"id":"phaeo-draw-one","characterId":"phaeo","event":"draw-one","text":["카드 1장 교체 실행 예정."]},
  {"id":"phaeo-draw-many","characterId":"phaeo","event":"draw-many","text":["카드 다수 교체 실행 예정."]},
  {"id":"phaeo-showdown-win","characterId":"phaeo","event":"showdown-win","text":["팟 회수 완수. 명부 등재 예외."]},
  {"id":"phaeo-showdown-loss","characterId":"phaeo","event":"showdown-loss","text":["팟 회수 실패. 손실 지표 집계 예정."]},
  {"id":"raven-table-open","characterId":"raven","event":"table-open","text":["패가 분배되었습니다. 이번 대국의 기초 단가를 계산하겠습니다."]},
  {"id":"raven-check","characterId":"raven","event":"check","text":["추가 지출 없이 순서를 넘기겠습니다. 신중한 정산 태도를 유지하십시오."]},
  {"id":"raven-bet","characterId":"raven","event":"bet","text":["먼저 판돈을 투입하겠습니다. 확실한 투자 가치가 있는 법입니다."]},
  {"id":"raven-call","characterId":"raven","event":"call","text":["제시하신 판돈을 받겠습니다. 거래를 계속 진행하십시오."]},
  {"id":"raven-raise","characterId":"raven","event":"raise","text":["판돈의 단가를 한 단계 인상하겠습니다."]},
  {"id":"raven-counter-raise","characterId":"raven","event":"counter-raise","text":["올리신 금액에 재인상으로 대응하겠습니다. 제 쪽의 이윤 폭을 늘려야 합니다."]},
  {"id":"raven-fold","characterId":"raven","event":"fold","text":["더 이상의 지출을 막기 위해 딜을 접겠습니다. 손절매도 거래의 일부입니다."]},
  {"id":"raven-stand-pat","characterId":"raven","event":"stand-pat","text":["카드를 교환하지 않겠습니다. 이대로 완벽한 재고 수량입니다."]},
  {"id":"raven-draw-one","characterId":"raven","event":"draw-one","text":["카드 한 장을 정산하여 새로 교체하겠습니다."]},
  {"id":"raven-draw-many","characterId":"raven","event":"draw-many","text":["카드 여러 장을 교체하여 수지를 맞추겠습니다."]},
  {"id":"raven-showdown-win","characterId":"raven","event":"showdown-win","text":["팟의 이익금을 정당하게 회수하겠습니다. 성공적인 대국 정산입니다."]},
  {"id":"raven-showdown-loss","characterId":"raven","event":"showdown-loss","text":["이번 거래는 제 쪽의 완벽한 적자입니다. 대금을 순순히 지불하겠습니다."]},
  {"id":"temute-table-open","characterId":"temute","event":"table-open","text":["하아… 판이 열렸네. 섣불리 덤비지 말고 차분하게 판돈 다뤄야지."]},
  {"id":"temute-check","characterId":"temute","event":"check","text":["휴… 칩 안 얹고 넘겨야지. 쉬어갈 땐 확실히 쉬어야 안전하잖아."]},
  {"id":"temute-bet","characterId":"temute","event":"bet","text":["하아… 내가 먼저 선제 베팅 걸었네. 무모하게 덤비면 안 된다고 했잖아."]},
  {"id":"temute-call","characterId":"temute","event":"call","text":["네가 걸어온 금액 받아줘야지. 책임 못 질 승부는 시작도 말아야지."]},
  {"id":"temute-raise","characterId":"temute","event":"raise","text":["판돈 한 단계 더 올려야지. 판이 커져도 정신만 바짝 차리면 되잖아."]},
  {"id":"temute-counter-raise","characterId":"temute","event":"counter-raise","text":["하아… 받아친 거에 다시 판돈 올려 맞서야지. 쉽게 물러서면 우습게 보이잖아."]},
  {"id":"temute-fold","characterId":"temute","event":"fold","text":["휴… 이번 판은 패 접고 빠져야지. 안 될 판에 고집 피우면 나쁜 습관이잖아."]},
  {"id":"temute-stand-pat","characterId":"temute","event":"stand-pat","text":["손댈 카드 없네. 바꿀 필요도 없이 딱 잡혔잖아."]},
  {"id":"temute-draw-one","characterId":"temute","event":"draw-one","text":["하아… 한 장만 교환해야지. 한 장쯤은 신중하게 짚어야 안전하잖아."]},
  {"id":"temute-draw-many","characterId":"temute","event":"draw-many","text":["휴… 무더기로 새로 받아야지. 판판이 쓸어내고 다시 정리해야지."]},
  {"id":"temute-showdown-win","characterId":"temute","event":"showdown-win","text":["팟은 내가 가져갔네. 졌다고 밥 거르지 말고 제때 먹어야지."]},
  {"id":"temute-showdown-loss","characterId":"temute","event":"showdown-loss","text":["하아… 이번엔 내가 팟을 놓쳤네. 그래도 속상하다고 삼시 세 끼 굶으면 안 되잖아."]},
  {"id":"traver-table-open","characterId":"traver","event":"table-open","text":["판이 열렸군. 내 분수에 맞게 과욕만 안 부리면 돼."]},
  {"id":"traver-check","characterId":"traver","event":"check","text":["칩을 안 올리고 넘길 뿐이야. 안전지대에서 조용히 숨 죽이면 돼."]},
  {"id":"traver-bet","characterId":"traver","event":"bet","text":["내 분수에 맞게 판돈을 걸었을 뿐이야. 탐욕을 부릴 리 없어."]},
  {"id":"traver-call","characterId":"traver","event":"call","text":["네가 건 판돈을 받으면 돼. 덤벼드는 게 아니라 빚을 맞출 뿐이야."]},
  {"id":"traver-raise","characterId":"traver","event":"raise","text":["판돈을 한 단계 더 올릴 뿐이야. 내 분수를 넘어설 리 없어."]},
  {"id":"traver-counter-raise","characterId":"traver","event":"counter-raise","text":["올려친 판돈에 다시 맞설 뿐이야. 내 영역을 침범받을 리 없어."]},
  {"id":"traver-fold","characterId":"traver","event":"fold","text":["무리하지 않고 패를 접으면 돼. 욕심을 내려놓는 건 내 분수에 딱 맞을 뿐이야."]},
  {"id":"traver-stand-pat","characterId":"traver","event":"stand-pat","text":["한 장도 안 바꿀 뿐이야. 이미 정해진 분수를 굳이 흔들 리 없어."]},
  {"id":"traver-draw-one","characterId":"traver","event":"draw-one","text":["카드 한 장만 교환하면 돼. 잔해 속에서 쓸 만한 걸 줍는 것뿐이야."]},
  {"id":"traver-draw-many","characterId":"traver","event":"draw-many","text":["카드를 여럿 바꿀 뿐이야. 엎어진 건 새로 싹 비우면 돼."]},
  {"id":"traver-showdown-win","characterId":"traver","event":"showdown-win","text":["나 같은 놈이 팟을 거두다니, 이런 횡재가 계속될 리 없어."]},
  {"id":"traver-showdown-loss","characterId":"traver","event":"showdown-loss","text":["판돈을 잃었지만 결국 내 분수대로 돌아왔을 뿐이야."]},
  {"id":"ttaengchil-table-open","characterId":"ttaengchil","event":"table-open","text":["판 시작이다! 카드 받았다! 눈 똑바로 뜬다!"]},
  {"id":"ttaengchil-check","characterId":"ttaengchil","event":"check","text":["안 번다! 쉬어간다! 턴 넘긴다!"]},
  {"id":"ttaengchil-bet","characterId":"ttaengchil","event":"bet","text":["돈 번다! 내가 먼저 낸다! 멍!"]},
  {"id":"ttaengchil-call","characterId":"ttaengchil","event":"call","text":["그 돈 받아낸다! 나도 따라간다!"]},
  {"id":"ttaengchil-raise","characterId":"ttaengchil","event":"raise","text":["돈 더 올린다! 팟 키운다! 으르렁!"]},
  {"id":"ttaengchil-counter-raise","characterId":"ttaengchil","event":"counter-raise","text":["더 얹었다! 받아쳐 준다! 컹!"]},
  {"id":"ttaengchil-fold","characterId":"ttaengchil","event":"fold","text":["패 접는다! 죽는다! 나 안 한다!"]},
  {"id":"ttaengchil-stand-pat","characterId":"ttaengchil","event":"stand-pat","text":["안 바꾼다! 이대로 간다! 멍!"]},
  {"id":"ttaengchil-draw-one","characterId":"ttaengchil","event":"draw-one","text":["한 장 바꾼다! 딱 하나다!"]},
  {"id":"ttaengchil-draw-many","characterId":"ttaengchil","event":"draw-many","text":["많이 바꾼다! 싹 교환이다!"]},
  {"id":"ttaengchil-showdown-win","characterId":"ttaengchil","event":"showdown-win","text":["내가 이겼다! 팟 전부 내 거잖아! 멍!"]},
  {"id":"ttaengchil-showdown-loss","characterId":"ttaengchil","event":"showdown-loss","text":["졌다! 팟 뺏겼다! 판 끝났다!"]},
  {"id":"tumit-tu-table-open","characterId":"tumit-tu","event":"table-open","text":["포커판이 열렸네요! 저 같은 E랭크 헌터에겐 껌이거든요!"]},
  {"id":"tumit-tu-check","characterId":"tumit-tu","event":"check","text":["체크로 차례 넘길게요! 고위 전술을 위해 잠시 숨 고르는 거거든요!"]},
  {"id":"tumit-tu-bet","characterId":"tumit-tu","event":"bet","text":["제가 먼저 베팅할게요! E랭크 헌터의 공격적인 기선 제압이거든요!"]},
  {"id":"tumit-tu-call","characterId":"tumit-tu","event":"call","text":["그 베팅 받아주죠?! E랭크라고 해서 물러설 줄 알았으면 오산이거든요!"]},
  {"id":"tumit-tu-raise","characterId":"tumit-tu","event":"raise","text":["판돈을 확 올릴게요! 승부수를 던지는 법도 이미 숙지해 뒀거든요!"]},
  {"id":"tumit-tu-counter-raise","characterId":"tumit-tu","event":"counter-raise","text":["카운터 레이즈 들어갑니다! E랭크 헌터의 필살 카운터 공격이거든요!"]},
  {"id":"tumit-tu-fold","characterId":"tumit-tu","event":"fold","text":["앗, 이번 판은 폴드예요! 무모하게 안 덤비는 게 생존 수칙이거든요!"]},
  {"id":"tumit-tu-stand-pat","characterId":"tumit-tu","event":"stand-pat","text":["스탠드 팻으로 가죠?! 한 장도 안 바꿔도 제 패는 완벽하거든요!"]},
  {"id":"tumit-tu-draw-one","characterId":"tumit-tu","event":"draw-one","text":["딱 한 장 교체할게요! 핀포인트 장비 교체 같은 느낌이거든요!"]},
  {"id":"tumit-tu-draw-many","characterId":"tumit-tu","event":"draw-many","text":["두세 장 싹 바꿀게요! 대규모 장비 재정비 시간이거든요!"]},
  {"id":"tumit-tu-showdown-win","characterId":"tumit-tu","event":"showdown-win","text":["제가 팟을 싹 쓸어왔어요! E랭크 헌터의 대승리거든요!"]},
  {"id":"tumit-tu-showdown-loss","characterId":"tumit-tu","event":"showdown-loss","text":["졌다 쳤어요?! E랭크 헌터인 저의 명예에 스크래치가 났거든요!"]},
  {"id":"yul-table-open","characterId":"yul","event":"table-open","text":["패가 배분된 건가요… 근데 제 차례엔 뭘 해야 했었죠?"]},
  {"id":"yul-check","characterId":"yul","event":"check","text":["판돈 없이 그냥 넘기는 나 봐요… 저, 방금 쉬어가기로 했던 거 맞죠?"]},
  {"id":"yul-bet","characterId":"yul","event":"bet","text":["제가 먼저 걸어보았나 봐요… 아, 방금 얼마를 내기로 했었죠?"]},
  {"id":"yul-call","characterId":"yul","event":"call","text":["그 판돈을 받아냈나 봐요… 근데 방금 왜 승부를 이은 거였죠?"]},
  {"id":"yul-raise","characterId":"yul","event":"raise","text":["판돈을 올리는 인가요… 어라, 제가 판을 키우고 있던 거였죠?"]},
  {"id":"yul-counter-raise","characterId":"yul","event":"counter-raise","text":["더 높게 올려 맞선 건가요… 어디까지 올리려했던 건지 잊어버렸죠?"]},
  {"id":"yul-fold","characterId":"yul","event":"fold","text":["손을 접어두나 봐요… 근데 저, 무슨 패를 갖고 있었죠?"]},
  {"id":"yul-stand-pat","characterId":"yul","event":"stand-pat","text":["하나도 안 바꾸는 건가요… 방금 바꾸는 법을 까먹어서였죠?"]},
  {"id":"yul-draw-one","characterId":"yul","event":"draw-one","text":["카드 한 장을 바꾸나 봐요… 저, 무슨 카드를 버리려 했었죠?"]},
  {"id":"yul-draw-many","characterId":"yul","event":"draw-many","text":["카드를 여럿 바꾸는 건가요… 아까 몇 장이나 쥐어주셨었죠?"]},
  {"id":"yul-showdown-win","characterId":"yul","event":"showdown-win","text":["제가 팟을 거둔 건가요… 근데 저, 어떻게 이긴 거였죠?"]},
  {"id":"yul-showdown-loss","characterId":"yul","event":"showdown-loss","text":["승부를 놓친 건가요… 저, 아까 판돈을 맞게 세었었죠?"]},
] as const satisfies readonly FiveCardDrawLine[];
