import { writeFileSync } from "node:fs";
import { resolve } from "node:path";
import {
  MATCH_PAIRS_SPREAD_PRICING_VERSION,
  createMatchPairsState,
  isCpuActor,
  matchPairsPerformance,
  reduceMatchPairs,
  type MatchPairsDifficulty,
  type MatchPairsFocus,
  type MatchPairsOpponent,
  type MatchPairsState,
} from "@lucky-arcade/match-pairs";
import { TEMEROSA_MATCH_PAIRS_PERSONAS } from "../src/features/match-pairs/temerosa-match-pairs-personas.ts";
import { TEMEROSA_MATCH_PAIRS_FACES, TEMEROSA_MATCH_PAIRS_PACK_VERSION } from "../src/features/match-pairs/temerosa-match-pairs-selection.ts";

const SAMPLE_SIZE = 600;
const DIFFICULTIES = ["easy", "normal"] as const;
const FOCUSES = ["relaxed", "standard", "sharp"] as const;

const opponents: readonly MatchPairsOpponent[] = Object.entries(TEMEROSA_MATCH_PAIRS_PERSONAS).map(([id, persona]) => ({
  id,
  name: id,
  portraits: { neutral: id, pleased: id, tense: id },
  despairPortrait: id,
  winCreditMultiplier: persona.difficultyTier === 3 ? 2.5 : persona.difficultyTier === 2 ? 2 : 1.5,
  ...persona,
}));

const quotes = opponents.flatMap((opponent) => DIFFICULTIES.flatMap((difficulty) => FOCUSES.map((focus) => quote(opponent, difficulty, focus))));
const output = `/* Generated by apps/web/scripts/generate-match-pairs-spreads.ts. Do not edit by hand. */\n`
  + `import type { MatchPairsSpreadQuote } from "@lucky-arcade/match-pairs";\n\n`
  + `export const TEMEROSA_MATCH_PAIRS_SPREAD_QUOTES = Object.freeze(${JSON.stringify(quotes, null, 2)}) as readonly MatchPairsSpreadQuote[];\n`;
writeFileSync(resolve("src/features/match-pairs/temerosa-match-pairs-spreads.generated.ts"), output);

function quote(opponent: MatchPairsOpponent, difficulty: MatchPairsDifficulty, focus: MatchPairsFocus) {
  const scores = Array.from({ length: SAMPLE_SIZE }, (_, index) => simulate(opponent, difficulty, focus, index)).sort((left, right) => left - right);
  const candidates = [...new Set(scores)].sort((left, right) => left - right);
  const priced = candidates.map((targetScore) => ({ targetScore, cover: scores.filter((score) => score > targetScore).length }));
  const selected = priced.filter(({ cover }) => cover / SAMPLE_SIZE <= .49).sort((left, right) => right.cover - left.cover || left.targetScore - right.targetScore)[0];
  const cover = selected?.cover ?? 0;
  const rate = Math.round(cover * 10_000 / SAMPLE_SIZE);
  const available = Boolean(selected && rate >= 3_000 && rate <= 4_900);
  return {
    contract: "match-pairs-spread/0.1" as const,
    quoteId: `${opponent.id}:${difficulty}:${focus}`,
    pricingVersion: MATCH_PAIRS_SPREAD_PRICING_VERSION,
    opponentId: opponent.id,
    difficulty,
    focus,
    targetScore: selected?.targetScore ?? Math.max(...scores),
    estimatedCoverRateBps: rate,
    sampleSize: SAMPLE_SIZE,
    available,
  };
}

function simulate(opponent: MatchPairsOpponent, difficulty: MatchPairsDifficulty, focus: MatchPairsFocus, index: number): number {
  const seed = `spread:${opponent.id}:${difficulty}:${focus}:${index}`;
  let state = createMatchPairsState(TEMEROSA_MATCH_PAIRS_FACES, opponents, TEMEROSA_MATCH_PAIRS_PACK_VERSION, seed, difficulty, opponent.id, "pricing", "play", undefined, focus, "practice");
  state = reduceMatchPairs(TEMEROSA_MATCH_PAIRS_FACES, opponents, state, { type: "start", seed });
  const observed = new Map<number, string>();
  while (state.status !== "complete") {
    if (state.status === "checking") {
      observe(state, observed);
      state = reduceMatchPairs(TEMEROSA_MATCH_PAIRS_FACES, opponents, state, { type: "resolve" });
      continue;
    }
    if (isCpuActor(state, state.currentTurn)) {
      state = reduceMatchPairs(TEMEROSA_MATCH_PAIRS_FACES, opponents, state, { type: "npc-reveal" });
      observe(state, observed);
      continue;
    }
    const cardIndex = perfectPublicMemoryChoice(state, observed);
    state = reduceMatchPairs(TEMEROSA_MATCH_PAIRS_FACES, opponents, state, { type: "player-reveal", index: cardIndex });
    observe(state, observed);
  }
  return matchPairsPerformance(state).performanceScore;
}

function observe(state: MatchPairsState, memory: Map<number, string>): void {
  for (const index of state.openIndexes) memory.set(index, state.cards[index]!.pairId);
}

function perfectPublicMemoryChoice(state: MatchPairsState, memory: Map<number, string>): number {
  const matched = new Set(state.matchedPairIds);
  const available = state.cards.map((_, index) => index).filter((index) => !matched.has(state.cards[index]!.pairId) && !state.openIndexes.includes(index));
  if (state.openIndexes.length === 1) {
    const openPair = memory.get(state.openIndexes[0]!);
    const known = available.find((index) => memory.get(index) === openPair);
    if (known !== undefined) return known;
  } else {
    const grouped = new Map<string, number[]>();
    for (const index of available) {
      const pairId = memory.get(index);
      if (pairId) grouped.set(pairId, [...(grouped.get(pairId) ?? []), index]);
    }
    const pair = [...grouped.values()].find((indexes) => indexes.length >= 2);
    if (pair?.[0] !== undefined) return pair[0];
  }
  return available.find((index) => !memory.has(index)) ?? available[0]!;
}
