import type { OldMaidLine, OldMaidLineEvent } from "./contracts.ts";

type LegacyLineEvent = Exclude<OldMaidLineEvent, "table-open" | "finish-1st" | "finish-2nd" | "finish-3rd" | "defeat">;
type LineText = Readonly<Record<LegacyLineEvent, readonly string[]>>;

const text = {
  pale: {
    watching: ["넷이 둘러앉아 차례만 기다리니 꼭 항구에 묶인 배 같거든.", "배 대신 카드가 떠다니는 것뿐이지만."],
    "idle-draw": ["바다에서 생선 한 마리 더 건졌거든, 양파 껍질을 까다 보면 언젠가 알맹이가 나오잖아."],
    "pair-discard": ["어라, 둘이 딱 맞았네. 서로 모르는 물고기라도", "같은 그물에 엮이면 사이좋은 한 쌍이 되거든."],
    "taken-from": ["가져가도 돼. 파도가 배를 딴 데로 밀어내도 항해했던 사실 자체가 사라지는 건 아니잖아."],
    "pair-made": ["오, 맞췄어. 썩은 양파에서 굵은 진주가 튀어나온 기분이네.", "양파 냄새는 여전히 싫지만."],
    "joker-drawn": ["짝이 없는 카드를 들었다고 죄는 아니거든.", "바다 위 외로운 섬도 이름이 붙으면 지도에 남잖아."],
    "joker-left": ["혼자 저 멀리 보내는 기분이네. 철새를 바라보는 어부 같아.", "…근데 어부가 철새를 잡던가?"],
    emptied: ["손에 들고 있던 짝을 다 찾아줬거든.", "빈손은 빈 배랑 비슷해서 이제 어디로든 갈 수 있잖아."],
  },
  kano: {
    watching: ["괜찮아요. 아직 아무도 위험해지진 않았네요. …조금 답답하긴 하지만."],
    "idle-draw": ["잘 받았습니다. 이 정도 카드는 충분히 감당할 수 있어요."],
    "pair-discard": ["깔끔하게 버리는 편이 서로한테 낫네요. …솔직히 지긋지긋했거든요."],
    "taken-from": ["이 카드였군요. 부르셨으니 기꺼이 응답해 드려야죠."],
    "pair-made": ["전부 예상하고 있었습니다. …사실 방금 속으로 엄청 쫄았잖아."],
    "joker-drawn": ["괜찮아요. 전 이것보다 더한 짐도 오래 들고 있어 봤네요."],
    "joker-left": ["미안해요. 이 카드는 제 힘으로도 도저히 녹일 수가 없었네요."],
    emptied: ["저는 이만 빠질게요. 어차피 혼자 남겨지는 건 익숙하니까요."],
  },
  nemo: {
    watching: ["다들 진지하네. 멋진 어른은 이럴 때 쿨하게 웃어줘야지.", "…근데 입꼬리가 안 올라가네."],
    "idle-draw": ["한 장 가져왔어. 괜찮아, 이 정도 시련으로 도망치진 않을 거거든."],
    "pair-discard": ["짝 맞춰서 버렸지. 원래 영웅은 정리정돈도 잘해. …음, 방금 건 좀 안 멋있었나?"],
    "taken-from": ["뽑아가도 돼. 가진 걸 나눠주는 게 진짜 어른의 여유니까. …아까운 건 아닌데, 진짜로."],
    "pair-made": ["봤지? 짝 맞췄어! 나도 하면 된다니까. …아니, 처음부터 다 계산해 둔 거야."],
    "joker-drawn": ["조커가 왔네. 진짜 떨린다. …그래도 나, 절대로 안 도망칠 거야."],
    "joker-left": ["휴, 넘어갔다. 방금 뽑은 사람한테는 미안하지만 끝까지 같이 있어 줄게."],
    emptied: ["내 손패는 다 비웠어! 자, 남은 사람도 무사히 데리고 가야지."],
  },
  bacikal: {
    watching: ["다들 망설이네. 난 이미 마음 정했어."],
    "idle-draw": ["이거면 돼. 더 좋은 카드가 있었대도 바꿀 생각 없어."],
    "pair-discard": ["짝 맞으면 버려. 그게 이 판 규칙이야."],
    "taken-from": ["가져가. 집어 들었으면 후회하지 말고."],
    "pair-made": ["짝 맞췄어. 그냥 운이야. 실력이라고 포장할 생각 없어."],
    "joker-drawn": ["조커네. 들어왔으면 품는 거지. 누구 원망 안 해."],
    "joker-left": ["넘겼어. 지나간 손패는 안 돌아봐."],
    emptied: ["끝. 털어낸 카드에 미련 없어."],
  },
  alger: {
    watching: ["대국 진행 이상 없음. 특이사항 없음. …근데 다들 손이 너무 느려."],
    "idle-draw": ["신규 카드 수령 완료. 내용물 이의 신청 불가."],
    "pair-discard": ["동일 수치 페어 정리 완료. 해당 건 종결 처리."],
    "taken-from": ["카드 반출 승인. 사후 위험 부담은 반출자 본인 몫."],
    "pair-made": ["예상 범위 내 수순. …칫, 솔직히 운인데 안 적어야지."],
    "joker-drawn": ["위험 요소 진입. …규정집 다시 확인해 봐야겠네."],
    "joker-left": ["조커 인수인계 완료. 발생할 피해는 현 담당자 책임."],
    emptied: ["본인 할당량 소진 완료. …근데 나 이제 진짜 딴짓해도 되나?"],
  },
  nieun: {
    watching: ["경우의 수는 다 털었네. 역시 정보상 짬바지. …정작 제일 중요한 건 못 읽었지만."],
    "idle-draw": ["기록 하나 추가. 축하해, 내 인생에 또 변수 하나 들어왔네."],
    "pair-discard": ["둘 버림. 현실 계산도 이렇게 클릭 한 번에 정리되면 얼마나 좋아."],
    "taken-from": ["가져가든가. 어차피 내 손에 든 건 죄다 금방 사라지거든."],
    "pair-made": ["짝 맞췄네. 내 계산이 완벽했던 거지. …솔직히 그냥 운이지만."],
    "joker-drawn": ["이 똥패는 왜 또 나한테 오는데. 뭐, 내가 안고 있는 게 속 편하지."],
    "joker-left": ["넘겼다. 별감정 없어. …약간 미안하긴 한데."],
    emptied: ["손패 털었네. 다들 일어나라는데, 난 이 자리 그대로 말뚝 박을 거거든."],
  },
  lyla: {
    watching: ["대국은 통제 범위 안에서 진행 중입니다."],
    "idle-draw": ["예상된 손실입니다. 문제없습니다."],
    "pair-discard": ["위험 요소 두 건을 즉시 폐기했습니다."],
    "taken-from": ["수령하십시오. 이미 제 계산에 반영된 건입니다."],
    "pair-made": ["관리 체계가 정상 작동 중입니다."],
    "joker-drawn": ["제가 회수하는 편이 안전합니다."],
    "joker-left": ["적절한 위치로 재배치했습니다. 제 판단입니다."],
    emptied: ["제 담당 구역은 정리 완료했습니다. 남은 작업은 각자 처리하십시오."],
  },
  riel: {
    watching: ["…일단 적어 뒀어요. 별일 없었던 걸로."],
    "idle-draw": ["한 장 수령했네요. 대장에 남길게요."],
    "pair-discard": ["정리된 건 목록에서 바로 뺄게요."],
    "taken-from": ["편하게 집어가세요. 장부엔 적겠지만요."],
    "pair-made": ["어, 맞았네요! 이런 것도 기재하나요?"],
    "joker-drawn": ["이건… 어디로 분류해야 할지 애매하네요."],
    "joker-left": ["넘어갔네요. 담당자 변경으로 적어 둡니다."],
    emptied: ["제 몫은 끝났어요. 대장 기록은 계속됩니다."],
  },
  wares: {
    watching: ["다들 손가락이 떨리네. 기다림은 종이에 잘 안 남아."],
    "idle-draw": ["얇고 납작한 게 왔네. 오래 머물 것 같진 않고."],
    "pair-discard": ["둘이 나갔네. 빈자리에 춤이나 출까 봐."],
    "taken-from": ["잘 집어가네. 네 손에 얼마나 머물려나."],
    "pair-made": ["같은 눈 둘이 만났네. 참 드문 일이야."],
    "joker-drawn": ["아. 아직 끝나지 않은 문장이 들어왔구나."],
    "joker-left": ["잘 가네. 모자만 훌렁 털고 말이야."],
    emptied: ["내 손은 비었고 의자는 아직 따뜻하구나."],
  },
} as const satisfies Readonly<Record<string, LineText>>;

export const temerosaOldMaidLines: readonly OldMaidLine[] = Object.entries(text).flatMap(([characterId, events]) =>
  Object.entries(events).map(([event, beats]) => ({
    id: `${characterId}-${event}`,
    characterId,
    event: event as OldMaidLineEvent,
    text: beats,
  })),
);
