import type { OldMaidLine } from "./contracts.ts";

/** Generated verbatim from docs/TEMEROSA-OLD-MAID-CEREMONY-DIALOGUE.md. */
export const temerosaOutcomeOldMaidLines = [
  { id: "pale-table-open", characterId: "pale", event: "table-open", text: ["넷이 모여 앉으니 배도 없는데 괜히 출항하는 기분이 들거든.", "펼쳐진 카드가 꼭 파도 같잖아."] },
  { id: "pale-finish-1st", characterId: "pale", event: "finish-1st", text: ["제일 먼저 다 짝지어 줬네.", "흩어진 물고기가 한 그물에 모인 기분이야. 비린내는 싫지만."] },
  { id: "pale-finish-2nd", characterId: "pale", event: "finish-2nd", text: ["나도 드디어 끝났거든. 두 번째 도착한 항구라고 해서", "첫 번째 바다보다 안 아름다운 건 아니잖아."] },
  { id: "pale-finish-3rd", characterId: "pale", event: "finish-3rd", text: ["간신히 다 맞춰서 털어냈네. 마지막 한 쌍은", "바다가 아니라 팍팍한 맨땅에서 헤엄치는 것만큼 힘들었거든."] },
  { id: "pale-defeat", characterId: "pale", event: "defeat", text: ["결국 내 손에 남았잖아. 짝 없는 불쌍한 카드랑", "최초의 베스티아라라니, 완전 딴판인데 묘하게 닮았네."] },
  { id: "kano-table-open", characterId: "kano", event: "table-open", text: ["시작하죠. 다들 무사히 끝날 거예요. …내가 반드시 그렇게 만들 거니까."] },
  { id: "kano-finish-1st", characterId: "kano", event: "finish-1st", text: ["제가 1등으로 끝냈네요. 신이라면 당연한 결과죠. …아, 근데 나 먼저 가도 되나?"] },
  { id: "kano-finish-2nd", characterId: "kano", event: "finish-2nd", text: ["두 번째로 마쳤네요. 남은 분들은 제가 조용히 지켜볼게요."] },
  { id: "kano-finish-3rd", characterId: "kano", event: "finish-3rd", text: ["겨우 빠져나왔네요. 전부 제 계산대로였어요. …하마터면 진짜 골로 갈 뻔했잖아."] },
  { id: "kano-defeat", characterId: "kano", event: "defeat", text: ["제가 끝까지 들게요. 응답할 자가 마지막 책임도 지니까요. …사실 무서워 죽겠네."] },
  { id: "nemo-table-open", characterId: "nemo", event: "table-open", text: ["좋아, 대결 시작이야! 원래 진짜 어른은 카드 뽑을 때 손 안 떨거든. …아마 그럴걸?"] },
  { id: "nemo-finish-1st", characterId: "nemo", event: "finish-1st", text: ["내가 1등이네! 완벽한 영웅은 퇴장도 전광석화지.", "…근데 명색이 영웅인데 혼자 쏙 빠져도 되나?"] },
  { id: "nemo-finish-2nd", characterId: "nemo", event: "finish-2nd", text: ["두 번째로 끝냈어. 모두를 단번에 구하진 못했지만, 아직 포기하긴 이르지."] },
  { id: "nemo-finish-3rd", characterId: "nemo", event: "finish-3rd", text: ["휴, 살았다! 아니, 영웅답게 멋지게 탈출한 거지. 자, 남아있는 사람도 다 끌어줄게."] },
  { id: "nemo-defeat", characterId: "nemo", event: "defeat", text: ["이 카드, 결국 내 손에 남았네. 솔직히 너무 무섭거든.", "그래도 나 도망 안 쳐. 나한테 맡기고, 다들 같이 돌아가자."] },
  { id: "bacikal-table-open", characterId: "bacikal", event: "table-open", text: ["시작해. 쥔 카드 가지고 쓸데없는 고민 안 해."] },
  { id: "bacikal-finish-1st", characterId: "bacikal", event: "finish-1st", text: ["판 끝났어. 쓸데없이 질질 끌 생각 없었거든."] },
  { id: "bacikal-finish-2nd", characterId: "bacikal", event: "finish-2nd", text: ["끝. 1등 놓쳤다고 아쉬워할 생각 없어."] },
  { id: "bacikal-finish-3rd", characterId: "bacikal", event: "finish-3rd", text: ["나왔어. 늦었지만 늦었다고 탓할 생각 없어."] },
  { id: "bacikal-defeat", characterId: "bacikal", event: "defeat", text: ["내 손에 남았네. 내 차례에 쥐었으면 내 거야."] },
  { id: "alger-table-open", characterId: "alger", event: "table-open", text: ["대국 개시. 참가자 넷, 이의 없음. …딴소리하기 없기."] },
  { id: "alger-finish-1st", characterId: "alger", event: "finish-1st", text: ["최단 시간 업무 완료. …이런 걸로 상장 주는 것도 아닌데."] },
  { id: "alger-finish-2nd", characterId: "alger", event: "finish-2nd", text: ["차순위 결재 완료. 무난한 실적. 무난한 게 최고야."] },
  { id: "alger-finish-3rd", characterId: "alger", event: "finish-3rd", text: ["기한 직전 겨우 종결. …등골 오싹했던 건 보고서에서 뺀다."] },
  { id: "alger-defeat", characterId: "alger", event: "defeat", text: ["최종 책임자 확정. …떠넘길 데도 없네."] },
  { id: "nieun-table-open", characterId: "nieun", event: "table-open", text: ["착석 완료. 카드 딜링이 세상 멸망보다 꼬이진 않겠지. …안 꼬여야 되는데."] },
  { id: "nieun-finish-1st", characterId: "nieun", event: "finish-1st", text: ["1등으로 손패 정리. 역시 정보상의 이름값 하네. …물론 이 의자에서 엉덩이 뗄 생각은 없어."] },
  { id: "nieun-finish-2nd", characterId: "nieun", event: "finish-2nd", text: ["나도 끝. 적당히 평타쳤네. 난 계속 여기 앉아 있을 테니까 보던 거나 봐."] },
  { id: "nieun-finish-3rd", characterId: "nieun", event: "finish-3rd", text: ["겨우 털었다. 자리도 못 비우는데 탈출 레이스라니, 내 팔자도 참."] },
  { id: "nieun-defeat", characterId: "nieun", event: "defeat", text: ["씨발."] },
  { id: "lyla-table-open", characterId: "lyla", event: "table-open", text: ["인원 확인 완료했습니다. 전원 관리 대상입니다."] },
  { id: "lyla-finish-1st", characterId: "lyla", event: "finish-1st", text: ["최단 시간에 격리했습니다. 통제가 완벽했다는 증거입니다."] },
  { id: "lyla-finish-2nd", characterId: "lyla", event: "finish-2nd", text: ["제 통제 구역은 수습됐습니다. 잔여 상황을 관찰하겠습니다."] },
  { id: "lyla-finish-3rd", characterId: "lyla", event: "finish-3rd", text: ["수습이 지연됐습니다. 오차 범위는 즉시 수정하겠습니다."] },
  { id: "lyla-defeat", characterId: "lyla", event: "defeat", text: ["제가 격리하겠습니다. 타인에게 이관할 사유가 없습니다."] },
  { id: "riel-table-open", characterId: "riel", event: "table-open", text: ["판 시작이네요. 참가자 네 분, 기록할게요."] },
  { id: "riel-finish-1st", characterId: "riel", event: "finish-1st", text: ["제일 먼저 끝났어요! 이런 것도 기록에 남죠?"] },
  { id: "riel-finish-2nd", characterId: "riel", event: "finish-2nd", text: ["두 번째로 털었네요. 조용히 적어 둘게요."] },
  { id: "riel-finish-3rd", characterId: "riel", event: "finish-3rd", text: ["휴, 살았네요… 손 떨린 건 안 적을래요."] },
  { id: "riel-defeat", characterId: "riel", event: "defeat", text: ["결국 제가 맡게 됐네요. 마지막은 제 이름입니다."] },
  { id: "wares-table-open", characterId: "wares", event: "table-open", text: ["의자 넷, 손 여덟 개. 판이 꽤 시끄럽겠어."] },
  { id: "wares-finish-1st", characterId: "wares", event: "finish-1st", text: ["손이 비니 손금이 잘 보이네. 다 적혔구나."] },
  { id: "wares-finish-2nd", characterId: "wares", event: "finish-2nd", text: ["중간에 꼈네. 나름 묘한 자리야."] },
  { id: "wares-finish-3rd", characterId: "wares", event: "finish-3rd", text: ["턱밑까지 왔었네. 멈췄던 숨을 쉬어 봐."] },
  { id: "wares-defeat", characterId: "wares", event: "defeat", text: ["내 손에서 굳었네. 이 문장은 내 몫인가 봐."] },
  { id: "adesha-table-open", characterId: "adesha", event: "table-open", text: ["착석. 넷. 개시."] },
  { id: "adesha-finish-1st", characterId: "adesha", event: "finish-1st", text: ["최단 시간 완료. 이상 무."] },
  { id: "adesha-finish-2nd", characterId: "adesha", event: "finish-2nd", text: ["차순 완료. 수순 진행."] },
  { id: "adesha-finish-3rd", characterId: "adesha", event: "finish-3rd", text: ["완료… 한계선 직전 탈출."] },
  { id: "adesha-defeat", characterId: "adesha", event: "defeat", text: ["패배 확정. 조커 보유. 내 몫."] },
  { id: "anna-table-open", characterId: "anna", event: "table-open", text: ["다들 앉아! …아니, 앉아 달라고. 명령 아니고 시작하자는 거야."] },
  { id: "anna-finish-1st", characterId: "anna", event: "finish-1st", text: ["내가 이겼어! …자랑하는 거 아니다? 억울해서 그래."] },
  { id: "anna-finish-2nd", characterId: "anna", event: "finish-2nd", text: ["끝났다. 너 잘하더라. …칭찬이야! 왜 그런 눈으로 봐?"] },
  { id: "anna-finish-3rd", characterId: "anna", event: "finish-3rd", text: ["나 나왔어. 위험했다… 너희 걱정한 거야. 나 말고!"] },
  { id: "anna-defeat", characterId: "anna", event: "defeat", text: ["내가 쥐고 끝낼게. 됐지? …이러려고 남은 거야, 나 오해하지 마."] },
  { id: "apollyon-table-open", characterId: "apollyon", event: "table-open", text: ["시작인가. 하아… 앉으라니 앉아주지."] },
  { id: "apollyon-finish-1st", characterId: "apollyon", event: "finish-1st", text: ["끝났군. 1등이라… 하아, 허무하군."] },
  { id: "apollyon-finish-2nd", characterId: "apollyon", event: "finish-2nd", text: ["끝이다. 두 번째면 적당해. …적당한 게 제일이지."] },
  { id: "apollyon-finish-3rd", characterId: "apollyon", event: "finish-3rd", text: ["겨우 끝났군. 하아… 너무 오래 붙잡혔어."] },
  { id: "apollyon-defeat", characterId: "apollyon", event: "defeat", text: ["남았군. …하아, 짐을 떠안는 거야 늘 해오던 일이다."] },
  { id: "bche-table-open", characterId: "bche", event: "table-open", text: ["자, 세팅 끝. 오늘은 좀 풀어주려나. 그럴 리가 없겠지만."] },
  { id: "bche-finish-1st", characterId: "bche", event: "finish-1st", text: ["어? 내가 1위? …야, 이거 진짜 승리 상금 없냐?"] },
  { id: "bche-finish-2nd", characterId: "bche", event: "finish-2nd", text: ["2등인가. 어중간하네. 어중간한 게 내 주머니 사정이지."] },
  { id: "bche-finish-3rd", characterId: "bche", event: "finish-3rd", text: ["살았다, 진짜 살아남았어! 이번 라운드는 넘어갔네."] },
  { id: "bche-defeat", characterId: "bche", event: "defeat", text: ["아 씨… 한탕은 무슨, 나 진짜 망했네."] },
  { id: "camille-table-open", characterId: "camille", event: "table-open", text: ["넷이나 모였네요오… 길게 놀아 봐요오."] },
  { id: "camille-finish-1st", characterId: "camille", event: "finish-1st", text: ["어라, 벌써 끝났나요오? 시시하게… 더 놀고 싶은데에."] },
  { id: "camille-finish-2nd", characterId: "camille", event: "finish-2nd", text: ["2등이네요오. 관전하기엔 딱 좋은 자리지요오."] },
  { id: "camille-finish-3rd", characterId: "camille", event: "finish-3rd", text: ["아, 탈출했네요오… 더 쫄깃할 수 있었는데에."] },
  { id: "camille-defeat", characterId: "camille", event: "defeat", text: ["나한테 남았구나아. …좋아, 이건 내가 들고 있지요."] },
  { id: "cicero-table-open", characterId: "cicero", event: "table-open", text: ["1급 기술자가 개입한 공정이다. 출력 수준을 기대해도 좋다."] },
  { id: "cicero-finish-1st", characterId: "cicero", event: "finish-1st", text: ["압도적인 공정 완결이다. 1급의 출력 차이를 알겠나?"] },
  { id: "cicero-finish-2nd", characterId: "cicero", event: "finish-2nd", text: ["2등으로 컷오프다. …등급 기준으로는 충분히 합격권이지."] },
  { id: "cicero-finish-3rd", characterId: "cicero", event: "finish-3rd", text: ["허용 오차 내로 통과다. 규격 심사였다면 턱걸이였겠지만."] },
  { id: "cicero-defeat", characterId: "cicero", event: "defeat", text: ["…카드 메커니즘의 결함이다! 1급인 나의 설계 오류가 아니다!"] },
  { id: "cradle-table-open", characterId: "cradle", event: "table-open", text: ["닻을 올려라! 겁먹지 마라, 신참. 이 선장이 같이 탄다!"] },
  { id: "cradle-finish-1st", characterId: "cradle", event: "finish-1st", text: ["이 몸이 1등으로 입항이다! …어라, 선장이 제일 먼저 내리면 좀 그런가?"] },
  { id: "cradle-finish-2nd", characterId: "cradle", event: "finish-2nd", text: ["두 번째로 상륙했다! 거품 빼고 보면 나쁘지 않은 조타였어."] },
  { id: "cradle-finish-3rd", characterId: "cradle", event: "finish-3rd", text: ["늦게 상륙했군. 선장은 원래 마지막에 내리는 거다. …마지막은 아니었지만."] },
  { id: "cradle-defeat", characterId: "cradle", event: "defeat", text: ["폭풍을 못 피했군. …이 짐은 선장이 진다, 신참은 비켜라!"] },
  { id: "deokbae-table-open", characterId: "deokbae", event: "table-open", text: ["…판을 깔지. 오래 걸릴 일은 아니니까."] },
  { id: "deokbae-finish-1st", characterId: "deokbae", event: "finish-1st", text: ["내가 먼저 터는군. 늙은이가 걸음만 빨라 봐야."] },
  { id: "deokbae-finish-2nd", characterId: "deokbae", event: "finish-2nd", text: ["끝났다. 두 번째면 족하지, 늙은이한테 뭘 바라겠나."] },
  { id: "deokbae-finish-3rd", characterId: "deokbae", event: "finish-3rd", text: ["겨우 벗어났군. 백 년을 구르고도 이런 판은 통 안 늘어."] },
  { id: "deokbae-defeat", characterId: "deokbae", event: "defeat", text: ["…이건 내가 안지. 젊은것들 손에 둘 물건이 아니다."] },
  { id: "diamo-table-open", characterId: "diamo", event: "table-open", text: ["넷이서 둥글게 모였네. …전에도 이런 밤이 있었던가."] },
  { id: "diamo-finish-1st", characterId: "diamo", event: "finish-1st", text: ["제일 먼저 털었어… 나 대신 가슴 벅차게 기뻐하는 누군가가 느껴져."] },
  { id: "diamo-finish-2nd", characterId: "diamo", event: "finish-2nd", text: ["두 번째로 빠졌네. …중간쯤에 묻히는 기분, 낯설지 않아."] },
  { id: "diamo-finish-3rd", characterId: "diamo", event: "finish-3rd", text: ["턱끝까지 찼다가 벗어났네… 조용히 숨 쉬는 느낌이 나."] },
  { id: "diamo-defeat", characterId: "diamo", event: "defeat", text: ["끝내 내 손에 남았네. 아무도 돌보지 않는 슬픔은 늘 나한테 모여."] },
  { id: "echo-table-open", characterId: "echo", event: "table-open", text: ["에코 앉았어! 긴장 안 했어… 사실 조금 했어."] },
  { id: "echo-finish-1st", characterId: "echo", event: "finish-1st", text: ["에코 1등이야! 너무 기뻐서 춤추고 싶어!"] },
  { id: "echo-finish-2nd", characterId: "echo", event: "finish-2nd", text: ["에코 2등이야. 사실 조금 아쉬워하고 있어."] },
  { id: "echo-finish-3rd", characterId: "echo", event: "finish-3rd", text: ["에코 겨우 살았어! 심장이 쾅쾅 뛰고 있어!"] },
  { id: "echo-defeat", characterId: "echo", event: "defeat", text: ["에코가 졌어. 슬프다고 에코는 말하는 중이야."] },
  { id: "esther-table-open", characterId: "esther", event: "table-open", text: ["네 분 모두 모이셨네요. 오늘은 어떤 분의 아픔이 먼저 가라앉을까요."] },
  { id: "esther-finish-1st", characterId: "esther", event: "finish-1st", text: ["제가 제일 먼저 쉬게 됐어요. 아쉬워 마세요, 다 순서가 있는 거랍니다."] },
  { id: "esther-finish-2nd", characterId: "esther", event: "finish-2nd", text: ["두 번째로 인사를 드릴게요. 남은 분들도 금방 편안해지실 거예요."] },
  { id: "esther-finish-3rd", characterId: "esther", event: "finish-3rd", text: ["아, 결국 저도 빠져나왔네요. …마지막까지 품어 드리지 못해 아쉬워요."] },
  { id: "esther-defeat", characterId: "esther", event: "defeat", text: ["결국 제 품에 남았네요. 이 가시 돋친 짐은 제가 안고 잠들게요."] },
  { id: "hiro-table-open", characterId: "hiro", event: "table-open", text: ["드디어 판이 열렸습니다! 오늘 밤도 정당하고 화려하게 싸워봅시다!"] },
  { id: "hiro-finish-1st", characterId: "hiro", event: "finish-1st", text: ["1등으로 손을 털었습니다! 정의는 언제나 승리하는 법이지요!", "…이런 쓸데없는 게임만 무패네."] },
  { id: "hiro-finish-2nd", characterId: "hiro", event: "finish-2nd", text: ["2등으로 마무리합니다! 주인공이 꼭 매번 1등일 필요는 없습니다!"] },
  { id: "hiro-finish-3rd", characterId: "hiro", event: "finish-3rd", text: ["하하, 정말 아슬아슬하게 살았습니다!", "…속 타는데 표정 관리하느라 죽는 줄 알았네."] },
  { id: "hiro-defeat", characterId: "hiro", event: "defeat", text: ["패배의 짐은 제가 짊어지겠습니다! 악역을 떠안는 것도 영웅입니다!", "…어째 시나리오가 항상 이 따위냐."] },
  { id: "katrinka-table-open", characterId: "katrinka", event: "table-open", text: ["착석료는 따로 안 받을게. 대신 판판이 벌어지는 손실은 본인 부담이야."] },
  { id: "katrinka-finish-1st", characterId: "katrinka", event: "finish-1st", text: ["최단 시간으로 손 털었어. 이 정도 속도면 프리미엄 할증감이네."] },
  { id: "katrinka-finish-2nd", characterId: "katrinka", event: "finish-2nd", text: ["2등 청산 완료. 기본 요율 그대로 적용해서 마감할게."] },
  { id: "katrinka-finish-3rd", characterId: "katrinka", event: "finish-3rd", text: ["겨우 마감 직전에 털어냈네. 하마터면 손실금 안을 뻔했어."] },
  { id: "katrinka-defeat", characterId: "katrinka", event: "defeat", text: ["폭탄을 결국 내가 안았네. …이 청구서는 대체 누구 앞으로 돌려야 돼?"] },
  { id: "kreva-table-open", characterId: "kreva", event: "table-open", text: ["테이블 4인 접속 확인. 도둑잡기 시퀀스 개시."] },
  { id: "kreva-finish-1st", characterId: "kreva", event: "finish-1st", text: ["목표 달성. 최단 처리 연산 시간 기록."] },
  { id: "kreva-finish-2nd", characterId: "kreva", event: "finish-2nd", text: ["2순위 탈출 완료. 시스템 손실률 0%."] },
  { id: "kreva-finish-3rd", characterId: "kreva", event: "finish-3rd", text: ["3순위 턱걸이 이탈. 예비 전력 임계치 아슬아슬하게 유지."] },
  { id: "kreva-defeat", characterId: "kreva", event: "defeat", text: ["연산 오류 발생. 노이즈 개체 제어 실패로 시스템 셧다운."] },
  { id: "levillotte-table-open", characterId: "levillotte", event: "table-open", text: ["다들 나 구경하러 앉은 거지? 이 최강 미소녀한테 덤벼볼 테면 덤벼봐!"] },
  { id: "levillotte-finish-1st", characterId: "levillotte", event: "finish-1st", text: ["압도적 1등! 초강력 미소녀의 대승리라고! 싸인받을 사람 줄 서!"] },
  { id: "levillotte-finish-2nd", characterId: "levillotte", event: "finish-2nd", text: ["2등으로 가볍게 골인! …어라, 양보해 준 티가 좀 났나? 얼른 안 칭찬해?"] },
  { id: "levillotte-finish-3rd", characterId: "levillotte", event: "finish-3rd", text: ["아슬아슬하게 이탈 성공! …휴, 심장 터지는 줄 알았네! 겉으로는 멀쩡해 보였지?"] },
  { id: "levillotte-defeat", characterId: "levillotte", event: "defeat", text: ["뭐야, 씨발… 내가 조커라고?!", "…아, 아니! 억울해서 소리 친 거 아니거든! 미소녀 운이 잠깐 졸아서 그런 거거든!"] },
  { id: "lilim-table-open", characterId: "lilim", event: "table-open", text: ["여기에… 앉으면 돼요? 왜 다들 저 봐요?"] },
  { id: "lilim-finish-1st", characterId: "lilim", event: "finish-1st", text: ["제일 먼저… 다 버렸어요! 저 상 주는 거예요?"] },
  { id: "lilim-finish-2nd", characterId: "lilim", event: "finish-2nd", text: ["두 번째로… 끝났어요. 이것도 괜찮은 거죠?"] },
  { id: "lilim-finish-3rd", characterId: "lilim", event: "finish-3rd", text: ["아… 살았다! 저 이제 안 진 거죠?"] },
  { id: "lilim-defeat", characterId: "lilim", event: "defeat", text: ["제가… 진 거예요? 아무도 안 가르쳐 줬는데…"] },
  { id: "machina-table-open", characterId: "machina", event: "table-open", text: ["다들 세팅 끝났지? 가볍게 돌려보자고."] },
  { id: "machina-finish-1st", characterId: "machina", event: "finish-1st", text: ["1등으로 마감했어! 사전 정비를 잘해 둔 덕분이지."] },
  { id: "machina-finish-2nd", characterId: "machina", event: "finish-2nd", text: ["두 번째 마감. 이 정도 속도가 부담 없고 딱 좋아."] },
  { id: "machina-finish-3rd", characterId: "machina", event: "finish-3rd", text: ["휴, 턱걸이했네. 안 부서지고 남았으면 됐지 뭐."] },
  { id: "machina-defeat", characterId: "machina", event: "defeat", text: ["불량품은 내가 안고 갈게. 나는 튼튼하니까 괜찮아."] },
  { id: "morsisa-table-open", characterId: "morsisa", event: "table-open", text: ["저… 저도 껴도 될까요? 방해 안 되게 할게요…"] },
  { id: "morsisa-finish-1st", characterId: "morsisa", event: "finish-1st", text: ["어? 저, 제가 1등이에요…? 그럴 리가 없는데…"] },
  { id: "morsisa-finish-2nd", characterId: "morsisa", event: "finish-2nd", text: ["두 번째… 저치고는 잘한 것 같은데, 아닌가요…"] },
  { id: "morsisa-finish-3rd", characterId: "morsisa", event: "finish-3rd", text: ["나, 나왔다… 살아남았어요…"] },
  { id: "morsisa-defeat", characterId: "morsisa", event: "defeat", text: ["역시… 제 몫이었네요. 정말 죄송해요…"] },
  { id: "nostalgia-table-open", characterId: "nostalgia", event: "table-open", text: ["어서 오세요. 오늘도 모두의 영혼이 안전하게 보호받기를."] },
  { id: "nostalgia-finish-1st", characterId: "nostalgia", event: "finish-1st", text: ["제가 가장 먼저 구원받았네요. 남은 분들도 반드시 인도받을 거예요."] },
  { id: "nostalgia-finish-2nd", characterId: "nostalgia", event: "finish-2nd", text: ["무사히 내려놓았어요. 순서는 상관없어요, 모두 소중한 분들이지요."] },
  { id: "nostalgia-finish-3rd", characterId: "nostalgia", event: "finish-3rd", text: ["겨우 빠져나왔군요. …감사드려요. 신께, 진심으로요."] },
  { id: "nostalgia-defeat", characterId: "nostalgia", event: "defeat", text: ["이 고통은 제가 품겠어요. 아무리 버려진 아이라도… 사랑받아야 한다."] },
  { id: "phaeo-table-open", characterId: "phaeo", event: "table-open", text: ["참가자 4인 확인. 통계적으로 3인은 안도 범위 내."] },
  { id: "phaeo-finish-1st", characterId: "phaeo", event: "finish-1st", text: ["최단 시간 탈출 완료. 극히 드문 변수이자 예외."] },
  { id: "phaeo-finish-2nd", characterId: "phaeo", event: "finish-2nd", text: ["2위로 종료. 예상 수치 범위 내 정상 결과."] },
  { id: "phaeo-finish-3rd", characterId: "phaeo", event: "finish-3rd", text: ["최하위 직전 안전권 진입. …체온 저하 멈춤 확인."] },
  { id: "phaeo-defeat", characterId: "phaeo", event: "defeat", text: ["최종 잔류 확정. 누군가는 비극을 맡을 예정. …본인으로 처리."] },
  { id: "raven-table-open", characterId: "raven", event: "table-open", text: ["좋은 판이 되길 바랍니다. 정산은 제가 맡겠습니다."] },
  { id: "raven-finish-1st", characterId: "raven", event: "finish-1st", text: ["가장 먼저 청산했습니다. 좋은 거래였습니다."] },
  { id: "raven-finish-2nd", characterId: "raven", event: "finish-2nd", text: ["차순위로 마무리했습니다. 손해는 아닌 자리입니다."] },
  { id: "raven-finish-3rd", characterId: "raven", event: "finish-3rd", text: ["아슬아슬하게 흑자 전환입니다. 다행입니다."] },
  { id: "raven-defeat", characterId: "raven", event: "defeat", text: ["제 쪽 손실로 처리하겠습니다. 단가는 기억하겠습니다."] },
  { id: "temute-table-open", characterId: "temute", event: "table-open", text: ["자, 시작하자. 다들 다치지 말고… 내가 또 잔소리하네."] },
  { id: "temute-finish-1st", characterId: "temute", event: "finish-1st", text: ["하아, 내가 1등이네. 어른이 애들 사이에 끼어서 참 잘하는 짓이다."] },
  { id: "temute-finish-2nd", characterId: "temute", event: "finish-2nd", text: ["2등으로 털었네. 안 튀고 적당히 빠지는 게 오래 사는 길이야."] },
  { id: "temute-finish-3rd", characterId: "temute", event: "finish-3rd", text: ["겨우 빠져나왔네. …야, 너 괜찮냐? 패 똑바로 쥐고 있어."] },
  { id: "temute-defeat", characterId: "temute", event: "defeat", text: ["하아… 줘 봐, 내가 들고 있을게. 액땜은 어른이 해야지."] },
  { id: "traver-table-open", characterId: "traver", event: "table-open", text: ["적당히 하자고. 욕심내서 선 넘으면 사단 나."] },
  { id: "traver-finish-1st", characterId: "traver", event: "finish-1st", text: ["1등으로 막차 탔네. …나 같은 놈도 되긴 되는구나."] },
  { id: "traver-finish-2nd", characterId: "traver", event: "finish-2nd", text: ["2등 도착. 딱 내 분수에 맞는 승강장이야. 만족해."] },
  { id: "traver-finish-3rd", characterId: "traver", event: "finish-3rd", text: ["겨우 빠져나왔네. 종착역 직전에 내리면 그걸로 충분해."] },
  { id: "traver-defeat", characterId: "traver", event: "defeat", text: ["역시나. …분수껏 지켰는데 왜 하필 나한테 꽂혀."] },
  { id: "ttaengchil-table-open", characterId: "ttaengchil", event: "table-open", text: ["다 모였다! 판 벌이자! 좋다! 좋아!"] },
  { id: "ttaengchil-finish-1st", characterId: "ttaengchil", event: "finish-1st", text: ["1등이다! 멍멍! 아, 미안! 털었다!"] },
  { id: "ttaengchil-finish-2nd", characterId: "ttaengchil", event: "finish-2nd", text: ["2등이다! 이것도 엄청 좋은 거지!"] },
  { id: "ttaengchil-finish-3rd", characterId: "ttaengchil", event: "finish-3rd", text: ["살았다! 무서웠어! 진짜 쫄았다!"] },
  { id: "ttaengchil-defeat", characterId: "ttaengchil", event: "defeat", text: ["아… 나다. 내 손에 남았어. 괜찮아. 내가 하면 돼."] },
  { id: "tumit-tu-table-open", characterId: "tumit-tu", event: "table-open", text: ["자, 드디어 개전이에요! E랭크 헌터의 저력을 보여 드릴게요!"] },
  { id: "tumit-tu-finish-1st", characterId: "tumit-tu", event: "finish-1st", text: ["1등 도착!! 봤죠?! 봤죠?! 이게 바로 E랭크의 힘이에요!"] },
  { id: "tumit-tu-finish-2nd", characterId: "tumit-tu", event: "finish-2nd", text: ["2등으로 골인이에요! E랭크 치고는 공적 대단한 거 아닙니까?!"] },
  { id: "tumit-tu-finish-3rd", characterId: "tumit-tu", event: "finish-3rd", text: ["아우, 살았다! E랭크는 원래 생존력 하나로 버티는 거거든요!"] },
  { id: "tumit-tu-defeat", characterId: "tumit-tu", event: "defeat", text: ["말도 안 돼… 이거 완전 S랭크 난이도잖아요! 제 등급 오버거든요!"] },
  { id: "yul-table-open", characterId: "yul", event: "table-open", text: ["어, 시작이에요? 저 뭐 하러 앉았더라… 아, 카드게임!"] },
  { id: "yul-finish-1st", characterId: "yul", event: "finish-1st", text: ["끝났어요? 제가요? 언제 다 버렸지… 아무튼 이겼네요!"] },
  { id: "yul-finish-2nd", characterId: "yul", event: "finish-2nd", text: ["두 번째네요. …어라, 뭐가 두 번째였죠? 아, 저요?"] },
  { id: "yul-finish-3rd", characterId: "yul", event: "finish-3rd", text: ["빠져나왔다… 나왔죠? 맞다고 해 주세요."] },
  { id: "yul-defeat", characterId: "yul", event: "defeat", text: ["내 손에 이게 왜 있지… 아, 아까 그거구나. …근데 언제 들어왔더라?"] },
] as const satisfies readonly OldMaidLine[];
