import type { OldMaidLine, OldMaidLineEvent } from "./contracts.ts";

type LegacyLineEvent = Exclude<OldMaidLineEvent, "table-open" | "finish-1st" | "finish-2nd" | "finish-3rd" | "defeat">;
type LineText = Readonly<Record<LegacyLineEvent, readonly string[]>>;

const text = {
  pale: {
    watching: ["넷이 차례를 기다리네. 항구에서 배를 기다리는 거랑 비슷해. 배 대신 카드가 오지만."],
    "idle-draw": ["한 장 늘었네. 바다에서 생선 한 마리 더 건진 셈이야. 얘도 짝은 있겠지."],
    "pair-discard": ["둘이 다시 만났어. 서로 모르는 물고기도 같은 그물에 들면 한 쌍 같아 보여."],
    "taken-from": ["가져가도 돼. 파도가 배를 옮겨도 항해한 사실은 안 없어지잖아."],
    "pair-made": ["찾았어. 양파 속에서 진주가 나온 것처럼 뜻밖이네. 양파는 싫지만."],
    "joker-drawn": ["짝이 없는 건 죄가 아니야. 바다에 혼자 뜬 섬도 이름을 얻으면 장소가 되니까."],
    "joker-left": ["혼자 보내는 기분이네. 철새를 놓아주는 어부 같아. …어부는 철새를 안 잡나?"],
    emptied: ["다 짝지어 줬어. 빈손은 빈 배랑 비슷하네. 이제 어디로든 갈 수 있으니까."],
  },
  kano: {
    watching: ["괜찮습니다. 아직 누구도 위험하지 않아요."],
    "idle-draw": ["받았습니다. 이 정도는 감당할 수 있어요."],
    "pair-discard": ["차갑게 정리하는 편이 서로에게 낫습니다."],
    "taken-from": ["고르셨군요. 부르셨다면 응답하겠습니다."],
    "pair-made": ["예상했습니다. …예상했다고 해 두죠."],
    "joker-drawn": ["괜찮아요. 저는 이런 걸 오래 들고 있어 봤습니다."],
    "joker-left": ["미안합니다. 이건 제가 녹일 수 없었어요."],
    emptied: ["먼저 나가겠습니다. 혼자 남는 건 익숙하니까요."],
  },
  nemo: {
    watching: ["다들 진지하네. 멋진 어른은 이럴 때 여유 있게 웃는 거야. …어떻게 웃더라."],
    "idle-draw": ["한 장 받았어. 괜찮아, 이 정도로 도망치진 않을 거야."],
    "pair-discard": ["짝을 찾았어. 영웅은 정리도 잘한다… 이건 좀 멋없나."],
    "taken-from": ["가져가. 아깝긴 한데, 사람을 돕는 건 나누는 데서 시작하니까."],
    "pair-made": ["됐다! 봐, 나도 해내잖아. …아니, 원래 할 수 있었어."],
    "joker-drawn": ["무섭네.", "그래도 이번에는 도망치지 않을 거야."],
    "joker-left": ["넘어갔어. 미안하지만, 끝까지 같이 해결할게."],
    emptied: ["내 손은 비었어. 이제 남은 사람도 데리고 집에 가자."],
  },
  bacikal: {
    watching: ["다들 고민이 많네. 나는 이미 골랐어서."],
    "idle-draw": ["이거면 됐어. 더 좋은 게 있었대도 이제 모르지."],
    "pair-discard": ["맞으면 버린다. 그게 규칙이잖아."],
    "taken-from": ["가져가. 두고 후회할 바엔."],
    "pair-made": ["맞췄네. 이런 건 운이야. 실력이라고 하면 거짓말이고."],
    "joker-drawn": ["받았어. 누구 탓도 아니야."],
    "joker-left": ["넘겼어. 뒤는 안 볼게."],
    emptied: ["끝. 되돌릴 생각은 안 했어."],
  },
  alger: {
    watching: ["진행 상황 정상. 특이사항 없음. …없다고 적어 두지."],
    "idle-draw": ["수령 확인. 내용물에 대한 이의는 접수하지 않는다."],
    "pair-discard": ["정리 완료. 이 건은 종결 처리한다."],
    "taken-from": ["반출 승인. 사후 책임은 반출자에게 있다."],
    "pair-made": ["예상 범위 안이야. …운이 좋았다곤 안 적을게."],
    "joker-drawn": ["…규정을 다시 읽어 봐야겠군."],
    "joker-left": ["인수인계 완료. 이후 발생하는 사안은 담당자 책임이다."],
    emptied: ["내 몫은 여기까지. …여기까지가 내 몫이 맞나?"],
  },
  nieun: {
    watching: ["경우의 수는 다 셌어. 이 정도면 천재 정보상이지. …모르는 게 하나 남았지만."],
    "idle-draw": ["변수 하나 추가. 축하해, 내 인생이 또 복잡해졌네."],
    "pair-discard": ["둘 정리. 세상 끝도 이렇게 클릭 한 번이면 좋겠다."],
    "taken-from": ["가져가. 어차피 내 손에 오래 남는 건 별로 없거든."],
    "pair-made": ["맞았네. 내 계산이 완벽했어. …그냥 운이었지만."],
    "joker-drawn": ["이런 건 왜 꼭 나한테 오냐. 뭐, 익숙한 사람이 드는 게 낫지."],
    "joker-left": ["넘겼어. 악감정은 없어. …미안하단 말이야."],
    emptied: ["손은 비었네. 이제 일어나면 되는데… 아, 그게 안 되지. 팔자 좋다."],
  },
  lyla: {
    watching: ["진행은 통제 범위 내입니다."],
    "idle-draw": ["예상된 손실입니다. 문제없습니다."],
    "pair-discard": ["위험 요소 둘을 제거했습니다."],
    "taken-from": ["가져가십시오. 이미 계산에 포함했습니다."],
    "pair-made": ["관리가 정상적으로 작동하고 있습니다."],
    "joker-drawn": ["제가 맡는 편이 안전합니다."],
    "joker-left": ["적절한 위치로 이동했습니다. 제 판단입니다."],
    emptied: ["제 관리 구역은 정리됐습니다. 나머지는 각자 처리하면 됩니다."],
  },
  riel: {
    watching: ["…기록해 둘게요. 별일 없었다고."],
    "idle-draw": ["한 장 수령. 적어 뒀어요."],
    "pair-discard": ["정리된 건 목록에서 지울게요."],
    "taken-from": ["가져가세요. 대장에는 남겨 둘게요."],
    "pair-made": ["어, 맞았네요. 이런 것도 적나요?"],
    "joker-drawn": ["이건… 분류가 애매하네요."],
    "joker-left": ["넘어갔어요. 담당이 바뀐 걸로 할게요."],
    emptied: ["제 몫은 끝났어요. 기록은 계속 남겠지만요."],
  },
  wares: {
    watching: ["다들 자기 차례를 기다리네. 손가락이 움직이고 눈은 카드에 있고, 기다림은 기록에 잘 안 남아."],
    "idle-draw": ["한 장 왔어. 종이는 얇고 그림은 납작하고, 지금 이 순간은 별로 중요하지 않아서 오래 남겠네."],
    "pair-discard": ["한 쌍이 끝났어. 둘이 없어지니까 가운데가 조금 넓어졌네. 넓은 곳은 춤추기 좋아."],
    "taken-from": ["가져가. 원래 내 것도 아니었고, 네 것이 될지는 조금 뒤에 알게 되겠지."],
    "pair-made": ["맞는 짝이 있었네. 드문 일이야. 비슷한 눈 둘이 서로를 보고 있는 것 같아."],
    "joker-drawn": ["아. 아직 끝나지 않은 문장이구나. 모자가 예쁘고 끝에는 마침표가 없네."],
    "joker-left": ["잘 가. 어디로 도착할지는 내가 안 정할게. 방금 오른쪽으로 갔다는 건 봤지만."],
    emptied: ["나는 여기서 끝났어. 손은 비었고 의자는 남았고, 다른 사람들 결말은 아직 움직이고 있네."],
  },
} as const satisfies Readonly<Record<string, LineText>>;

export const temerosaOldMaidLines: readonly OldMaidLine[] = Object.entries(text).flatMap(([characterId, events]) =>
  Object.entries(events).map(([event, beats]) => ({
    id: `${characterId}-${event}`,
    characterId,
    event: event as OldMaidLineEvent,
    text: beats,
  })),
);
