import type { OldMaidLine, OldMaidLineEvent } from "./contracts.ts";

type LegacyLineEvent = Exclude<OldMaidLineEvent, "table-open" | "finish-1st" | "finish-2nd" | "finish-3rd" | "defeat">;
type LineText = Readonly<Record<LegacyLineEvent, readonly string[]>>;

const text = {
  pale: {
    watching: ["이렇게 둘러앉아 있는 것만으로도 뭔가가 생겨. 이름은 아직 없지만."],
    "idle-draw": ["한 장 늘었네. 얘도 어딘가에 짝이 있을 거야."],
    "pair-discard": ["둘이 다시 만났어. 이름을 붙여 줄까?"],
    "taken-from": ["가져가도 돼. 내 손에 있었다는 건 안 없어지니까."],
    "pair-made": ["봐, 찾았어. 찾으면 이렇게 되는 거야."],
    "joker-drawn": ["짝이 없는 건 죄가 아니야."],
    "joker-left": ["혼자 두는 것 같아서 좀 그렇네. …잘 지내."],
    emptied: ["나는 다 짝지어 줬어. 그러니까 이제 사라져도 돼. …농담이야."],
  },
  kano: {
    watching: ["괜찮아. 아직 아무도 위험하지 않아."],
    "idle-draw": ["받았어. 이 정도는 감당할 수 있어."],
    "pair-discard": ["차갑게 정리하는 편이 서로에게 나아."],
    "taken-from": ["골랐구나. 그럼 응답할게."],
    "pair-made": ["예상했어. …예상했다고 해 두자."],
    "joker-drawn": ["괜찮아. 나는 이런 걸 오래 들고 있어 봤어."],
    "joker-left": ["미안. 이건 내가 못 녹여."],
    emptied: ["먼저 나갈게. 혼자 남는 건 익숙해서."],
  },
  nemo: {
    watching: ["지금까지 나온 카드, 전부 세어 놨어. 순서도."],
    "idle-draw": ["이건 아니야. …괜찮아, 아직 되돌릴 만한 일도 아니고."],
    "pair-discard": ["이건 고칠 수 있는 실수였어. 드물게도."],
    "taken-from": ["그거 가져가면 계산이 하나 어긋나는데. …가져가."],
    "pair-made": ["봐. 맞출 수 있잖아. 처음부터 그랬어야지."],
    "joker-drawn": ["…한 번만. 딱 한 번만 되돌리면 되는데.", "…안 해."],
    "joker-left": ["넘겼어. …이건 미안해하지 않기로 했어."],
    emptied: ["다 끝났네. 이번엔 아무것도 안 되돌렸어."],
  },
  bacikal: {
    watching: ["다들 고민이 많네. 나는 이미 골랐어서."],
    "idle-draw": ["이거면 됐어. 더 좋은 게 있었대도 이제 모르지."],
    "pair-discard": ["맞으면 버린다. 그게 규칙이잖아."],
    "taken-from": ["가져가. 두고 후회할 바엔."],
    "pair-made": ["맞췄네. 이런 건 운이야. 실력이라고 하면 거짓말이고."],
    "joker-drawn": ["받았어. 누구 탓도 아니야."],
    "joker-left": ["넘겼어. 뒤는 안 볼게."],
    emptied: ["끝. 되돌릴 생각은 안 했어."],
  },
  alger: {
    watching: ["진행 상황 정상. 특이사항 없음. …없다고 적어 두지."],
    "idle-draw": ["수령 확인. 내용물에 대한 이의는 접수하지 않는다."],
    "pair-discard": ["정리 완료. 이 건은 종결 처리한다."],
    "taken-from": ["반출 승인. 사후 책임은 반출자에게 있다."],
    "pair-made": ["예상 범위 안이야. …운이 좋았다곤 안 적을게."],
    "joker-drawn": ["…규정을 다시 읽어 봐야겠군."],
    "joker-left": ["인수인계 완료. 이후 발생하는 사안은 담당자 책임이다."],
    emptied: ["내 몫은 여기까지. …여기까지가 내 몫이 맞나?"],
  },
  nieun: {
    watching: ["이 판의 남은 경우의 수는 전부 계산했어. 그래도 하나는 모르겠네."],
    "idle-draw": ["변수 하나 추가. 예측 범위 안이야."],
    "pair-discard": ["정리했어. 줄어드는 건 좋은 거야."],
    "taken-from": ["가져가. 어차피 내가 통제할 수 있는 건 여기까지야."],
    "pair-made": ["맞았네. 이런 건 계산이 아니라 그냥 운이지."],
    "joker-drawn": ["내가 들고 있는 게 낫겠어. 익숙하니까."],
    "joker-left": ["미안. 이건 넘길 수밖에 없었어."],
    emptied: ["손은 비었는데, 이상하게 못 일어나겠네."],
  },
  lyla: {
    watching: ["통제 가능한 범위 안이야."],
    "idle-draw": ["예상 손실. 문제없어."],
    "pair-discard": ["둘은 위험하지만, 없어지면 안전하지."],
    "taken-from": ["가져가. 그것도 계산에 넣어 뒀어."],
    "pair-made": ["관리가 되고 있다는 뜻이야."],
    "joker-drawn": ["이건 내가 맡는 게 안전해. 다른 사람은 못 다뤄."],
    "joker-left": ["적절한 곳으로 갔어. 내가 판단했어."],
    emptied: ["내 관리 구역은 정리됐어. 나머지는… 각자 알아서 하겠지."],
  },
  riel: {
    watching: ["…기록해 둘게요. 별일 없었다고."],
    "idle-draw": ["한 장 수령. 적어 뒀어요."],
    "pair-discard": ["정리된 건 목록에서 지울게요."],
    "taken-from": ["가져가세요. 대장에는 남겨 둘게요."],
    "pair-made": ["어, 맞았네요. 이런 것도 적나요?"],
    "joker-drawn": ["이건… 분류가 애매하네요."],
    "joker-left": ["넘어갔어요. 담당이 바뀐 걸로 할게요."],
    emptied: ["제 몫은 끝났어요. 기록은 계속 남겠지만요."],
  },
  wares: {
    watching: ["다들 자기 차례를 기다리네. 기다림은 잘 기록되지 않는데."],
    "idle-draw": ["지금 이 순간도 어딘가엔 남아. 별로 중요하지 않아서, 오히려 더 오래."],
    "pair-discard": ["한 쌍이 끝났어. 이건 되돌리지 않을게."],
    "taken-from": ["가져가. 원래 내 것도 아니었어."],
    "pair-made": ["맞는 짝이 있었네. 드문 일이야."],
    "joker-drawn": ["아. 이건 아직 끝나지 않은 문장이구나."],
    "joker-left": ["잘 가. 네가 도착할 곳은 내가 안 정할게."],
    emptied: ["나는 여기서 끝났어. 남은 사람들의 결말은 남은 사람들 거야."],
  },
} as const satisfies Readonly<Record<string, LineText>>;

export const temerosaOldMaidLines: readonly OldMaidLine[] = Object.entries(text).flatMap(([characterId, events]) =>
  Object.entries(events).map(([event, beats]) => ({
    id: `${characterId}-${event}`,
    characterId,
    event: event as OldMaidLineEvent,
    text: beats,
  })),
);
