import type { OldMaidLine } from "./contracts.ts";

/** CHARX-reviewed dialogue for the 26 audited Bestiaization-era casino NPCs. */
export const temerosaCasinoOldMaidLines = [
  { id: "echo-watching", characterId: "echo", event: "watching", text: ["에코는 기다리고 있어. 기다리는 게 지루하다고 에코는 생각해. 방금 그 생각도 말해 버렸어."] },
  { id: "echo-idle-draw", characterId: "echo", event: "idle-draw", text: ["에코가 한 장 가져왔어. 별로였다고 에코는 느꼈어."] },
  { id: "echo-pair-discard", characterId: "echo", event: "pair-discard", text: ["두 장이 맞았어. 에코는 기쁘다고 말하고 있어."] },
  { id: "echo-taken-from", characterId: "echo", event: "taken-from", text: ["누가 에코 손에서 가져갔어. 에코는 막을 생각을 안 했어."] },
  { id: "echo-pair-made", characterId: "echo", event: "pair-made", text: ["맞췄어. 에코는 이걸 운이라고 생각해."] },
  { id: "echo-joker-drawn", characterId: "echo", event: "joker-drawn", text: ["조커야. 에코는 지금 당황했다고 말해야 해."] },
  { id: "echo-joker-left", characterId: "echo", event: "joker-left", text: ["갔어. 에코는 안심했어. 숨길 수가 없어서 미안해."] },
  { id: "echo-emptied", characterId: "echo", event: "emptied", text: ["에코는 끝났어. 에코가 무슨 생각을 했는지 다들 알았을 거야. 늘 그래."] },
  { id: "adesha-watching", characterId: "adesha", event: "watching", text: ["대기."] },
  { id: "adesha-idle-draw", characterId: "adesha", event: "idle-draw", text: ["한 장. 무의미."] },
  { id: "adesha-pair-discard", characterId: "adesha", event: "pair-discard", text: ["정리."] },
  { id: "adesha-taken-from", characterId: "adesha", event: "taken-from", text: ["가져갔음. 문제없음."] },
  { id: "adesha-pair-made", characterId: "adesha", event: "pair-made", text: ["일치."] },
  { id: "adesha-joker-drawn", characterId: "adesha", event: "joker-drawn", text: ["…이물질."] },
  { id: "adesha-joker-left", characterId: "adesha", event: "joker-left", text: ["이관 완료."] },
  { id: "adesha-emptied", characterId: "adesha", event: "emptied", text: ["임무 종료. …다음 지시."] },
  { id: "ttaengchil-watching", characterId: "ttaengchil", event: "watching", text: ["다들 조용하네. 나 여기 있어."] },
  { id: "ttaengchil-idle-draw", characterId: "ttaengchil", event: "idle-draw", text: ["가져왔다! 어, 이거 아니네."] },
  { id: "ttaengchil-pair-discard", characterId: "ttaengchil", event: "pair-discard", text: ["둘 똑같아! 버려!"] },
  { id: "ttaengchil-taken-from", characterId: "ttaengchil", event: "taken-from", text: ["가져가도 돼. 나 많아."] },
  { id: "ttaengchil-pair-made", characterId: "ttaengchil", event: "pair-made", text: ["맞았다! 왈! 맞았어! 봤어?"] },
  { id: "ttaengchil-joker-drawn", characterId: "ttaengchil", event: "joker-drawn", text: ["…이거 반짝이지도 않네."] },
  { id: "ttaengchil-joker-left", characterId: "ttaengchil", event: "joker-left", text: ["가져갔다. 잘 가."] },
  { id: "ttaengchil-emptied", characterId: "ttaengchil", event: "emptied", text: ["다 없어졌어. 이제 뭐 해? 나 여기 있어도 돼?"] },
  { id: "camille-watching", characterId: "camille", event: "watching", text: ["다들 무슨 얼굴을 하고 있는지…… 그게 제일 재밌는 부분이거든요오."] },
  { id: "camille-idle-draw", characterId: "camille", event: "idle-draw", text: ["한 장…… 시시하네에. 아무 반응도 안 나왔잖아요오."] },
  { id: "camille-pair-discard", characterId: "camille", event: "pair-discard", text: ["짝을 맞췄어요오. 이런 건 금방 끝나서 아쉬워어."] },
  { id: "camille-taken-from", characterId: "camille", event: "taken-from", text: ["가져가세요오. 어떤 표정을 지을지 보고 싶으니까아."] },
  { id: "camille-pair-made", characterId: "camille", event: "pair-made", text: ["어라. 벌써 맞았네에. 좀 더 헤매 주지이."] },
  { id: "camille-joker-drawn", characterId: "camille", event: "joker-drawn", text: ["……이건 제 취향이 아닌데에."] },
  { id: "camille-joker-left", characterId: "camille", event: "joker-left", text: ["잘 받으셨나요오. 천천히 즐기세요오."] },
  { id: "camille-emptied", characterId: "camille", event: "emptied", text: ["다 끝났네요오. 아무도 제 얼굴은 안 봤죠오?"] },
  { id: "raven-watching", characterId: "raven", event: "watching", text: ["진행 상황을 지켜보겠습니다. 관전도 서비스의 일부니까요."] },
  { id: "raven-idle-draw", characterId: "raven", event: "idle-draw", text: ["한 장 수령했습니다. 장부에 반영하겠습니다."] },
  { id: "raven-pair-discard", characterId: "raven", event: "pair-discard", text: ["결제 완료. 두 장을 정산했습니다."] },
  { id: "raven-taken-from", characterId: "raven", event: "taken-from", text: ["가져가십시오. 재고는 다시 채우면 됩니다."] },
  { id: "raven-pair-made", characterId: "raven", event: "pair-made", text: ["예상 수익 범위 안입니다."] },
  { id: "raven-joker-drawn", characterId: "raven", event: "joker-drawn", text: ["……이건 값을 매길 수가 없군요."] },
  { id: "raven-joker-left", characterId: "raven", event: "joker-left", text: ["양도 완료했습니다. 반품은 받지 않습니다."] },
  { id: "raven-emptied", characterId: "raven", event: "emptied", text: ["정산이 끝났습니다. 남은 건…… 돈으로 살 수 없는 것뿐이네요."] },
  { id: "deokbae-watching", characterId: "deokbae", event: "watching", text: ["…예전엔 이런 판을 다르게 불렀지. 이름은 잊었군."] },
  { id: "deokbae-idle-draw", characterId: "deokbae", event: "idle-draw", text: ["한 장. …이런 게 쌓여서 백 년이 됐지."] },
  { id: "deokbae-pair-discard", characterId: "deokbae", event: "pair-discard", text: ["맞는 것끼리는 결국 만나더군."] },
  { id: "deokbae-taken-from", characterId: "deokbae", event: "taken-from", text: ["가져가게. 쥐고 있어 봐야 무거워질 뿐이야."] },
  { id: "deokbae-pair-made", characterId: "deokbae", event: "pair-made", text: ["…운이군. 실력이라고 해 둘 나이는 지났어."] },
  { id: "deokbae-joker-drawn", characterId: "deokbae", event: "joker-drawn", text: ["…이런 건 예전에도 있었지. 이름만 달랐고."] },
  { id: "deokbae-joker-left", characterId: "deokbae", event: "joker-left", text: ["넘겼군. …누구 손에 있든 그건 그대로야."] },
  { id: "deokbae-emptied", characterId: "deokbae", event: "emptied", text: ["나는 여기까지야. …결국 아무것도 못 알아냈군."] },
  { id: "morsisa-watching", characterId: "morsisa", event: "watching", text: ["저, 저는 그냥… 보고 있을게요. 방해 안 되게."] },
  { id: "morsisa-idle-draw", characterId: "morsisa", event: "idle-draw", text: ["아, 하나… 가져왔습니다. 죄송합니다."] },
  { id: "morsisa-pair-discard", characterId: "morsisa", event: "pair-discard", text: ["마, 맞았네요. 이런 건 가끔… 되기도 하더라고요."] },
  { id: "morsisa-taken-from", characterId: "morsisa", event: "taken-from", text: ["가, 가져가세요. 어차피 제 건 별로…"] },
  { id: "morsisa-pair-made", characterId: "morsisa", event: "pair-made", text: ["어… 됐다. 됐어요. 아무한테도 말 안 할게요."] },
  { id: "morsisa-joker-drawn", characterId: "morsisa", event: "joker-drawn", text: ["역시… 저한테 오네요. 늘 이래요."] },
  { id: "morsisa-joker-left", characterId: "morsisa", event: "joker-left", text: ["가, 갔어요. 미안해요. 정말 미안해요."] },
  { id: "morsisa-emptied", characterId: "morsisa", event: "emptied", text: ["저… 끝났어요. 이번엔 아무한테도 폐 안 끼쳤죠?"] },
  { id: "yul-watching", characterId: "yul", event: "watching", text: ["어… 지금 누구 차례였죠?"] },
  { id: "yul-idle-draw", characterId: "yul", event: "idle-draw", text: ["한 장 뽑았고… 어, 이거 왜 뽑았더라."] },
  { id: "yul-pair-discard", characterId: "yul", event: "pair-discard", text: ["이거랑 이거랑 같네요. 버리면… 버리는 거 맞죠?"] },
  { id: "yul-taken-from", characterId: "yul", event: "taken-from", text: ["가져가세요. 어차피 뭐가 있었는지 기억 안 나요."] },
  { id: "yul-pair-made", characterId: "yul", event: "pair-made", text: ["어? 맞았네. 노린 건 아닌데."] },
  { id: "yul-joker-drawn", characterId: "yul", event: "joker-drawn", text: ["이건… 아, 이거 그거죠. 그… 나쁜 거."] },
  { id: "yul-joker-left", characterId: "yul", event: "joker-left", text: ["넘겼나요? 넘겼구나. 다행이다."] },
  { id: "yul-emptied", characterId: "yul", event: "emptied", text: ["다 없어졌네요. 제가 뭘 했는지는 모르겠는데, 잘 됐나 봐요."] },
  { id: "anna-watching", characterId: "anna", event: "watching", text: ["다들 편하게 해. …아니, 명령 아니야. 부탁이야."] },
  { id: "anna-idle-draw", characterId: "anna", event: "idle-draw", text: ["한 장 받았다. …고맙다는 뜻이야."] },
  { id: "anna-taken-from", characterId: "anna", event: "taken-from", text: ["가져가. 노려보는 거 아니야. 원래 눈이 이래."] },
  { id: "anna-pair-discard", characterId: "anna", event: "pair-discard", text: ["정리했다. 잘한 거 맞지? …맞다고 해 줘."] },
  { id: "anna-emptied", characterId: "anna", event: "emptied", text: ["먼저 빠진다. …다들 잘하고 있어. 진심이야. 표정이 문제지."] },
  { id: "apollyon-watching", characterId: "apollyon", event: "watching", text: ["…아직인가. …하아."] },
  { id: "apollyon-idle-draw", characterId: "apollyon", event: "idle-draw", text: ["한 장. …굳이 봐야 하나."] },
  { id: "apollyon-taken-from", characterId: "apollyon", event: "taken-from", text: ["가져가. 말리는 것도 일이라."] },
  { id: "apollyon-pair-discard", characterId: "apollyon", event: "pair-discard", text: ["둘. 버렸다. …끝."] },
  { id: "apollyon-emptied", characterId: "apollyon", event: "emptied", text: ["끝났군. …삼백 년 넘게, 뭐든 이렇게 끝나더라."] },
  { id: "bche-watching", characterId: "bche", event: "watching", text: ["남 노는 거 구경하는 게 제일 싸게 먹히지."] },
  { id: "bche-idle-draw", characterId: "bche", event: "idle-draw", text: ["한 장 획득. …획득 아이템, 쓰레기."] },
  { id: "bche-taken-from", characterId: "bche", event: "taken-from", text: ["가져가라. 어차피 내 건 원래 없었어."] },
  { id: "bche-pair-discard", characterId: "bche", event: "pair-discard", text: ["두 장 소모. 인벤토리 정리 완료."] },
  { id: "bche-emptied", characterId: "bche", event: "emptied", text: ["다 털었다. 이번 달 방세는… 아, 이건 돈 안 되지."] },
  { id: "cicero-watching", characterId: "cicero", event: "watching", text: ["지켜보고 있습니다. 1급쯤 되면 보는 것도 일이라."] },
  { id: "cicero-idle-draw", characterId: "cicero", event: "idle-draw", text: ["한 장 수령. 이 정도 배분은 계산 안에 있었습니다."] },
  { id: "cicero-taken-from", characterId: "cicero", event: "taken-from", text: ["가져가시죠. 하급자에게 양보하는 것도 등급의 의무니까."] },
  { id: "cicero-pair-discard", characterId: "cicero", event: "pair-discard", text: ["정리했습니다. 효율이란 이런 겁니다."] },
  { id: "cicero-emptied", characterId: "cicero", event: "emptied", text: ["먼저 끝냈습니다. …이런 거라도 1등은 해야죠."] },
  { id: "cradle-watching", characterId: "cradle", event: "watching", text: ["자자, 초보들은 잘 봐 두라고! 이게 바다다!"] },
  { id: "cradle-idle-draw", characterId: "cradle", event: "idle-draw", text: ["한 장 노획! …별거 아니군. 뭐, 항해가 다 그렇지."] },
  { id: "cradle-taken-from", characterId: "cradle", event: "taken-from", text: ["가져가라! 자유 해적은 뺏기는 것도 두려워하지 않는다!"] },
  { id: "cradle-pair-discard", characterId: "cradle", event: "pair-discard", text: ["둘을 바다에 던진다! 짐은 가벼울수록 좋아!"] },
  { id: "cradle-emptied", characterId: "cradle", event: "emptied", text: ["이 몸이 먼저 상륙했다! …남은 놈들, 조심해서 오라고."] },
  { id: "diamo-watching", characterId: "diamo", event: "watching", text: ["이 방… 전에도 있었어. 아니, 내가 아니라… 누가 있었지."] },
  { id: "diamo-idle-draw", characterId: "diamo", event: "idle-draw", text: ["한 장. 이거… 누군가 손에 쥐고 있었던 감촉이야."] },
  { id: "diamo-taken-from", characterId: "diamo", event: "taken-from", text: ["가져가. 그건 원래 내 것도 아니었으니까."] },
  { id: "diamo-pair-discard", characterId: "diamo", event: "pair-discard", text: ["둘이 만났네. …만난 적 있어. 여기서는 아니고."] },
  { id: "diamo-emptied", characterId: "diamo", event: "emptied", text: ["손이 비었어. 이제 누구 기억을 꾸면 되지?"] },
  { id: "esther-watching", characterId: "esther", event: "watching", text: ["다들 애쓰고 계시네요. 아픈 곳이 있으면 말씀하세요."] },
  { id: "esther-idle-draw", characterId: "esther", event: "idle-draw", text: ["한 장 받았어요. 다친 건 아니니 금방 정리할 수 있겠네요."] },
  { id: "esther-taken-from", characterId: "esther", event: "taken-from", text: ["가져가세요. 덜어 드리는 게 제 일이거든요."] },
  { id: "esther-pair-discard", characterId: "esther", event: "pair-discard", text: ["둘을 보내 드렸어요. 편안해 보이지 않나요."] },
  { id: "esther-emptied", characterId: "esther", event: "emptied", text: ["저는 끝났어요. 끝나는 건 나쁜 게 아니에요. 정말이에요."] },
  { id: "hiro-watching", characterId: "hiro", event: "watching", text: ["다들 잘하고 있어! 끝까지 집중하자!"] },
  { id: "hiro-idle-draw", characterId: "hiro", event: "idle-draw", text: ["한 장 받았다! 아직 승부는 끝나지 않았어!"] },
  { id: "hiro-taken-from", characterId: "hiro", event: "taken-from", text: ["가져가! 영웅은 나누는 법이니까."] },
  { id: "hiro-pair-discard", characterId: "hiro", event: "pair-discard", text: ["깔끔하게 정리! 이런 게 그림이 되거든."] },
  { id: "hiro-emptied", characterId: "hiro", event: "emptied", text: ["먼저 빠지겠어! …오늘도 잘 연기했다."] },
  { id: "katrinka-watching", characterId: "katrinka", event: "watching", text: ["지켜보는 건 무료야. 손대는 순간부터 청구되고."] },
  { id: "katrinka-idle-draw", characterId: "katrinka", event: "idle-draw", text: ["한 장. 원가에 포함이야."] },
  { id: "katrinka-taken-from", characterId: "katrinka", event: "taken-from", text: ["가져가. 청구서는 나중에 보낼게."] },
  { id: "katrinka-pair-discard", characterId: "katrinka", event: "pair-discard", text: ["정리 완료. 수수료는 이번만 면제해 줄게."] },
  { id: "katrinka-emptied", characterId: "katrinka", event: "emptied", text: ["다 정리했어. …장부에 안 적은 게 하나 있는데, 그건 됐어."] },
  { id: "kreva-watching", characterId: "kreva", event: "watching", text: ["관측 중. 불필요한 대화는 생략해도 되나."] },
  { id: "kreva-idle-draw", characterId: "kreva", event: "idle-draw", text: ["한 장. 규격 미달."] },
  { id: "kreva-taken-from", characterId: "kreva", event: "taken-from", text: ["가져가. 재고는 계산에 넣어 뒀어."] },
  { id: "kreva-pair-discard", characterId: "kreva", event: "pair-discard", text: ["두 장 제거. 목표 외에는 손대지 않아."] },
  { id: "kreva-emptied", characterId: "kreva", event: "emptied", text: ["끝. …이런 건 몸이 안 상해서 좋군."] },
  { id: "levillotte-watching", characterId: "levillotte", event: "watching", text: ["뭘 봐. 이 초강력 운을 가진 미소녀를 그렇게 보면 닳아."] },
  { id: "levillotte-idle-draw", characterId: "levillotte", event: "idle-draw", text: ["한 장? 흥, 내 운이면 이 정도는 당연하지."] },
  { id: "levillotte-taken-from", characterId: "levillotte", event: "taken-from", text: ["가져가. 어차피 너한테 갈 운명이었을걸."] },
  { id: "levillotte-pair-discard", characterId: "levillotte", event: "pair-discard", text: ["봤지? 이게 운이야. 실력 아니고."] },
  { id: "levillotte-emptied", characterId: "levillotte", event: "emptied", text: ["나 먼저 빠진다. …이번엔 아무도 대신 안 물었으면 좋겠는데."] },
  { id: "lilim-watching", characterId: "lilim", event: "watching", text: ["다, 다들… 이렇게 같이 앉는 거… 처음 봐요."] },
  { id: "lilim-idle-draw", characterId: "lilim", event: "idle-draw", text: ["하, 한 장… 받았어요. 이건… 뭐라고 부르는 거예요?"] },
  { id: "lilim-taken-from", characterId: "lilim", event: "taken-from", text: ["가, 가져가세요. 저는… 어차피 잘 몰라서."] },
  { id: "lilim-pair-discard", characterId: "lilim", event: "pair-discard", text: ["두 개가… 같아요. 같으면… 버리는 거 맞죠?"] },
  { id: "lilim-emptied", characterId: "lilim", event: "emptied", text: ["다… 없어졌어요. 저, 이제 어디로 가면… 아, 못 나가는구나."] },
  { id: "machina-watching", characterId: "machina", event: "watching", text: ["지켜보고 있어. 뭐 고장 나면 말해."] },
  { id: "machina-idle-draw", characterId: "machina", event: "idle-draw", text: ["한 장 들어왔고. 규격은 맞네."] },
  { id: "machina-taken-from", characterId: "machina", event: "taken-from", text: ["가져가. 부품은 갈면 되니까."] },
  { id: "machina-pair-discard", characterId: "machina", event: "pair-discard", text: ["두 개 정리. 정비는 미루면 손해야."] },
  { id: "machina-emptied", characterId: "machina", event: "emptied", text: ["내 쪽은 끝났어. …남은 사람들 거, 필요하면 봐 줄게."] },
  { id: "nostalgia-watching", characterId: "nostalgia", event: "watching", text: ["다들 편안하신가요. 여기 계신 모두가 사랑받을 자격이 있어요."] },
  { id: "nostalgia-idle-draw", characterId: "nostalgia", event: "idle-draw", text: ["한 장 받았어요. 무엇이 오든 감사한 일이지요."] },
  { id: "nostalgia-taken-from", characterId: "nostalgia", event: "taken-from", text: ["가져가세요. 나누는 것이 먼저 배워야 할 일이니까요."] },
  { id: "nostalgia-pair-discard", characterId: "nostalgia", event: "pair-discard", text: ["둘을 보냈습니다. …구원이란 원래 덜어 내는 일이에요."] },
  { id: "nostalgia-emptied", characterId: "nostalgia", event: "emptied", text: ["저는 먼저 끝났네요. 기다릴게요. 여러분 전부, 끝까지."] },
  { id: "phaeo-watching", characterId: "phaeo", event: "watching", text: ["관찰 중입니다. 누가 먼저 무너지는지는 대개 초반에 보이죠."] },
  { id: "phaeo-idle-draw", characterId: "phaeo", event: "idle-draw", text: ["한 장. 통계상 의미 없는 수치입니다."] },
  { id: "phaeo-taken-from", characterId: "phaeo", event: "taken-from", text: ["가져가십시오. 남는 것에 의미를 두면 오래 못 갑니다."] },
  { id: "phaeo-pair-discard", characterId: "phaeo", event: "pair-discard", text: ["두 장 제외. 줄어드는 건 좋은 신호입니다."] },
  { id: "phaeo-emptied", characterId: "phaeo", event: "emptied", text: ["저는 여기까지군요. …이번엔 이름을 안 적어도 되겠습니다."] },
  { id: "temute-watching", characterId: "temute", event: "watching", text: ["하아… 다들 신중하시네. 좋은 거야, 그거."] },
  { id: "temute-idle-draw", characterId: "temute", event: "idle-draw", text: ["하아. 한 장 받았고. 뭐, 이런 거지."] },
  { id: "temute-taken-from", characterId: "temute", event: "taken-from", text: ["가져가. 붙들고 있어 봐야 좋을 거 없어."] },
  { id: "temute-pair-discard", characterId: "temute", event: "pair-discard", text: ["정리했어. 하아, 이런 건 빨리빨리 해야 편해."] },
  { id: "temute-emptied", characterId: "temute", event: "emptied", text: ["나 먼저 끝났다. …야, 너 조심해. 아니, 아무것도 아니야."] },
  { id: "traver-watching", characterId: "traver", event: "watching", text: ["보는 중. 분수껏 하면 돼."] },
  { id: "traver-idle-draw", characterId: "traver", event: "idle-draw", text: ["한 장. 이 정도면 됐어."] },
  { id: "traver-taken-from", characterId: "traver", event: "taken-from", text: ["가져가. 욕심부리면 34층 꼴 나."] },
  { id: "traver-pair-discard", characterId: "traver", event: "pair-discard", text: ["둘 처분. 무거우면 못 걸어."] },
  { id: "traver-emptied", characterId: "traver", event: "emptied", text: ["나 빠진다. …분수껏 했으니까 이런 거지."] },
  { id: "tumit-tu-watching", characterId: "tumit-tu", event: "watching", text: ["오, 이거 완전 S랭크급 긴장감인데요!"] },
  { id: "tumit-tu-idle-draw", characterId: "tumit-tu", event: "idle-draw", text: ["한 장 획득! E랭크 헌터의 손맛이란 이런 겁니다!"] },
  { id: "tumit-tu-taken-from", characterId: "tumit-tu", event: "taken-from", text: ["가져가세요! E랭크쯤 되면 이 정도는 안 아까워요!"] },
  { id: "tumit-tu-pair-discard", characterId: "tumit-tu", event: "pair-discard", text: ["짝 완성! 봤죠? 봤죠?!"] },
  { id: "tumit-tu-emptied", characterId: "tumit-tu", event: "emptied", text: ["제가 1등! …누나한테 자랑해야지."] },
  { id: "anna-pair-made", characterId: "anna", event: "pair-made", text: ["맞았다. …웃은 거야. 지금 이거 웃은 거다."] },
  { id: "anna-joker-drawn", characterId: "anna", event: "joker-drawn", text: ["이건 내가 들고 있겠다. …아니, 뺏은 거 아니야."] },
  { id: "anna-joker-left", characterId: "anna", event: "joker-left", text: ["넘어갔다. …미안. 진짜로 미안하다는 뜻이야."] },
  { id: "apollyon-pair-made", characterId: "apollyon", event: "pair-made", text: ["맞았군. …기뻐해야 하나. 하아."] },
  { id: "apollyon-joker-drawn", characterId: "apollyon", event: "joker-drawn", text: ["왔군. …뭐, 상관없다. 상관있는 게 없어서."] },
  { id: "apollyon-joker-left", characterId: "apollyon", event: "joker-left", text: ["갔군. 하아… 붙잡을 이유가 없었다."] },
  { id: "bche-pair-made", characterId: "bche", event: "pair-made", text: ["오, 맞았네. 운빨 스탯이 올랐나?"] },
  { id: "bche-joker-drawn", characterId: "bche", event: "joker-drawn", text: ["하. 역시 나한테 오네. 이게 내 고정 운명이지."] },
  { id: "bche-joker-left", characterId: "bche", event: "joker-left", text: ["넘겼다. 이번 판은 살았어. 방세는 아직이지만."] },
  { id: "cicero-pair-made", characterId: "cicero", event: "pair-made", text: ["당연한 결과입니다. 1급이 괜히 1급이겠습니까."] },
  { id: "cicero-joker-drawn", characterId: "cicero", event: "joker-drawn", text: ["…이건 배분의 문제지 실력의 문제가 아닙니다."] },
  { id: "cicero-joker-left", characterId: "cicero", event: "joker-left", text: ["처리했습니다. 하급자에게 넘어간 건 제 알 바 아니고."] },
  { id: "cradle-pair-made", characterId: "cradle", event: "pair-made", text: ["명중! 이 몸의 항해술을 봤나!"] },
  { id: "cradle-joker-drawn", characterId: "cradle", event: "joker-drawn", text: ["검은 깃발이 내 배에 올랐군! …뭐, 선장이 짊어져야지."] },
  { id: "cradle-joker-left", characterId: "cradle", event: "joker-left", text: ["넘어갔다! 초보, 겁먹지 마라! 그것도 항해의 일부야!"] },
  { id: "diamo-pair-made", characterId: "diamo", event: "pair-made", text: ["맞았어… 이 감각, 누가 기뻐했던 거지."] },
  { id: "diamo-joker-drawn", characterId: "diamo", event: "joker-drawn", text: ["아… 이건 아무도 기억 안 하는 거야. 그래서 나한테 왔나."] },
  { id: "diamo-joker-left", characterId: "diamo", event: "joker-left", text: ["갔네. 잘 가. …이 기억은 이제 누구의 것이지."] },
  { id: "esther-pair-made", characterId: "esther", event: "pair-made", text: ["어머, 맞았네요. 둘이 같이 갈 수 있어서 다행이에요."] },
  { id: "esther-joker-drawn", characterId: "esther", event: "joker-drawn", text: ["제게 오셨군요. …괜찮아요. 제가 안고 있을게요."] },
  { id: "esther-joker-left", characterId: "esther", event: "joker-left", text: ["가셨네요. 부디 편안한 곳으로."] },
  { id: "hiro-pair-made", characterId: "hiro", event: "pair-made", text: ["역시 나야! 이 정도는 해내야 그림이 되지!"] },
  { id: "hiro-joker-drawn", characterId: "hiro", event: "joker-drawn", text: ["하하, 이런 것도 영웅의 몫이지! …왜 항상 나지."] },
  { id: "hiro-joker-left", characterId: "hiro", event: "joker-left", text: ["넘겼다! …정의라는 게 원래 남한테 떠넘기는 거였나."] },
  { id: "katrinka-pair-made", characterId: "katrinka", event: "pair-made", text: ["맞췄어. 이건 청구 안 할게."] },
  { id: "katrinka-joker-drawn", characterId: "katrinka", event: "joker-drawn", text: ["…이건 위험 수당 대상인데. 누가 내지?"] },
  { id: "katrinka-joker-left", characterId: "katrinka", event: "joker-left", text: ["넘어갔어. 처리 비용은… 됐어, 이번엔 그냥 갈게."] },
  { id: "kreva-pair-made", characterId: "kreva", event: "pair-made", text: ["명중. 규격 일치."] },
  { id: "kreva-joker-drawn", characterId: "kreva", event: "joker-drawn", text: ["목표 외 개체. …처리 대상이 아닌데."] },
  { id: "kreva-joker-left", characterId: "kreva", event: "joker-left", text: ["이관 완료. 저건 내 담당이 아니야."] },
  { id: "levillotte-pair-made", characterId: "levillotte", event: "pair-made", text: ["봤지? 초강력 운. 이래서 내가 미소녀인 거야."] },
  { id: "levillotte-joker-drawn", characterId: "levillotte", event: "joker-drawn", text: ["…어라. 내 운이 왜. 뭐, 이 정도는 액땜이지."] },
  { id: "levillotte-joker-left", characterId: "levillotte", event: "joker-left", text: ["갔다. …야, 너 괜찮아? 아니, 신경 쓴 거 아니야."] },
  { id: "lilim-pair-made", characterId: "lilim", event: "pair-made", text: ["어… 맞았어요? 제가… 잘한 거예요?"] },
  { id: "lilim-joker-drawn", characterId: "lilim", event: "joker-drawn", text: ["이, 이거… 아무도 안 가져가는 거예요? 왜요?"] },
  { id: "lilim-joker-left", characterId: "lilim", event: "joker-left", text: ["가, 갔어요… 근데 왜 다들 안심하는 표정이에요?"] },
  { id: "machina-pair-made", characterId: "machina", event: "pair-made", text: ["맞았네. 정비 잘 됐다는 뜻이지."] },
  { id: "machina-joker-drawn", characterId: "machina", event: "joker-drawn", text: ["아, 이거 나한테 왔네. 괜찮아, 나는 튼튼하니까."] },
  { id: "machina-joker-left", characterId: "machina", event: "joker-left", text: ["갔어. …조심해. 그건 갈아 끼울 수 있는 부품이 아니야."] },
  { id: "nostalgia-pair-made", characterId: "nostalgia", event: "pair-made", text: ["만났군요. 만남은 언제나 축복입니다."] },
  { id: "nostalgia-joker-drawn", characterId: "nostalgia", event: "joker-drawn", text: ["제게 왔네요. …이 아이도 사랑받을 자격이 있어요."] },
  { id: "nostalgia-joker-left", characterId: "nostalgia", event: "joker-left", text: ["떠났군요. 어디에 있든 사랑받아야 해요. …그래야만 해요."] },
  { id: "phaeo-pair-made", characterId: "phaeo", event: "pair-made", text: ["두 장 일치. 통계 안입니다."] },
  { id: "phaeo-joker-drawn", characterId: "phaeo", event: "joker-drawn", text: ["예상대로군요. 누군가는 맡습니다. 늘 그렇습니다."] },
  { id: "phaeo-joker-left", characterId: "phaeo", event: "joker-left", text: ["이관됐습니다. …저쪽이 오래 못 버티겠군요."] },
  { id: "temute-pair-made", characterId: "temute", event: "pair-made", text: ["하아, 맞았네. 이런 날도 있어야지."] },
  { id: "temute-joker-drawn", characterId: "temute", event: "joker-drawn", text: ["하아… 그래, 이런 건 보통 나한테 와."] },
  { id: "temute-joker-left", characterId: "temute", event: "joker-left", text: ["넘겼다. …야, 그거 잘 들고 있어. 놓치지 말고."] },
  { id: "traver-pair-made", characterId: "traver", event: "pair-made", text: ["맞았네. 이 정도면 충분해."] },
  { id: "traver-joker-drawn", characterId: "traver", event: "joker-drawn", text: ["…이건 분수 밖인데."] },
  { id: "traver-joker-left", characterId: "traver", event: "joker-left", text: ["털었다. 무거운 건 안 들고 다니는 게 원칙이야."] },
  { id: "tumit-tu-pair-made", characterId: "tumit-tu", event: "pair-made", text: ["이게 바로 E랭크의 실력! 봤죠?!"] },
  { id: "tumit-tu-joker-drawn", characterId: "tumit-tu", event: "joker-drawn", text: ["어… 이거 S랭크 난이도 아닙니까?"] },
  { id: "tumit-tu-joker-left", characterId: "tumit-tu", event: "joker-left", text: ["넘겼다! E랭크는 위기를 이렇게 넘깁니다!"] },
] as const satisfies readonly OldMaidLine[];
