import type { OldMaidLine } from "./contracts.ts";

/** CHARX-reviewed dialogue for the 26 audited Bestiaization-era casino NPCs. */
export const temerosaCasinoOldMaidLines = [
  { id: "echo-watching", characterId: "echo", event: "watching", text: ["에코는 보는 중이야. 지루하다고 에코는 생각해."] },
  { id: "echo-idle-draw", characterId: "echo", event: "idle-draw", text: ["에코가 뽑았어! 안 예쁘다고 말하고 있어."] },
  { id: "echo-pair-discard", characterId: "echo", event: "pair-discard", text: ["짝 맞췄어! 에코는 지금 신나고 있어."] },
  { id: "echo-taken-from", characterId: "echo", event: "taken-from", text: ["누가 집어갔어! 에코는 안 막고 보고 있어."] },
  { id: "echo-pair-made", characterId: "echo", event: "pair-made", text: ["맞았어! 에코는 이걸 순전히 운이라고 생각해."] },
  { id: "echo-joker-drawn", characterId: "echo", event: "joker-drawn", text: ["조커야! 에코는 엄청 당황했다고 소리치는 중이야."] },
  { id: "echo-joker-left", characterId: "echo", event: "joker-left", text: ["갔어! 에코는 속으로 휴 하고 한숨 쉬어."] },
  { id: "echo-emptied", characterId: "echo", event: "emptied", text: ["에코 털었어! 무슨 생각인지 다 들켰지?"] },
  { id: "adesha-watching", characterId: "adesha", event: "watching", text: ["상황 관측. 대기."] },
  { id: "adesha-idle-draw", characterId: "adesha", event: "idle-draw", text: ["카드 인수. 의미 없음."] },
  { id: "adesha-pair-discard", characterId: "adesha", event: "pair-discard", text: ["쌍 일치. 폐기."] },
  { id: "adesha-taken-from", characterId: "adesha", event: "taken-from", text: ["패 인출 확인. 문제없음."] },
  { id: "adesha-pair-made", characterId: "adesha", event: "pair-made", text: ["조건 일치. 정합 확인."] },
  { id: "adesha-joker-drawn", characterId: "adesha", event: "joker-drawn", text: ["…이물질 유입. 경계."] },
  { id: "adesha-joker-left", characterId: "adesha", event: "joker-left", text: ["이물질 이관. 손패 변동."] },
  { id: "adesha-emptied", characterId: "adesha", event: "emptied", text: ["손패 전량 소진. 다음 지시 대기."] },
  { id: "ttaengchil-watching", characterId: "ttaengchil", event: "watching", text: ["다들 잠잠하네! 나 여기 보고 있다!"] },
  { id: "ttaengchil-idle-draw", characterId: "ttaengchil", event: "idle-draw", text: ["쓱 집었다! 으응, 이거 아니야!"] },
  { id: "ttaengchil-pair-discard", characterId: "ttaengchil", event: "pair-discard", text: ["둘이 똑같다! 딱 버려!"] },
  { id: "ttaengchil-taken-from", characterId: "ttaengchil", event: "taken-from", text: ["가져가라! 나 아직 많다!"] },
  { id: "ttaengchil-pair-made", characterId: "ttaengchil", event: "pair-made", text: ["맞았다! 왈! 맞았어! 봤냐!"] },
  { id: "ttaengchil-joker-drawn", characterId: "ttaengchil", event: "joker-drawn", text: ["…이거 안 반짝거려! 으르렁!"] },
  { id: "ttaengchil-joker-left", characterId: "ttaengchil", event: "joker-left", text: ["가져갔다! 나쁜 거 잘 가라!"] },
  { id: "ttaengchil-emptied", characterId: "ttaengchil", event: "emptied", text: ["다 없어졌다! 나 이제 뭐 해!"] },
  { id: "camille-watching", characterId: "camille", event: "watching", text: ["어떤 표정들을 지을까아… 그게 제일 재밌거든요오."] },
  { id: "camille-idle-draw", characterId: "camille", event: "idle-draw", text: ["한 장 슥… 시시하네에, 반응이 없잖아요오."] },
  { id: "camille-pair-discard", characterId: "camille", event: "pair-discard", text: ["짝 맞췄어요오. 벌써 버리면 아쉬운데에."] },
  { id: "camille-taken-from", characterId: "camille", event: "taken-from", text: ["가져가세요오. 어떤 얼굴 되나 보게에."] },
  { id: "camille-pair-made", characterId: "camille", event: "pair-made", text: ["어라, 짝이 맞았네요오. 좀 더 헤매 주지이."] },
  { id: "camille-joker-drawn", characterId: "camille", event: "joker-drawn", text: ["…우응, 이건 제 스타일 아닌데요오."] },
  { id: "camille-joker-left", characterId: "camille", event: "joker-left", text: ["잘 받으셨지요오? 꽉 잡고 계세요오."] },
  { id: "camille-emptied", characterId: "camille", event: "emptied", text: ["다 비웠네요오. 제 표정 읽은 사람 있나요오?"] },
  { id: "raven-watching", characterId: "raven", event: "watching", text: ["상황을 주시하겠습니다. 관전도 서비스입니다."] },
  { id: "raven-idle-draw", characterId: "raven", event: "idle-draw", text: ["한 장 입고했습니다. 장부에 반영하겠습니다."] },
  { id: "raven-pair-discard", characterId: "raven", event: "pair-discard", text: ["정산 완료했습니다. 두 장 버렸습니다."] },
  { id: "raven-taken-from", characterId: "raven", event: "taken-from", text: ["가져가십시오. 재고는 다시 채우겠습니다."] },
  { id: "raven-pair-made", characterId: "raven", event: "pair-made", text: ["예상 수익 범위 안입니다. 깔끔합니다."] },
  { id: "raven-joker-drawn", characterId: "raven", event: "joker-drawn", text: ["…이건 단가를 매길 수가 없는 물품입니다."] },
  { id: "raven-joker-left", characterId: "raven", event: "joker-left", text: ["양도 완료했습니다. 반품은 받지 않습니다."] },
  { id: "raven-emptied", characterId: "raven", event: "emptied", text: ["결제가 끝났습니다. 장부를 덮겠습니다."] },
  { id: "deokbae-watching", characterId: "deokbae", event: "watching", text: ["…예전엔 이런 판을 다르게 불렀는데. …이름이 뭐였더라."] },
  { id: "deokbae-idle-draw", characterId: "deokbae", event: "idle-draw", text: ["한 장… 이런 게 얹히며 백 년이 지났군."] },
  { id: "deokbae-pair-discard", characterId: "deokbae", event: "pair-discard", text: ["짝이 맞으면 결국 털어내는 거다."] },
  { id: "deokbae-taken-from", characterId: "deokbae", event: "taken-from", text: ["집어가게. 오래 품고 있어 봐야 손만 무겁다."] },
  { id: "deokbae-pair-made", characterId: "deokbae", event: "pair-made", text: ["…운이 좋았군. 늙은이가 실력을 논할 판은 아니지."] },
  { id: "deokbae-joker-drawn", characterId: "deokbae", event: "joker-drawn", text: ["…또 손에 들어왔군. 예전에도 이름만 다른 게 돌았지."] },
  { id: "deokbae-joker-left", characterId: "deokbae", event: "joker-left", text: ["털어냈군. …누구 손에 가든 흉물은 흉물이다."] },
  { id: "deokbae-emptied", characterId: "deokbae", event: "emptied", text: ["손을 비웠군. …결국 알게 된 건 하나도 없어."] },
  { id: "morsisa-watching", characterId: "morsisa", event: "watching", text: ["저, 저는 그냥… 구경만 할게요. 방해 안 되게…"] },
  { id: "morsisa-idle-draw", characterId: "morsisa", event: "idle-draw", text: ["아, 한 장… 가져왔는데요. 죄송해요…"] },
  { id: "morsisa-pair-discard", characterId: "morsisa", event: "pair-discard", text: ["마, 맞았어요… 이런 게 가끔 되더라고요."] },
  { id: "morsisa-taken-from", characterId: "morsisa", event: "taken-from", text: ["가, 가져가세요. 어차피 제 건 별 볼 일 없어서…"] },
  { id: "morsisa-pair-made", characterId: "morsisa", event: "pair-made", text: ["어… 됐다, 됐어요. 아무한테도 안 말할게요…"] },
  { id: "morsisa-joker-drawn", characterId: "morsisa", event: "joker-drawn", text: ["역시… 저한테 오네요. 늘 이렇더라고요…"] },
  { id: "morsisa-joker-left", characterId: "morsisa", event: "joker-left", text: ["가, 갔어요… 미안해요, 정말 미안해요…"] },
  { id: "morsisa-emptied", characterId: "morsisa", event: "emptied", text: ["저… 다 털었어요. 이번엔 폐 안 끼친 거 맞죠…?"] },
  { id: "yul-watching", characterId: "yul", event: "watching", text: ["어… 지금 누구 차례였죠? 저였나요?"] },
  { id: "yul-idle-draw", characterId: "yul", event: "idle-draw", text: ["일단 한 장 뽑았고… 어, 이거 왜 뽑았더라?"] },
  { id: "yul-pair-discard", characterId: "yul", event: "pair-discard", text: ["이거랑 이거랑 똑같네요. …버리는 거 맞죠?"] },
  { id: "yul-taken-from", characterId: "yul", event: "taken-from", text: ["가져가세요. 어차피 저한테 뭐가 있었는지 잊어버렸어요."] },
  { id: "yul-pair-made", characterId: "yul", event: "pair-made", text: ["어? 짝이 맞았네. …뭐 맞추려고 한 거였죠?"] },
  { id: "yul-joker-drawn", characterId: "yul", event: "joker-drawn", text: ["이건… 아, 그 나쁜 카드 맞죠? 어떡하지…"] },
  { id: "yul-joker-left", characterId: "yul", event: "joker-left", text: ["넘어갔나요? 다행이다. …방금 뭐가 넘어갔더라?"] },
  { id: "yul-emptied", characterId: "yul", event: "emptied", text: ["다 없어졌어요. 제가 뭘 했는지는 모르겠는데… 잘 된 거죠?"] },
  { id: "anna-watching", characterId: "anna", event: "watching", text: ["다들 편하게 해. …아니, 명령 아니야. 부탁하는 거야."] },
  { id: "anna-idle-draw", characterId: "anna", event: "idle-draw", text: ["한 장 가져간다. …고맙다는 뜻이야. 진짜야."] },
  { id: "anna-taken-from", characterId: "anna", event: "taken-from", text: ["가져가. …노려본 거 아니야! 내 눈이 원래 이래."] },
  { id: "anna-pair-discard", characterId: "anna", event: "pair-discard", text: ["정리 끝났다. 잘한 거 맞지? …그렇다고 해 줘."] },
  { id: "anna-emptied", characterId: "anna", event: "emptied", text: ["나 먼저 빠질게. …다들 잘하고 있어. 나 비꼬는 거 아니야!"] },
  { id: "apollyon-watching", characterId: "apollyon", event: "watching", text: ["…아직인가. …하아."] },
  { id: "apollyon-idle-draw", characterId: "apollyon", event: "idle-draw", text: ["한 장. …굳이 들여다볼 가치도 없군."] },
  { id: "apollyon-taken-from", characterId: "apollyon", event: "taken-from", text: ["집어가라. 말리는 것조차 번거롭다."] },
  { id: "apollyon-pair-discard", characterId: "apollyon", event: "pair-discard", text: ["둘 버렸다. …끝이다."] },
  { id: "apollyon-emptied", characterId: "apollyon", event: "emptied", text: ["끝났군. …삼백 년 넘게, 모든 게 다 이렇게 끝났지."] },
  { id: "bche-watching", characterId: "bche", event: "watching", text: ["남 노는 거나 쳐다보는 게 제일 돈 안 들고 편하지."] },
  { id: "bche-idle-draw", characterId: "bche", event: "idle-draw", text: ["한 장 획득. …물건 값어치, 최하위 쓰레기."] },
  { id: "bche-taken-from", characterId: "bche", event: "taken-from", text: ["가져가라. 어차피 내 것에 좋은 건 없었어."] },
  { id: "bche-pair-discard", characterId: "bche", event: "pair-discard", text: ["두 장 소모. 짐 정리는 확실하네."] },
  { id: "bche-emptied", characterId: "bche", event: "emptied", text: ["손패 싹 털었다. 이번 달 방세는… 아, 이건 돈 안 주는 판이지."] },
  { id: "cicero-watching", characterId: "cicero", event: "watching", text: ["지켜보는 중이다. 1급쯤 되면 관찰도 작업의 일환이지."] },
  { id: "cicero-idle-draw", characterId: "cicero", event: "idle-draw", text: ["한 장 수령. 이 정도 변수는 연산 범위 안이다."] },
  { id: "cicero-taken-from", characterId: "cicero", event: "taken-from", text: ["가져가도록. 하급자에게 부품을 양보하는 것도 1급의 의무지."] },
  { id: "cicero-pair-discard", characterId: "cicero", event: "pair-discard", text: ["회로 정렬 완료. 효율이란 이런 것이다."] },
  { id: "cicero-emptied", characterId: "cicero", event: "emptied", text: ["기량 검증 완료. …이런 영세한 판이라도 최고 등급을 입증해야지."] },
  { id: "cradle-watching", characterId: "cradle", event: "watching", text: ["똑똑히 봐 둬라, 신참! 이게 진짜 바다판이다!"] },
  { id: "cradle-idle-draw", characterId: "cradle", event: "idle-draw", text: ["한 장 노획! …흠, 별거 없군. 원래 항해란 이런 거다."] },
  { id: "cradle-taken-from", characterId: "cradle", event: "taken-from", text: ["가져가라! 뺏기는 것쯤으로 졸지 마라, 그게 해적이다!"] },
  { id: "cradle-pair-discard", characterId: "cradle", event: "pair-discard", text: ["둘은 바다에 던져라! 배는 짐이 가벼워야 잘 뜨는 거다!"] },
  { id: "cradle-emptied", characterId: "cradle", event: "emptied", text: ["이 몸은 육지에 닿았다! …너희도 닻 내릴 때까지 방심 마라!"] },
  { id: "diamo-watching", characterId: "diamo", event: "watching", text: ["이 테이블… 전에도 앉아 본 것 같아. 내가… 아니었던가."] },
  { id: "diamo-idle-draw", characterId: "diamo", event: "idle-draw", text: ["한 장. 손끝에 남아 있네… 다른 사람이 만졌던 온도가."] },
  { id: "diamo-taken-from", characterId: "diamo", event: "taken-from", text: ["가져가네. 괜찮아… 어차피 내 손에 있던 적 없었어."] },
  { id: "diamo-pair-discard", characterId: "diamo", event: "pair-discard", text: ["둘이 맞았구나. …어디선가 짝을 맞춰 본 느낌인데."] },
  { id: "diamo-emptied", characterId: "diamo", event: "emptied", text: ["손패가 비었네. …이제 내 손에 남은 건 누구 기억이지?"] },
  { id: "esther-watching", characterId: "esther", event: "watching", text: ["다들 참 열심히 하시네요. 많이 피곤하시면 편히 숨 돌리세요."] },
  { id: "esther-idle-draw", characterId: "esther", event: "idle-draw", text: ["한 장 가져왔어요. 별탈 없이 조용히 넘어갈 생각이에요."] },
  { id: "esther-taken-from", characterId: "esther", event: "taken-from", text: ["가져가셔도 괜찮아요. 무거운 짐은 제가 덜어 드려야지요."] },
  { id: "esther-pair-discard", characterId: "esther", event: "pair-discard", text: ["두 장은 내려놓을게요. 나란히 놓인 모습이 아주 편해 보여요."] },
  { id: "esther-emptied", characterId: "esther", event: "emptied", text: ["제 손패는 모두 비었어요. 놓아주는 법을 배우면 참 편해져요."] },
  { id: "hiro-watching", characterId: "hiro", event: "watching", text: ["다들 멋진 승부를 보여주고 계십니다! 끝까지 힘내시지요!"] },
  { id: "hiro-idle-draw", characterId: "hiro", event: "idle-draw", text: ["카드 한 장 받아 들겠습니다! 아직 승부는 시작에 불과합니다!"] },
  { id: "hiro-taken-from", characterId: "hiro", event: "taken-from", text: ["마음에 드신다면 가져가십시오! 나눠 주는 것이 영웅의 미덕입니다!"] },
  { id: "hiro-pair-discard", characterId: "hiro", event: "pair-discard", text: ["깔끔하게 정리하겠습니다! 연출이 아주 보기 좋군요!"] },
  { id: "hiro-emptied", characterId: "hiro", event: "emptied", text: ["제 손에 든 카드를 모두 털어냈습니다! 깔끔한 승부였습니다!"] },
  { id: "katrinka-watching", characterId: "katrinka", event: "watching", text: ["수수료 없이 관전하는 건 여기까지야. 손대는 순간부터 과금 들어간다."] },
  { id: "katrinka-idle-draw", characterId: "katrinka", event: "idle-draw", text: ["한 장 뽑았어. 기본 이용료에 포함된 수량이야."] },
  { id: "katrinka-taken-from", characterId: "katrinka", event: "taken-from", text: ["가져가든가. 청구서는 판 끝나고 한꺼번에 보낼 테니까."] },
  { id: "katrinka-pair-discard", characterId: "katrinka", event: "pair-discard", text: ["두 장 세트로 처리했어. 정리 수수료는 서비스로 쳐줄게."] },
  { id: "katrinka-emptied", characterId: "katrinka", event: "emptied", text: ["손패 다 정리했어. 장부 잔액 깔끔하게 맞췄으니 난 이만."] },
  { id: "kreva-watching", characterId: "kreva", event: "watching", text: ["판세 관측 중. 불필요한 신호 교환 생략."] },
  { id: "kreva-idle-draw", characterId: "kreva", event: "idle-draw", text: ["1장 인입. 유효 데이터 미달."] },
  { id: "kreva-taken-from", characterId: "kreva", event: "taken-from", text: ["손패 1장 이탈. 잔여 재고 수량 계산에 반영 완료."] },
  { id: "kreva-pair-discard", characterId: "kreva", event: "pair-discard", text: ["동일 동력원 2장 배출 완료. 지정 목표 외 배제."] },
  { id: "kreva-emptied", characterId: "kreva", event: "emptied", text: ["손패 소진. 연산 가동률 정상 수치 복귀."] },
  { id: "levillotte-watching", characterId: "levillotte", event: "watching", text: ["뭘 빤히 봐? 초강력 운을 가진 미소녀 보는 눈빛 치고는 너무 둔한데."] },
  { id: "levillotte-idle-draw", characterId: "levillotte", event: "idle-draw", text: ["한 장 당겨볼까? 흥, 이 몸의 럭키 지수면 뭘 뽑아도 대박이거든."] },
  { id: "levillotte-taken-from", characterId: "levillotte", event: "taken-from", text: ["가져가라, 가져가. 미소녀의 넓은 마음으로 넘겨주는 거니까."] },
  { id: "levillotte-pair-discard", characterId: "levillotte", event: "pair-discard", text: ["봤지? 싹 정리되는 거. 타고난 미모와 운이 합쳐지면 당연한 결과라고!"] },
  { id: "levillotte-emptied", characterId: "levillotte", event: "emptied", text: ["나 손 다 비웠다! 역시 완벽한 운이었네! …휴, 덤터기 안 써서 다행이다."] },
  { id: "lilim-watching", characterId: "lilim", event: "watching", text: ["다, 다들… 이렇게 같이 모여서… 뭐 하는 거예요?"] },
  { id: "lilim-idle-draw", characterId: "lilim", event: "idle-draw", text: ["한 장… 가져왔어요. 이건 안 버려요?"] },
  { id: "lilim-taken-from", characterId: "lilim", event: "taken-from", text: ["저기… 제 거 뽑아간 거예요?"] },
  { id: "lilim-pair-discard", characterId: "lilim", event: "pair-discard", text: ["어… 똑같은 게 두 개면… 버리는 게 맞죠?"] },
  { id: "lilim-emptied", characterId: "lilim", event: "emptied", text: ["제 손이… 다 비었어요. 저 이제 어떡해요?"] },
  { id: "machina-watching", characterId: "machina", event: "watching", text: ["지켜보고 있어. 뭐 고장 나면 바로 말해."] },
  { id: "machina-idle-draw", characterId: "machina", event: "idle-draw", text: ["한 장 뽑았어. 규격은 딱 맞네."] },
  { id: "machina-taken-from", characterId: "machina", event: "taken-from", text: ["가져가도 돼. 부품이야 갈아 끼우면 되니까."] },
  { id: "machina-pair-discard", characterId: "machina", event: "pair-discard", text: ["짝 맞춰서 정리! 정비는 미루면 손해야."] },
  { id: "machina-emptied", characterId: "machina", event: "emptied", text: ["내 쪽 정비는 끝났어. 남은 사람들 거 도와줄까?"] },
  { id: "nostalgia-watching", characterId: "nostalgia", event: "watching", text: ["편안히 기다리세요. 여기 계신 모두가 소중한 분들이지요."] },
  { id: "nostalgia-idle-draw", characterId: "nostalgia", event: "idle-draw", text: ["카드를 한 장 받았어요. 무엇이 오든 감사히 받아들여야 해요."] },
  { id: "nostalgia-taken-from", characterId: "nostalgia", event: "taken-from", text: ["편히 가져가세요. 나눔은 제일 먼저 배워야 할 미덕이니까요."] },
  { id: "nostalgia-pair-discard", characterId: "nostalgia", event: "pair-discard", text: ["둘을 내려놓았어요. 구원이란 불필요한 무게를 덜어 내는 일이지요."] },
  { id: "nostalgia-emptied", characterId: "nostalgia", event: "emptied", text: ["제 패는 다 비었어요. 남아 계신 분들을 위해 끝까지 기도할게요."] },
  { id: "phaeo-watching", characterId: "phaeo", event: "watching", text: ["대상들 관찰 중. 초반 패 배분에서 생존 확률 도출 가능."] },
  { id: "phaeo-idle-draw", characterId: "phaeo", event: "idle-draw", text: ["1장 수령. 통계상 의미 없는 수치 변화."] },
  { id: "phaeo-taken-from", characterId: "phaeo", event: "taken-from", text: ["1장 피탈. 잔여물에 집착할 시 조기 탈락 예정."] },
  { id: "phaeo-pair-discard", characterId: "phaeo", event: "pair-discard", text: ["2장 제외 처리. 잔여 패 감소는 긍정적 신호."] },
  { id: "phaeo-emptied", characterId: "phaeo", event: "emptied", text: ["손패 전량 소진. 명부에 사망 기록은 작성 예외."] },
  { id: "temute-watching", characterId: "temute", event: "watching", text: ["다들 너무 뜸 들이네. 쫄지 말고 천천히 집어."] },
  { id: "temute-idle-draw", characterId: "temute", event: "idle-draw", text: ["한 장 집었네. 뭐, 주는 대로 받아 챙겨야지."] },
  { id: "temute-taken-from", characterId: "temute", event: "taken-from", text: ["가져가라, 가져가. 쥐고 있어 봐야 마음만 찌푸려지지."] },
  { id: "temute-pair-discard", characterId: "temute", event: "pair-discard", text: ["짝 맞춰서 털었어. 이런 건 빨리 치워야 안 꼬이지."] },
  { id: "temute-emptied", characterId: "temute", event: "emptied", text: ["나 먼저 손 뗐네. …야, 너 방심하지 마라. 카드 잘 봐."] },
  { id: "traver-watching", characterId: "traver", event: "watching", text: ["보는 중. 욕심 안 부리고 자기 자리만 지키면 돼."] },
  { id: "traver-idle-draw", characterId: "traver", event: "idle-draw", text: ["한 장. 환승권 하나 챙겼다고 생각하면 돼."] },
  { id: "traver-taken-from", characterId: "traver", event: "taken-from", text: ["뽑아가라. 과욕 부리다간 지하 34층 꼴 나는 것뿐이야."] },
  { id: "traver-pair-discard", characterId: "traver", event: "pair-discard", text: ["짝 맞춰 버림. 짐이 무거우면 개찰구도 못 지나가."] },
  { id: "traver-emptied", characterId: "traver", event: "emptied", text: ["나 빠진다. 내 분수대로 딱 움직이니까 끝나는 거야."] },
  { id: "tumit-tu-watching", characterId: "tumit-tu", event: "watching", text: ["와, 이 긴장감! 거의 S랭크 구역 입구 수준인데요?!"] },
  { id: "tumit-tu-idle-draw", characterId: "tumit-tu", event: "idle-draw", text: ["한 장 획득! E랭크 헌터의 신중한 컨트롤이거든요!"] },
  { id: "tumit-tu-taken-from", characterId: "tumit-tu", event: "taken-from", text: ["가져가세요! E랭크 헌터는 이 정도 패로는 안 울거든요!"] },
  { id: "tumit-tu-pair-discard", characterId: "tumit-tu", event: "pair-discard", text: ["짝 맞췄어요! 봤죠?! 이게 E랭크의 기민함이에요!"] },
  { id: "tumit-tu-emptied", characterId: "tumit-tu", event: "emptied", text: ["저 패 다 털었어요! 집에 가서 누나한테 자랑할 거거든요!"] },
  { id: "anna-pair-made", characterId: "anna", event: "pair-made", text: ["짝 맞았어. …웃은 거야. 방금 나 기뻐서 웃은 거라고."] },
  { id: "anna-joker-drawn", characterId: "anna", event: "joker-drawn", text: ["이건 내가 쥐고 있을게. …뺏어온 거 아니야, 진짜야!"] },
  { id: "anna-joker-left", characterId: "anna", event: "joker-left", text: ["넘어갔다. …미안해. 이건 정말 사과하려는 거야."] },
  { id: "apollyon-pair-made", characterId: "apollyon", event: "pair-made", text: ["맞았군. …기뻐할 일인가. 하아."] },
  { id: "apollyon-joker-drawn", characterId: "apollyon", event: "joker-drawn", text: ["들어왔군. …뭐, 상관없다. 어차피 다 무의미하니."] },
  { id: "apollyon-joker-left", characterId: "apollyon", event: "joker-left", text: ["갔군. 하아… 잡고 늘어질 이유도 없지."] },
  { id: "bche-pair-made", characterId: "bche", event: "pair-made", text: ["오, 맞았네? 오늘 팔자라도 좀 풀렸나?"] },
  { id: "bche-joker-drawn", characterId: "bche", event: "joker-drawn", text: ["하, 또 나한테 오네. 내 팔자에 낀 고정 액운인가?"] },
  { id: "bche-joker-left", characterId: "bche", event: "joker-left", text: ["털었다! 이번 판은 살았네. 방세는 한 푼도 못 벌었지만."] },
  { id: "cicero-pair-made", characterId: "cicero", event: "pair-made", text: ["규격 일치다. 1급의 정밀도가 괜히 나오는 줄 아나?"] },
  { id: "cicero-joker-drawn", characterId: "cicero", event: "joker-drawn", text: ["…이건 구조적 결함이지 내 연산 오차가 아니다!"] },
  { id: "cicero-joker-left", characterId: "cicero", event: "joker-left", text: ["오류 요소 방출 완료. 하급자에게 넘어간 건 내 관할 밖이다."] },
  { id: "cradle-pair-made", characterId: "cradle", event: "pair-made", text: ["명중이다! 봤나, 이 몸의 거침없는 항해술을!"] },
  { id: "cradle-joker-drawn", characterId: "cradle", event: "joker-drawn", text: ["검은 깃발이 올랐군! …걱정 마라, 나쁜 파도는 선장이 맡는다."] },
  { id: "cradle-joker-left", characterId: "cradle", event: "joker-left", text: ["넘어갔다! 겁먹지 마라, 신참! 풍랑을 넘어야 진짜 사나이지!"] },
  { id: "diamo-pair-made", characterId: "diamo", event: "pair-made", text: ["맞췄어… 누군가 맘속으로 되게 기뻐했던 카드 같아."] },
  { id: "diamo-joker-drawn", characterId: "diamo", event: "joker-drawn", text: ["아… 잊혀진 카드구나. 아무도 찾지 않아서 나한테 왔나."] },
  { id: "diamo-joker-left", characterId: "diamo", event: "joker-left", text: ["떠나갔네. 잘 가… 이 묵직한 기억은 이제 누구 거가 될까."] },
  { id: "esther-pair-made", characterId: "esther", event: "pair-made", text: ["어머, 짝이 맞았네요. 둘이 외롭지 않게 같이 떠나서 다행이에요."] },
  { id: "esther-joker-drawn", characterId: "esther", event: "joker-drawn", text: ["기어이 저한테 오셨군요. …괜찮아요, 잠시 감싸 안고 있을게요."] },
  { id: "esther-joker-left", characterId: "esther", event: "joker-left", text: ["다른 분께 건너갔네요. 부디 상처 없이 잘 다스려지기를."] },
  { id: "hiro-pair-made", characterId: "hiro", event: "pair-made", text: ["멋지게 짝을 맞췄습니다! 이 정도는 해줘야 관객이 환호하지 않겠습니까!"] },
  { id: "hiro-joker-drawn", characterId: "hiro", event: "joker-drawn", text: ["위기는 영웅을 빛나게 만드는 법입니다!", "…근데 왜 맨날 나한테 꼬이냐."] },
  { id: "hiro-joker-left", characterId: "hiro", event: "joker-left", text: ["조용히 다음 분께 넘기겠습니다!", "…무대 뒤에서 털어버리는 게 최고지."] },
  { id: "katrinka-pair-made", characterId: "katrinka", event: "pair-made", text: ["딱 맞아떨어졌네. 이번 건 특별히 추가금 안 매길게."] },
  { id: "katrinka-joker-drawn", characterId: "katrinka", event: "joker-drawn", text: ["…위험물 품목이 들어왔네. 이거 보관료는 누가 지불할 건데?"] },
  { id: "katrinka-joker-left", characterId: "katrinka", event: "joker-left", text: ["너한테 넘겼어. 위험물 이관 수수료는 깔끔하게 퉁쳐 준다."] },
  { id: "kreva-pair-made", characterId: "kreva", event: "pair-made", text: ["동일 회로 대조 성공. 규격 일치."] },
  { id: "kreva-joker-drawn", characterId: "kreva", event: "joker-drawn", text: ["노이즈 개체 유입. 내부 바이패스 회로를 통한 빠른 배출 필요."] },
  { id: "kreva-joker-left", characterId: "kreva", event: "joker-left", text: ["노이즈 개체 이관 완료. 본체 담당 구역에서 제거됨."] },
  { id: "levillotte-pair-made", characterId: "levillotte", event: "pair-made", text: ["어머, 또 짝이 맞아버렸네? 행운의 여신이 나한테 올인 중이지!"] },
  { id: "levillotte-joker-drawn", characterId: "levillotte", event: "joker-drawn", text: ["…어라, 얘가 왜 나한테 오지? 뭐, 미소녀한테 생기는 가벼운 흠집 정도거든!"] },
  { id: "levillotte-joker-left", characterId: "levillotte", event: "joker-left", text: ["쏙 넘겨줬지! …야, 너 표정이 왜 그래? 딱히 걱정해서 물어보는 건 아니라고!"] },
  { id: "lilim-pair-made", characterId: "lilim", event: "pair-made", text: ["우와… 맞았어요! 저 잘한 건가요?"] },
  { id: "lilim-joker-drawn", characterId: "lilim", event: "joker-drawn", text: ["이건… 그림이 이상한데… 갖고 있으면 안 돼요?"] },
  { id: "lilim-joker-left", characterId: "lilim", event: "joker-left", text: ["어… 뽑아가셨어요? 저 이제 안 위험해요?"] },
  { id: "machina-pair-made", characterId: "machina", event: "pair-made", text: ["딱 맞았네. 미리 기름칠 잘해 둔 보람이 있어."] },
  { id: "machina-joker-drawn", characterId: "machina", event: "joker-drawn", text: ["위험 부품이 왔네. 괜찮아, 난 튼튼해서 견뎌."] },
  { id: "machina-joker-left", characterId: "machina", event: "joker-left", text: ["넘어갔어. …그건 교체 안 되는 부품이니까 조심해."] },
  { id: "nostalgia-pair-made", characterId: "nostalgia", event: "pair-made", text: ["짝을 맞추었네요. 아름다운 만남은 늘 축복으로 이어지죠."] },
  { id: "nostalgia-joker-drawn", characterId: "nostalgia", event: "joker-drawn", text: ["이 슬픔이 제게 찾아왔군요. 제가 따뜻하게 품어 줄게요."] },
  { id: "nostalgia-joker-left", characterId: "nostalgia", event: "joker-left", text: ["다른 품으로 떠났네요. 어디에 있든 사랑받아야 해요. …그래야만 해요."] },
  { id: "phaeo-pair-made", characterId: "phaeo", event: "pair-made", text: ["동일 수치 2장 일치. 오차 범위 내 정상 전개."] },
  { id: "phaeo-joker-drawn", characterId: "phaeo", event: "joker-drawn", text: ["위협 카드 입수. 누군가는 인수할 예정. 자연스러운 통계."] },
  { id: "phaeo-joker-left", characterId: "phaeo", event: "joker-left", text: ["위협 카드 타인 이관 완료. 대상의 버티기 한계 임박."] },
  { id: "temute-pair-made", characterId: "temute", event: "pair-made", text: ["하아, 딱 맞아떨어졌네. 가끔은 운도 좀 따라 줘야지."] },
  { id: "temute-joker-drawn", characterId: "temute", event: "joker-drawn", text: ["하아… 귀찮은 건 꼭 나한테 먼저 들어온다니까."] },
  { id: "temute-joker-left", characterId: "temute", event: "joker-left", text: ["휴, 넘겼다. 야, 너 그거 떨어뜨리지 말고 똑바로 쥐어."] },
  { id: "traver-pair-made", characterId: "traver", event: "pair-made", text: ["맞았네. 딱 내 몫만큼 들어온 것뿐이야."] },
  { id: "traver-joker-drawn", characterId: "traver", event: "joker-drawn", text: ["…이딴 건 내 분수 밖인데. 오독일 리 없어."] },
  { id: "traver-joker-left", characterId: "traver", event: "joker-left", text: ["털었다. 무거운 화물은 일찍 내려놓는 게 원칙이지."] },
  { id: "tumit-tu-pair-made", characterId: "tumit-tu", event: "pair-made", text: ["드디어 터졌다! 이게 바로 E랭크의 숨은 실력이에요!"] },
  { id: "tumit-tu-joker-drawn", characterId: "tumit-tu", event: "joker-drawn", text: ["어… 이건 S랭크급 시련 같은데요?! 너무 센 거 아닙니까?!"] },
  { id: "tumit-tu-joker-left", characterId: "tumit-tu", event: "joker-left", text: ["위기 탈출 성공! E랭크는 원래 발 빠르게 도망치거든요!"] },
] as const satisfies readonly OldMaidLine[];
