import { readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";

type Range = Readonly<{ min: number; max: number }>;
type TableId = "temerosa-old-maid" | "temerosa-match-pairs" | "temerosa-slot" | "indian-poker" | "temerosa-high-low" | "temerosa-five-card-draw";
type RosterRecord = Readonly<{
  id: string; series: "overture" | "root2" | "bestiaization" | "finale"; sourcePersonaKey: string;
  canonicalPersonKey: string; displayName: string; qualifiedName: string; role: "gambler" | "house" | "dealer" | "host";
  status: "confirmed" | "needs-confirmation"; releaseEligibility: "casino-ready" | "ledger-only" | "house-only" | "blocked" | "excluded";
  loreEvidence: readonly Readonly<{ key: string; contentSha256: string }>[];
}>;
type Roster = Readonly<{ contract: string; generatedAt: string; records: readonly RosterRecord[] }>;
type Profile = Readonly<{
  npcId: string; status: "active" | "inactive" | "needs-confirmation"; role: string; sourceLabel: string;
  evidenceRefs: readonly Readonly<{ series: string; loreItem: Readonly<{ entryIndex: number; label: string }>; sha256: string }>[];
  economy: Readonly<{ dailyIncomeRange: Range; casinoBudgetRateBps: number; settlementWindow: Readonly<{ timezone: "Asia/Seoul"; startMinute: number; endMinute: number }> }>;
  behavior: Readonly<{
    riskAppetite: number; stakeAggression: number; lossChasing: number; stopLossDiscipline: number; takeProfitDiscipline: number;
    visitsPerDay: Range; roundsPerVisit: Range; preferredTables: readonly TableId[]; gameSkills: Readonly<Record<TableId, number>>;
  }>;
}>;
type ProfileDocument = Readonly<{ contract: string; generatedFrom: Readonly<{ rosterContract: string }>; profiles: readonly Profile[] }>;

const rosterUrl = new URL("./temerosa-series-npc-roster.generated.json", import.meta.url);
const profilesUrl = new URL("./temerosa-series-casino-profiles.generated.json", import.meta.url);
const outputUrl = new URL("../../../cabinets/casino-ledger/src/temerosa-series-runtime.generated.ts", import.meta.url);
const roster = JSON.parse(await readFile(rosterUrl, "utf8")) as Roster;
const profileSet = JSON.parse(await readFile(profilesUrl, "utf8")) as ProfileDocument;
if (roster.contract !== "temerosa-series-npc-inventory/0.2" || profileSet.generatedFrom.rosterContract !== roster.contract) throw new Error("series_runtime_contract_mismatch");

const profileById = new Map(profileSet.profiles.map((profile) => [profile.npcId, profile]));
const records = roster.records.filter((record) => record.role === "gambler" && record.status === "confirmed"
  && (record.releaseEligibility === "casino-ready" || record.releaseEligibility === "ledger-only")
  && profileById.get(record.id)?.status === "active" && profileById.get(record.id)?.role === "gambler");
const overrides = Object.fromEntries(records.map((record) => {
  const profile = profileById.get(record.id);
  if (!profile || profile.status !== "active" || profile.role !== "gambler") throw new Error(`series_runtime_profile_unavailable:${record.id}`);
  return [record.id, authoredProfile(profile)];
}));
const seatIds = records.filter((record) => record.releaseEligibility === "casino-ready").map((record) => record.id);
const runtimeRecords = records.map((record) => ({
  id: record.id, series: record.series, sourcePersonaKey: record.sourcePersonaKey, canonicalPersonKey: record.canonicalPersonKey,
  displayName: record.displayName, qualifiedName: record.qualifiedName, role: record.role, status: record.status,
  loreEvidence: record.loreEvidence.map((evidence) => ({ key: evidence.key, contentSha256: evidence.contentSha256 })),
}));

const source = `/* This file is generated by apps/content-cli/src/generate-temerosa-series-runtime.ts. */\n`
  + `import type { TemerosaFlowAuthoredProfile, TemerosaFlowRosterRecord } from "./temerosa-flow-profiles.ts";\n\n`
  + `export const TEMEROSA_SERIES_RUNTIME_ROSTER: readonly TemerosaFlowRosterRecord[] = Object.freeze(${JSON.stringify(runtimeRecords, null, 2)});\n\n`
  + `export const TEMEROSA_SERIES_AUTHORED_PROFILES: Readonly<Record<string, Readonly<TemerosaFlowAuthoredProfile>>> = Object.freeze(${JSON.stringify(overrides, null, 2)});\n\n`
  + `export const TEMEROSA_SERIES_CASINO_SEAT_IDS: readonly string[] = Object.freeze(${JSON.stringify(seatIds, null, 2)});\n`
  + `export const TEMEROSA_SERIES_RUNTIME_SOURCE = Object.freeze({ rosterContract: ${JSON.stringify(roster.contract)}, profileContract: ${JSON.stringify(profileSet.contract)}, identityRule: "series-and-source-persona", ledgerProfiles: ${records.length}, casinoSeats: ${seatIds.length} } as const);\n`;
await writeFile(outputUrl, source, "utf8");
console.log(`Wrote ${records.length} ledger profiles and ${seatIds.length} casino seats to ${fileURLToPath(outputUrl)}`);

function authoredProfile(profile: Profile): object {
  const behavior = profile.behavior;
  const risk = ratio(behavior.riskAppetite), stopDiscipline = ratio(behavior.stopLossDiscipline), takeDiscipline = ratio(behavior.takeProfitDiscipline);
  const preferredTables = behavior.preferredTables.map((tableId, index) => ({ tableId, weight: behavior.preferredTables.length - index + 2 }));
  const visitsPerDay = positiveRange(behavior.visitsPerDay);
  const roundsPerVisit = positiveRange(behavior.roundsPerVisit);
  const incomeRange = [profile.economy.dailyIncomeRange.min, profile.economy.dailyIncomeRange.max] as const;
  const evidenceRefs = profile.evidenceRefs.map((evidence) => `${evidence.series}:${evidence.loreItem.entryIndex}:${evidence.loreItem.label}:${evidence.sha256}`);
  return {
    gambling: {
      target: 0, riskAppetite: risk, discipline: round((stopDiscipline + takeDiscipline) / 2), lossChasing: ratio(behavior.lossChasing),
      winPressing: ratio(behavior.stakeAggression), stopLossRatio: round(.65 - stopDiscipline * .4), takeProfitRatio: round(.75 - takeDiscipline * .45),
      maxExposureRatio: round(.12 + risk * .32), incomeBand: incomeBand(incomeRange), payCycleDays: 7, paydayOffset: 0,
      skills: {
        oldMaid: ratio(behavior.gameSkills["temerosa-old-maid"]), matchPairsMemory: ratio(behavior.gameSkills["temerosa-match-pairs"]),
        pokerRead: ratio(behavior.gameSkills["indian-poker"]), pokerBluff: ratio(behavior.gameSkills["temerosa-five-card-draw"]),
        highLowJudgment: ratio(behavior.gameSkills["temerosa-high-low"]),
      },
      sessionsPerDay: visitsPerDay, tables: preferredTables,
      activeHours: [{ startMinute: profile.economy.settlementWindow.startMinute, endMinute: profile.economy.settlementWindow.endMinute, weight: 1 }],
    },
    income: {
      sourceLabel: profile.sourceLabel, evidenceRefs, dailyIncomeRange: incomeRange,
      casinoBudgetRateBps: [profile.economy.casinoBudgetRateBps, profile.economy.casinoBudgetRateBps], openingExternalReserve: 0,
      settlementWindow: [
        Math.min(1_439, profile.economy.settlementWindow.startMinute),
        Math.min(1_439, profile.economy.settlementWindow.endMinute),
      ],
    },
    behavior: {
      riskAppetite: risk, stakeAggression: ratio(behavior.stakeAggression), lossChasing: ratio(behavior.lossChasing),
      stopLossDiscipline: stopDiscipline, takeProfitDiscipline: takeDiscipline, visitsPerDay,
      roundsPerVisit,
      skills: Object.fromEntries(Object.entries(behavior.gameSkills).map(([tableId, value]) => [tableId, ratio(value)])),
      preferredTables,
    },
  };
}

function ratio(value: number): number { if (!Number.isSafeInteger(value) || value < 0 || value > 10_000) throw new Error("series_runtime_invalid_bps"); return round(value / 10_000); }
function round(value: number): number { return Number(value.toFixed(4)); }
function positiveRange(range: Range): Range {
  const min = Math.max(1, range.min);
  return { min, max: Math.max(min, range.max) };
}
function incomeBand([minimum, maximum]: readonly [number, number]): "low" | "middle" | "high" | "premium" {
  const midpoint = (minimum + maximum) / 2;
  return midpoint < 100 ? "low" : midpoint < 200 ? "middle" : midpoint < 320 ? "high" : "premium";
}
