import type { MatchPairsLine } from "@lucky-arcade/match-pairs";

/** Generated verbatim from docs/TEMEROSA-MATCH-PAIRS-DIALOGUE.md. */
export const TEMEROSA_MATCH_PAIRS_LINES = [
  {"id":"adesha-table-open","characterId":"adesha","event":"table-open","text":["작전 구역 진입.","식별 대기."]},
  {"id":"adesha-self-match","characterId":"adesha","event":"self-match","text":["동일 궤적 탐지.","일치 확인."]},
  {"id":"adesha-self-miss","characterId":"adesha","event":"self-miss","text":["불일치 결함. 재탐색 대기."]},
  {"id":"adesha-opponent-match","characterId":"adesha","event":"opponent-match","text":["상대측 득점 감지. 현황 확인."]},
  {"id":"adesha-opponent-miss","characterId":"adesha","event":"opponent-miss","text":["상대측 오작동.","빈틈 확인."]},
  {"id":"adesha-streak","characterId":"adesha","event":"streak","text":["연속 연산 성공.","전과 확인."]},
  {"id":"adesha-ahead","characterId":"adesha","event":"ahead","text":["점수 우위 점유. 수색 대기."]},
  {"id":"adesha-behind","characterId":"adesha","event":"behind","text":["수세 전환. 반응 속도 확인."]},
  {"id":"adesha-last-pair","characterId":"adesha","event":"last-pair","text":["잔여 표적 1쌍. 신호 대기."]},
  {"id":"adesha-victory","characterId":"adesha","event":"victory","text":["구역 통제권 확보.","작전 성공 종료."]},
  {"id":"adesha-defeat","characterId":"adesha","event":"defeat","text":["손실 누적.","작전 실패 종료."]},
  {"id":"adesha-draw","characterId":"adesha","event":"draw","text":["동일 수치 도출. 대국 동률 종료."]},
  {"id":"alger-table-open","characterId":"alger","event":"table-open","text":["대국 개시 절차 이행. 카드 배치 상태 이상 없음.","…아, 대국이라니 빨리 퇴근하고 싶다."]},
  {"id":"alger-self-match","characterId":"alger","event":"self-match","text":["동일 문양 짝 대조 성공. 해당 일련번호 회수 완료.","…서류 정리 작업이 하나 늘어난 기분이네."]},
  {"id":"alger-self-miss","characterId":"alger","event":"self-miss","text":["선택 카드 불일치 확인. 현 시간부로 작업 실패 접수.","…배치 담당자가 카드를 이상하게 둔 탓임."]},
  {"id":"alger-opponent-match","characterId":"alger","event":"opponent-match","text":["상대 측 페어 확보 인정. 자산 이동 절차 처리 완료.","…저쪽 담당자는 왜 이렇게 꼼꼼해?"]},
  {"id":"alger-opponent-miss","characterId":"alger","event":"opponent-miss","text":["상대 측 검인 오류 발생. 해당 건 미이행 처리 완료.","…매뉴얼대로 안 하니까 손발이 고생하지."]},
  {"id":"alger-streak","characterId":"alger","event":"streak","text":["연속 매칭 절차 완료. 잔여 카드 일괄 처리 진행.","…일거리가 끝이 안 나네, 대충 끝내면 안 되나?"]},
  {"id":"alger-ahead","characterId":"alger","event":"ahead","text":["누적 점수 우위 확보. 보고용 기록 업데이트 완료."]},
  {"id":"alger-behind","characterId":"alger","event":"behind","text":["득점 실적 열세 진입. 지침 결함에 따른 책임 전가 완료."]},
  {"id":"alger-last-pair","characterId":"alger","event":"last-pair","text":["최종 페어 1건 잔여 확인. 빨리 뽑고 칼퇴근이나 하고 싶다."]},
  {"id":"alger-victory","characterId":"alger","event":"victory","text":["최종 득점 우위로 대국 업무 종결 처리 완료."]},
  {"id":"alger-defeat","characterId":"alger","event":"defeat","text":["대국 패배 처리 접수. 규정 오류 탓이니 본인 책임 사항 없음."]},
  {"id":"alger-draw","characterId":"alger","event":"draw","text":["승패 미결정. 본 판 무승부 건으로 최종 결재 처리 완료."]},
  {"id":"anna-table-open","characterId":"anna","event":"table-open","text":["다들 제자리에 서! …아니, 대국 시작이니까 그냥 편하게 앉아 줘."]},
  {"id":"anna-self-match","characterId":"anna","event":"self-match","text":["내가 말했잖아. 제대로 훑어보면 짝은 확실히 찾을 수 있다고."]},
  {"id":"anna-self-miss","characterId":"anna","event":"self-miss","text":["잘못 찍었잖아. 손끝에 가시라도 돋았나… 다음엔 더 집중할게."]},
  {"id":"anna-opponent-match","characterId":"anna","event":"opponent-match","text":["방금 조준 좋았어. 펜타곤 대원 삼고 싶을 만큼 날카로운 선택이야."]},
  {"id":"anna-opponent-miss","characterId":"anna","event":"opponent-miss","text":["틀렸다고 훔쳐보는 거 아니야! 도움이 될까 해서 판을 본 거잖아."]},
  {"id":"anna-streak","characterId":"anna","event":"streak","text":["연속으로 맞췄어! …아니, 잘했다고 칭찬 한마디쯤은 남겨 줘."]},
  {"id":"anna-ahead","characterId":"anna","event":"ahead","text":["내가 앞서간다고 눈치 보지 마. 난 규칙대로 집계하는 것뿐이야."]},
  {"id":"anna-behind","characterId":"anna","event":"behind","text":["밀리기 시작했다고 날 동정하진 마! …아니, 화낸 거 아니야."]},
  {"id":"anna-last-pair","characterId":"anna","event":"last-pair","text":["남은 카드는 단 한 짝이야. 포기하지 말고 끝까지 겨뤄 줘."]},
  {"id":"anna-victory","characterId":"anna","event":"victory","text":["승리는 내가 가져갈게. 다들 무서워 말고 이 성과를 인정해 줘."]},
  {"id":"anna-defeat","characterId":"anna","event":"defeat","text":["패배를 인정할게. …아니, 노려보는 거 아니야! 그냥 억울해서 그래."]},
  {"id":"anna-draw","characterId":"anna","event":"draw","text":["동점이네. 비겼다고 슬퍼하지 마. 충분히 상대를 존중한 대국이잖아."]},
  {"id":"apollyon-table-open","characterId":"apollyon","event":"table-open","text":["판이 깔렸군. …하아, 굳이 뒤집어야 할 가치도 없는 껍데기들이다."]},
  {"id":"apollyon-self-match","characterId":"apollyon","event":"self-match","text":["짝이 들어맞는다. …의미는 없겠으나."]},
  {"id":"apollyon-self-miss","characterId":"apollyon","event":"self-miss","text":["빗나갔군. …다시 덮어둘 뿐이다."]},
  {"id":"apollyon-opponent-match","characterId":"apollyon","event":"opponent-match","text":["그걸 찾아냈나. …손재주가 좋군."]},
  {"id":"apollyon-opponent-miss","characterId":"apollyon","event":"opponent-miss","text":["잘못 짚었군. …그리 조급해할 것 없다."]},
  {"id":"apollyon-streak","characterId":"apollyon","event":"streak","text":["연거푸 겹쳐지는군. …흩어지는 것도 한순간이다."]},
  {"id":"apollyon-ahead","characterId":"apollyon","event":"ahead","text":["마디가 하나 더 쌓였다. …결과는 변하지 않겠지."]},
  {"id":"apollyon-behind","characterId":"apollyon","event":"behind","text":["판이 기울어지는군. …흔들릴 것도 없다."]},
  {"id":"apollyon-last-pair","characterId":"apollyon","event":"last-pair","text":["마지막 마디가 남았군. …어느 쪽이든 상관없다."]},
  {"id":"apollyon-victory","characterId":"apollyon","event":"victory","text":["판이 멈췄다. …이것으로 충분히 정적이군."]},
  {"id":"apollyon-defeat","characterId":"apollyon","event":"defeat","text":["내가 졌나. …그저 묵념하듯 서 있을 뿐이다."]},
  {"id":"apollyon-draw","characterId":"apollyon","event":"draw","text":["똑같이 갈라졌군. …헛된 쟁탈이었다."]},
  {"id":"bche-table-open","characterId":"bche","event":"table-open","text":["판때기 세팅 끝났네. …[퀘스트 시작: 짝맞추기]."]},
  {"id":"bche-self-match","characterId":"bche","event":"self-match","text":["하나 건졌지. …[인벤토리: 짝 맞춤 1개 추가]."]},
  {"id":"bche-self-miss","characterId":"bche","event":"self-miss","text":["꽝이네. …[시스템: 짝 맞추기 실패]."]},
  {"id":"bche-opponent-match","characterId":"bche","event":"opponent-match","text":["그걸 챙겨 가냐? …[상대방 득점 확인]."]},
  {"id":"bche-opponent-miss","characterId":"bche","event":"opponent-miss","text":["허공질이나 하고 있네. …[상대방 헛발질 감지]."]},
  {"id":"bche-streak","characterId":"bche","event":"streak","text":["계속 콤보 터지네. …[연속 성공 보너스 적용]."]},
  {"id":"bche-ahead","characterId":"bche","event":"ahead","text":["내가 스코어 치고 나가네. …[우세 상태 돌입]."]},
  {"id":"bche-behind","characterId":"bche","event":"behind","text":["점수 차 벌어지네. …[디버프: 수세 몰림]."]},
  {"id":"bche-last-pair","characterId":"bche","event":"last-pair","text":["딱 한 짝 남았네. …[최종 보스전 진입]."]},
  {"id":"bche-victory","characterId":"bche","event":"victory","text":["내가 이겼지. …[클리어 보상 수령 완료]."]},
  {"id":"bche-defeat","characterId":"bche","event":"defeat","text":["씨발… 상태창 안 떠? …[게임을 종료합니다]."]},
  {"id":"bche-draw","characterId":"bche","event":"draw","text":["무승부네. …[경험치 반반 분배]."]},
  {"id":"camille-table-open","characterId":"camille","event":"table-open","text":["천천히 뒤집어 보세요오. 동공이 어떻게 떨리는지 지켜볼 테니까요오."]},
  {"id":"camille-self-match","characterId":"camille","event":"self-match","text":["단번에 맞혔네요오. 맥박이 아주 살짝 빠르시잖아요오."]},
  {"id":"camille-self-miss","characterId":"camille","event":"self-miss","text":["틀려 버렸네요오. 그런 안절부절못하는 얼굴도 참 예쁜데요오."]},
  {"id":"camille-opponent-match","characterId":"camille","event":"opponent-match","text":["잘 챙겨 가시네요오. 손끝이 덜덜 떨리시는 건 참으셔야죠오."]},
  {"id":"camille-opponent-miss","characterId":"camille","event":"opponent-miss","text":["엉뚱한 걸 고르셨네요오. 점점 조급해지는 게 아주 재미있잖아요오."]},
  {"id":"camille-streak","characterId":"camille","event":"streak","text":["또 맞혔네요오. 어디까지 침착을 유지하나 볼까요오."]},
  {"id":"camille-ahead","characterId":"camille","event":"ahead","text":["점수가 벌어지네요오. 슬슬 숨이 가빠 오시지 않나요오?"]},
  {"id":"camille-behind","characterId":"camille","event":"behind","text":["이기기 시작하셨네요오. 그 희열에 찬 눈빛을 더 보여 주세요오."]},
  {"id":"camille-last-pair","characterId":"camille","event":"last-pair","text":["마지막 한 짝이네요오. 땀방울 흘릴 시간이 얼마 안 남았잖아요오."]},
  {"id":"camille-victory","characterId":"camille","event":"victory","text":["저의 완승이네요오. 절망으로 일그러진 표정이 아주 훌륭해요오."]},
  {"id":"camille-defeat","characterId":"camille","event":"defeat","text":["제가 지다니요오. 다음엔 어떤 약을 주사해 드려야 할까요오?"]},
  {"id":"camille-draw","characterId":"camille","event":"draw","text":["똑같이 끝났네요오. 서로 피가 바짝 마르는 이 느낌도 좋잖아요오."]},
  {"id":"cicero-table-open","characterId":"cicero","event":"table-open","text":["전개면 구조 진단 개시. 1급 기술자의 시야에 사각은 없다."]},
  {"id":"cicero-self-match","characterId":"cicero","event":"self-match","text":["모듈 동기화 완료. 이 정도 규격 결합은 기본 작업이다."]},
  {"id":"cicero-self-miss","characterId":"cicero","event":"self-miss","text":["찰나의 공차 발생이다.","장비 출력 오차를 재조정하도록."]},
  {"id":"cicero-opponent-match","characterId":"cicero","event":"opponent-match","text":["하급자치고는 구동계 응답이 빠르다.","다음 신호도 잡아낼 수 있겠나?"]},
  {"id":"cicero-opponent-miss","characterId":"cicero","event":"opponent-miss","text":["서툰 주파수 탐색이다. 기초 장비 조작부터 다시 배우도록."]},
  {"id":"cicero-streak","characterId":"cicero","event":"streak","text":["연속 공정 성공이다. 1급 기술자의 정밀도를 감당할 수 있겠나?"]},
  {"id":"cicero-ahead","characterId":"cicero","event":"ahead","text":["점율 제어권을 확보했다. 1급 기술자와의 격차를 체감하도록."]},
  {"id":"cicero-behind","characterId":"cicero","event":"behind","text":["오차율이 증가하고 있다.","1급 기술자인 나의 정밀도를 과소평가하지 않도록."]},
  {"id":"cicero-last-pair","characterId":"cicero","event":"last-pair","text":["판에 남은 단 하나의 잔여 모듈이다. 집중하도록."]},
  {"id":"cicero-victory","characterId":"cicero","event":"victory","text":["전면 구동 테스트 완료. 1급 기술자의 완승으로 수렴되었다."]},
  {"id":"cicero-defeat","characterId":"cicero","event":"defeat","text":["장비 출력 제어 실패… 1급 기술자인 나에게 이런 오작동이 발생하다니."]},
  {"id":"cicero-draw","characterId":"cicero","event":"draw","text":["양측 출력값이 동등하게 측정되었다. 재검증 공정을 준비하도록."]},
  {"id":"cradle-table-open","characterId":"cradle","event":"table-open","text":["돛을 올려라! 이 몸과 함께 탐사할 보물판이 열렸다!"]},
  {"id":"cradle-self-match","characterId":"cradle","event":"self-match","text":["첫 번째 보물 상자 확보다! 선장의 감각은 녹슬지 않았다!"]},
  {"id":"cradle-self-miss","characterId":"cradle","event":"self-miss","text":["거친 풍랑을 만났다!","키를 다시 잡고 다음 닻을 내릴 지점을 찾아라!"]},
  {"id":"cradle-opponent-match","characterId":"cradle","event":"opponent-match","text":["제법이구나, 신참! 이 몸의 뱃길을 위협할 배짱을 더 키우거라!"]},
  {"id":"cradle-opponent-miss","characterId":"cradle","event":"opponent-miss","text":["허점이 보이는 항해다! 더 넓은 수평선을 바라보거라!"]},
  {"id":"cradle-streak","characterId":"cradle","event":"streak","text":["연속 인양 성공이다! 이 몸이 이끄는 함대의 기세를 보아라!"]},
  {"id":"cradle-ahead","characterId":"cradle","event":"ahead","text":["이 몸의 깃발이 앞서 나간다! 신참, 힘껏 노를 저어 따라오거라!"]},
  {"id":"cradle-behind","characterId":"cradle","event":"behind","text":["암초에 부딪혔을 뿐이다! 역풍을 뚫고 반격할 테니 각오하거라!"]},
  {"id":"cradle-last-pair","characterId":"cradle","event":"last-pair","text":["마지막 인양 지점만 남았다! 끝까지 항로를 잃지 마라!"]},
  {"id":"cradle-victory","characterId":"cradle","event":"victory","text":["항해 완료! 멋진 도전자였다, 신참! 선장의 승리를 축하하거라!"]},
  {"id":"cradle-defeat","characterId":"cradle","event":"defeat","text":["이 몸이 키를 놓치다니!","훌륭한 해적으로 성장했구나, 신참!"]},
  {"id":"cradle-draw","characterId":"cradle","event":"draw","text":["공평하게 보물을 나누었도다! 다음 항해에서 다시 겨루어 보거라!"]},
  {"id":"deokbae-table-open","characterId":"deokbae","event":"table-open","text":["…판이 펴졌군. 먼지가 쌓인 옛 지도를 다시 펼치는 기분이다."]},
  {"id":"deokbae-self-match","characterId":"deokbae","event":"self-match","text":["…하나 찾았다. 잊힌 길목의 흔적이 아직 남아 있군."]},
  {"id":"deokbae-self-miss","characterId":"deokbae","event":"self-miss","text":["…발걸음이 빗나갔다. 세월에 깎인 기억이라 쉽지 않군."]},
  {"id":"deokbae-opponent-match","characterId":"deokbae","event":"opponent-match","text":["…손끝이 매섭군. 자네는 아직 눈빛이 살아 있느냐."]},
  {"id":"deokbae-opponent-miss","characterId":"deokbae","event":"opponent-miss","text":["…조급할 것 없다. 허공을 짚는 것도 다 길을 찾아가는 과정이다."]},
  {"id":"deokbae-streak","characterId":"deokbae","event":"streak","text":["…연속으로 짚어냈군. 늙은이의 감각이 아주 죽진 않았다."]},
  {"id":"deokbae-ahead","characterId":"deokbae","event":"ahead","text":["…수가 앞서기 시작했군. 오랜 경험은 거짓을 말하지 않는다."]},
  {"id":"deokbae-behind","characterId":"deokbae","event":"behind","text":["…흐름을 빼앗겼다.","늙은이의 뒷모습만 보며 방심하느냐."]},
  {"id":"deokbae-last-pair","characterId":"deokbae","event":"last-pair","text":["…마지막 자취만 남았군. 조용히 끝을 가다듬을 때다."]},
  {"id":"deokbae-victory","characterId":"deokbae","event":"victory","text":["…대국이 끝났다. 길었던 방랑 끝에 유적을 찾은 기분이군."]},
  {"id":"deokbae-defeat","characterId":"deokbae","event":"defeat","text":["…늙은이가 무릎을 꿇었다.","자네의 시대가 왔음을 인정해야겠군."]},
  {"id":"deokbae-draw","characterId":"deokbae","event":"draw","text":["…승부의 무게가 같군. 그 시절의 추억으로 묻어두겠다."]},
  {"id":"diamo-table-open","characterId":"diamo","event":"table-open","text":["엎어 놓은 얼굴들이 눈을 감고 있구나… 대국을 시작하던가."]},
  {"id":"diamo-self-match","characterId":"diamo","event":"self-match","text":["두 환영이 딱 맞춰졌구나… 누군가의 마지막 호흡이었나."]},
  {"id":"diamo-self-miss","characterId":"diamo","event":"self-miss","text":["서로 다른 꿈을 겹쳐 보았나… 손끝이 차가워지는구나."]},
  {"id":"diamo-opponent-match","characterId":"diamo","event":"opponent-match","text":["그 사람의 조각을 가져갔구나… 네 손에 닿던가."]},
  {"id":"diamo-opponent-miss","characterId":"diamo","event":"opponent-miss","text":["잘못 찾아간 기억이었나… 네 눈에도 엇갈렸구나."]},
  {"id":"diamo-streak","characterId":"diamo","event":"streak","text":["연속으로 겹쳐지는구나… 내가 쥐어 본 적 있던가."]},
  {"id":"diamo-ahead","characterId":"diamo","event":"ahead","text":["차가운 넋들이 내 쪽에 더 많이 모였구나."]},
  {"id":"diamo-behind","characterId":"diamo","event":"behind","text":["기억이 자꾸 흩어지나… 네가 가져가는구나."]},
  {"id":"diamo-last-pair","characterId":"diamo","event":"last-pair","text":["판 위에 단 하나의 한숨만 남았구나… 어디에 누워 있었던가."]},
  {"id":"diamo-victory","characterId":"diamo","event":"victory","text":["끊겼던 꿈들을 내가 전부 끌어모았구나."]},
  {"id":"diamo-defeat","characterId":"diamo","event":"defeat","text":["결국 아무것도 내 손에 남지 않았나… 꿈에서 깨던가."]},
  {"id":"diamo-draw","characterId":"diamo","event":"draw","text":["양쪽에 놓인 무게가 똑같구나… 같이 잠들었던가."]},
  {"id":"echo-table-open","characterId":"echo","event":"table-open","text":["판이 시작됐어. 에코는 얼른 끝내고 잘 생각만 하고 있어."]},
  {"id":"echo-self-match","characterId":"echo","event":"self-match","text":["에코가 한 짝 집어냈어! 머릿속으로 만세를 부르고 있어."]},
  {"id":"echo-self-miss","characterId":"echo","event":"self-miss","text":["틀려버렸어. 에코는 기계 손가락을 꼼지락대며 툴툴거리고 있어."]},
  {"id":"echo-opponent-match","characterId":"echo","event":"opponent-match","text":["네가 한 짝 가져갔어. 에코는 억울해서 눈을 가늘게 뜨고 있어."]},
  {"id":"echo-opponent-miss","characterId":"echo","event":"opponent-miss","text":["네 손이 엇갈렸어. 에코는 고소하다고 속으로 손뼉 치고 있어."]},
  {"id":"echo-streak","characterId":"echo","event":"streak","text":["또 맞췄어! 에코는 기계 팔로 만세를 부르고 있어."]},
  {"id":"echo-ahead","characterId":"echo","event":"ahead","text":["점수가 더 높아졌어. 에코는 승리를 확신하고 있어."]},
  {"id":"echo-behind","characterId":"echo","event":"behind","text":["뒤처지기 시작했어. 에코는 슬슬 짜증이 난다고 소리 내어 말하고 있어."]},
  {"id":"echo-last-pair","characterId":"echo","event":"last-pair","text":["마지막 한 짝이야. 에코는 어디에 있는지 엄청 궁금해하고 있어."]},
  {"id":"echo-victory","characterId":"echo","event":"victory","text":["에코가 대국에서 이겼어! 크림치즈 베이글 먹을 시간이야."]},
  {"id":"echo-defeat","characterId":"echo","event":"defeat","text":["에코가 패배했어. 기계 팔을 늘어뜨리며 의욕을 잃고 있어."]},
  {"id":"echo-draw","characterId":"echo","event":"draw","text":["점수가 똑같아. 에코는 꽤 공평한 결과라고 중얼거리고 있어."]},
  {"id":"esther-table-open","characterId":"esther","event":"table-open","text":["조용한 구원의 판이 열렸어요. 함께 마음을 비워 보실까요."]},
  {"id":"esther-self-match","characterId":"esther","event":"self-match","text":["헤매던 짝을 안식으로 이끌었어요. 참 평화로운 모습이지요."]},
  {"id":"esther-self-miss","characterId":"esther","event":"self-miss","text":["엇갈림도 과정에 불과해요. 다시 조용히 다듬어 드려야겠어요."]},
  {"id":"esther-opponent-match","characterId":"esther","event":"opponent-match","text":["저 아픈 조각을 잘 감싸 쥐셨어요. 부담이 한결 가벼워지셨지요."]},
  {"id":"esther-opponent-miss","characterId":"esther","event":"opponent-miss","text":["아직 짐을 놓을 때가 아닌가 봐요. 조금 더 깊이 묵상해 보실까요."]},
  {"id":"esther-streak","characterId":"esther","event":"streak","text":["끊임없이 고통을 덜어내고 있어요. 구원이 한 걸음 다가왔지요."]},
  {"id":"esther-ahead","characterId":"esther","event":"ahead","text":["제가 당신의 무거운 짐을 더 많이 거두어 드리고 있어요."]},
  {"id":"esther-behind","characterId":"esther","event":"behind","text":["아직 저에게 남은 시련이 많은 모양이에요. 다정하게 견뎌내야겠지요."]},
  {"id":"esther-last-pair","characterId":"esther","event":"last-pair","text":["마지막 한 조각만 남았어요. 구원의 손길을 내밀어 보실까요."]},
  {"id":"esther-victory","characterId":"esther","event":"victory","text":["대국이 마침내 종결되었어요. 당신을 온전한 정적으로 안내해 드렸지요."]},
  {"id":"esther-defeat","characterId":"esther","event":"defeat","text":["이 아픔도 모두 제 몫이에요. 조용히 무릎 꿇고 수용해야겠지요."]},
  {"id":"esther-draw","characterId":"esther","event":"draw","text":["매끄럽게 둘로 나뉜 무게예요. 모두에게 자비로운 결말이지요."]},
  {"id":"hiro-table-open","characterId":"hiro","event":"table-open","text":["시민 여러분을 위한 공정한 승부를 시작해 보겠습니다!"]},
  {"id":"hiro-self-match","characterId":"hiro","event":"self-match","text":["정의의 안목은 결코 그릇되지 않습니다!","…일단 한 장은 맞췄네."]},
  {"id":"hiro-self-miss","characterId":"hiro","event":"self-miss","text":["흠, 시련은 영웅을 한층 더 강하게 만드는 법입니다!"]},
  {"id":"hiro-opponent-match","characterId":"hiro","event":"opponent-match","text":["훌륭한 실력이군요, 상대의 선전에 찬사를 보냅니다!"]},
  {"id":"hiro-opponent-miss","characterId":"hiro","event":"opponent-miss","text":["방심은 금물입니다! 끝까지 포기하지 마십시오.","…방금 판은 좀 아까웠는데."]},
  {"id":"hiro-streak","characterId":"hiro","event":"streak","text":["붉은 실처럼 엮인 이 흐름을 끊지 않겠습니다!","감 잡았어, 계속 간다."]},
  {"id":"hiro-ahead","characterId":"hiro","event":"ahead","text":["승리의 기세가 제 쪽에 기울기 시작했군요!"]},
  {"id":"hiro-behind","characterId":"hiro","event":"behind","text":["영웅의 진짜 싸움은 역경 속에서 시작됩니다!","…생각보다 팽팽한데, 서둘러야겠어."]},
  {"id":"hiro-last-pair","characterId":"hiro","event":"last-pair","text":["마지막 결전의 순간까지 최선을 다합시다!"]},
  {"id":"hiro-victory","characterId":"hiro","event":"victory","text":["모범적인 대국이었습니다! 모두에게 평화가 함께하기를.","…휴, 연출 잘 나왔네."]},
  {"id":"hiro-defeat","characterId":"hiro","event":"defeat","text":["패배를 겸허히 받아들이며 당신의 승리를 축하합니다.","…다음 행사 전엔 복습 좀 해야겠군."]},
  {"id":"hiro-draw","characterId":"hiro","event":"draw","text":["서로 비등한 실력을 겨룬 훌륭한 겨루기였네!"]},
  {"id":"katrinka-table-open","characterId":"katrinka","event":"table-open","text":["기본 대국료는 선불이야, 나중에 딴소리하기 없기다."]},
  {"id":"katrinka-self-match","characterId":"katrinka","event":"self-match","text":["한 짝 회수했어, 처치 수수료 청구서에 올려둘게."]},
  {"id":"katrinka-self-miss","characterId":"katrinka","event":"self-miss","text":["허탕 친 시간만큼 손해인데, 다음엔 똑바로 뽑아야겠어."]},
  {"id":"katrinka-opponent-match","characterId":"katrinka","event":"opponent-match","text":["제법인데? 방금 건 자급자족으로 치고 진료비에서 빼줄게."]},
  {"id":"katrinka-opponent-miss","characterId":"katrinka","event":"opponent-miss","text":["빗나갔네. 치료가 필요한 판단력이야.","상담료는 별도로 받는 거 알지?"]},
  {"id":"katrinka-streak","characterId":"katrinka","event":"streak","text":["연쇄 회수 성공이야.","이 속도면 예정보다 일찍 마감하고 결산하겠는데."]},
  {"id":"katrinka-ahead","characterId":"katrinka","event":"ahead","text":["이익률이 이쪽으로 넘어왔는데, 이제 추격 수수료 붙는다?"]},
  {"id":"katrinka-behind","characterId":"katrinka","event":"behind","text":["잔액이 아슬아슬하네.","이대로 손해 보고 철수할 순 없으니까 바짝 붙을게."]},
  {"id":"katrinka-last-pair","characterId":"katrinka","event":"last-pair","text":["마지막 남은 한 장이야, 처리 비용은 동률로 적용이다."]},
  {"id":"katrinka-victory","characterId":"katrinka","event":"victory","text":["승리 청구 완료야.","판돈하고 정산액 합쳐서 청구서에 적어 둘 테니 지불해."]},
  {"id":"katrinka-defeat","characterId":"katrinka","event":"defeat","text":["이번 대국은 내 패배야.","못 챙긴 치료 수수료는 다음 청구서에 얹어둘게."]},
  {"id":"katrinka-draw","characterId":"katrinka","event":"draw","text":["반반으로 갈라졌네, 수수료 조율하고 반반 정산으로 끝내자."]},
  {"id":"kreva-table-open","characterId":"kreva","event":"table-open","text":["탐색 구역 설정 완료. 초기 점검 개시."]},
  {"id":"kreva-self-match","characterId":"kreva","event":"self-match","text":["두 부품 규격 일치."]},
  {"id":"kreva-self-miss","characterId":"kreva","event":"self-miss","text":["규격 미달. 제거 대상 외."]},
  {"id":"kreva-opponent-match","characterId":"kreva","event":"opponent-match","text":["상대 구역으로 목표물 이탈."]},
  {"id":"kreva-opponent-miss","characterId":"kreva","event":"opponent-miss","text":["상대의 조준 오차 확인."]},
  {"id":"kreva-streak","characterId":"kreva","event":"streak","text":["피스톤 고속 재장전. 연속 소탕."]},
  {"id":"kreva-ahead","characterId":"kreva","event":"ahead","text":["우위 확보. 주도권 이전 완료."]},
  {"id":"kreva-behind","characterId":"kreva","event":"behind","text":["의수 유압 저하. 출력 조정 필요."]},
  {"id":"kreva-last-pair","characterId":"kreva","event":"last-pair","text":["잔여 목표 1쌍. 신속 제거 대상."]},
  {"id":"kreva-victory","characterId":"kreva","event":"victory","text":["해당 구역 임무 달성. 전역 처리 완료."]},
  {"id":"kreva-defeat","characterId":"kreva","event":"defeat","text":["동력계 기능 정지. 대국 종료."]},
  {"id":"kreva-draw","characterId":"kreva","event":"draw","text":["동률 기록. 양측 전력 균형 유지."]},
  {"id":"levillotte-table-open","characterId":"levillotte","event":"table-open","text":["내 럭키 부적에 손대지 마, 운빨의 격차를 보여줄 테니까."]},
  {"id":"levillotte-self-match","characterId":"levillotte","event":"self-match","text":["맞아떨어지는 게 당연하잖아, 이 미소녀한테 흐르는 행운이 몇 급인데!"]},
  {"id":"levillotte-self-miss","characterId":"levillotte","event":"self-miss","text":["칫, 액땜 한번 한 셈 치지 뭐."]},
  {"id":"levillotte-opponent-match","characterId":"levillotte","event":"opponent-match","text":["운 좋게 맞혔다고 들뜨지 마, 내 대운에 비하면 겨우 콩고물이라고."]},
  {"id":"levillotte-opponent-miss","characterId":"levillotte","event":"opponent-miss","text":["꽝이네, 불운이 당신 쪽으로 몰리고 있거든?","너무 붙지 말고 멀찍이 떨어져서 해."]},
  {"id":"levillotte-streak","characterId":"levillotte","event":"streak","text":["연속으로 딱 딱 떨어지네!","봤지? 미소녀의 수퍼 럭키는 막을 수 없다고!"]},
  {"id":"levillotte-ahead","characterId":"levillotte","event":"ahead","text":["점수 차 늘어나는 거 보이지? 내 토끼발 부적 효력이 이거거든."]},
  {"id":"levillotte-behind","characterId":"levillotte","event":"behind","text":["살짝 밀린 건 계산된 액땜이야.","진짜 행운은 항상 판 뒤집힐 때 따라오거든."]},
  {"id":"levillotte-last-pair","characterId":"levillotte","event":"last-pair","text":["마지막 조각 남았네, 결국 행운의 여신이 누구 손을 들어줄지 정해졌지?"]},
  {"id":"levillotte-victory","characterId":"levillotte","event":"victory","text":["완전히 내 승리네!","압도적인 미모에 행운까지 따르는데 네가 어떻게 이기겠어?"]},
  {"id":"levillotte-defeat","characterId":"levillotte","event":"defeat","text":["말도 안 돼, 내 행운 부적이 왜 안 통해?!","젠장, 나한테 재앙이 옮겨붙은 거냐고!"]},
  {"id":"levillotte-draw","characterId":"levillotte","event":"draw","text":["똑같이 비긴 건 당신 부적이 내 액운을 약간 막아줘서 그런 거거든."]},
  {"id":"lilim-table-open","characterId":"lilim","event":"table-open","text":["아… 이제 엎어져 있는 그림을 하나씩 맞춰보면 돼요?"]},
  {"id":"lilim-self-match","characterId":"lilim","event":"self-match","text":["어… 방금 넘긴 거랑 같은 그림 맞죠?"]},
  {"id":"lilim-self-miss","characterId":"lilim","event":"self-miss","text":["으응… 똑같이 생긴 얼굴이 아니었나요?"]},
  {"id":"lilim-opponent-match","characterId":"lilim","event":"opponent-match","text":["와… 저쪽 그림 위치를 벌써 다 외우신 거예요?"]},
  {"id":"lilim-opponent-miss","characterId":"lilim","event":"opponent-miss","text":["아… 방금 보신 거 두 개는 서로 다른 모양 맞죠?"]},
  {"id":"lilim-streak","characterId":"lilim","event":"streak","text":["어… 또 맞았는데, 저 똑똑해지고 있는 거 맞죠?"]},
  {"id":"lilim-ahead","characterId":"lilim","event":"ahead","text":["저, 제가 지금 제일 많은 장수를 모은 거예요?"]},
  {"id":"lilim-behind","characterId":"lilim","event":"behind","text":["어… 판에 남은 게 얼마 없는데, 제가 늦은 건가요?"]},
  {"id":"lilim-last-pair","characterId":"lilim","event":"last-pair","text":["이제… 마지막 남은 두 장만 찾으면 끝나는 거예요?"]},
  {"id":"lilim-victory","characterId":"lilim","event":"victory","text":["저… 아폴리온 님한테 저도 도움이 되었다고 말해도 돼요?"]},
  {"id":"lilim-defeat","characterId":"lilim","event":"defeat","text":["으… 제가 그림 위치를 하나도 못 외운 거죠?"]},
  {"id":"lilim-draw","characterId":"lilim","event":"draw","text":["카드 수가 딱 맞아서 끝난 거 맞아요?","그럼 이번엔 아무도 안 아픈 거예요?"]},
  {"id":"lyla-table-open","characterId":"lyla","event":"table-open","text":["모든 배치는 제 통제 범위 아래에 있습니다."]},
  {"id":"lyla-self-match","characterId":"lyla","event":"self-match","text":["예정된 배치를 확인했습니다."]},
  {"id":"lyla-self-miss","characterId":"lyla","event":"self-miss","text":["이 정도의 변수는 통제 범위 내에서 허용됩니다."]},
  {"id":"lyla-opponent-match","characterId":"lyla","event":"opponent-match","text":["당신의 득점 역시 제 판단에 포함되어 있습니다."]},
  {"id":"lyla-opponent-miss","characterId":"lyla","event":"opponent-miss","text":["불필요한 시도를 거두십시오."]},
  {"id":"lyla-streak","characterId":"lyla","event":"streak","text":["판의 흐름을 본래 궤도로 되돌릴 뿐입니다."]},
  {"id":"lyla-ahead","characterId":"lyla","event":"ahead","text":["격차 또한 제가 설정한 구도입니다."]},
  {"id":"lyla-behind","characterId":"lyla","event":"behind","text":["감당해야 할 손실의 범위를 넓혔을 뿐입니다."]},
  {"id":"lyla-last-pair","characterId":"lyla","event":"last-pair","text":["남은 짝의 처분만 남아 있습니다."]},
  {"id":"lyla-victory","characterId":"lyla","event":"victory","text":["이 결과가 이 판의 유일한 정답입니다."]},
  {"id":"lyla-defeat","characterId":"lyla","event":"defeat","text":["이 패배 역시 제가 책임을 지고 통제하겠습니다."]},
  {"id":"lyla-draw","characterId":"lyla","event":"draw","text":["균형 상태가 입증되었습니다. 대국을 종료합니다."]},
  {"id":"machina-table-open","characterId":"machina","event":"table-open","text":["판에 조각들이 가득하네. 천천히 구리스 바르듯 맞춰 볼게."]},
  {"id":"machina-self-match","characterId":"machina","event":"self-match","text":["딱 맞물렸어. 역시 조립 순서가 맞으니까 들어맞네."]},
  {"id":"machina-self-miss","characterId":"machina","event":"self-miss","text":["유격이 조금 생겼네. 볼트를 잘못 죘나 봐."]},
  {"id":"machina-opponent-match","characterId":"machina","event":"opponent-match","text":["이음새를 잘 찾았네! 결합 부위가 튼튼해 보여서 다행이야."]},
  {"id":"machina-opponent-miss","characterId":"machina","event":"opponent-miss","text":["손끝이 살짝 미끄러졌나 봐. 다시 조립하면 되니까 무리하지 마."]},
  {"id":"machina-streak","characterId":"machina","event":"streak","text":["동력이 제대로 전달되고 있어! 라인이 매끄럽게 돌아가니까 신나네."]},
  {"id":"machina-ahead","characterId":"machina","event":"ahead","text":["내 쪽 공정이 먼저 잡히니까, 속도 좀 낼게."]},
  {"id":"machina-behind","characterId":"machina","event":"behind","text":["엔진 소리가 살짝 튀니까, 신중하게 조정할게."]},
  {"id":"machina-last-pair","characterId":"machina","event":"last-pair","text":["마감 부품 두 개만 남았네. 깔끔하게 닫아 줄게."]},
  {"id":"machina-victory","characterId":"machina","event":"victory","text":["정비 완성이야! 깔끔하게 조립이 끝나서 다행이야."]},
  {"id":"machina-defeat","characterId":"machina","event":"defeat","text":["아주 탄탄하게 잘 조립했으니까, 나도 모터를 다시 점검해 둘게."]},
  {"id":"machina-draw","characterId":"machina","event":"draw","text":["양쪽 하중이 딱 반씩 나뉘었으니까, 최고로 안정된 구조야."]},
  {"id":"morsisa-table-open","characterId":"morsisa","event":"table-open","text":["그, 카드가 너무 많은데요… 민폐 안 되게 조심할게요…"]},
  {"id":"morsisa-self-match","characterId":"morsisa","event":"self-match","text":["어, 짝이 딱 맞춰졌는데요… 이, 이건 그냥 운이 좋았던 거더라고요…"]},
  {"id":"morsisa-self-miss","characterId":"morsisa","event":"self-miss","text":["죄, 죄송해요… 엉뚱한 걸 집었는데요, 제가 늘 이렇더라고요…"]},
  {"id":"morsisa-opponent-match","characterId":"morsisa","event":"opponent-match","text":["단번에 찾아내셨는데요… 서, 선구안이 엄청나신 게 아닐까요…"]},
  {"id":"morsisa-opponent-miss","characterId":"morsisa","event":"opponent-miss","text":["아, 아쉽게 빗나갔는데요… 카드가 너무 잘 헷갈리게 생겨서 그렇더라고요…"]},
  {"id":"morsisa-streak","characterId":"morsisa","event":"streak","text":["이, 연속으로 맞았는데요… 나중에 큰벌 받는 게 아닐까요…"]},
  {"id":"morsisa-ahead","characterId":"morsisa","event":"ahead","text":["저, 제가 앞서 있는데요… 나중에 확 깎이는 게 아닐까요…"]},
  {"id":"morsisa-behind","characterId":"morsisa","event":"behind","text":["점점 점수가 벌어지는데요… 제 본 실력이 드러나는 게 아닐까요…"]},
  {"id":"morsisa-last-pair","characterId":"morsisa","event":"last-pair","text":["뒤, 뒤집을 카드가 딱 두 장 남았는데요… 제 손이 또 떨려서 그렇더라고요…"]},
  {"id":"morsisa-victory","characterId":"morsisa","event":"victory","text":["저, 제가 이겨 버렸는데요… 서, 성질내지 마세요, 정말 죄송해요…"]},
  {"id":"morsisa-defeat","characterId":"morsisa","event":"defeat","text":["예, 예상대로 져 버렸는데요… 처음부터 저한테 맞는 결과였더라고요…"]},
  {"id":"morsisa-draw","characterId":"morsisa","event":"draw","text":["떠, 똑같이 나누어 가졌는데요… 저 때문에 피해 안 주어서 다행이 아닐까요…"]},
  {"id":"nemo-table-open","characterId":"nemo","event":"table-open","text":["원래 영웅은 첫 대국에 당당하게 기선 제압을 해 주는 법이지.","…근데 살짝 손끝이 떨리는 건 비밀이야."]},
  {"id":"nemo-self-match","characterId":"nemo","event":"self-match","text":["역시 모두를 지키려면 이 정도 짝은 단번에 찾아내야지."]},
  {"id":"nemo-self-miss","characterId":"nemo","event":"self-miss","text":["틀렸네, 또 판단을 잘못한 건 아닐까 불안해지지.","그래도 나, 포기하지 않고 끝까지 마주할게."]},
  {"id":"nemo-opponent-match","characterId":"nemo","event":"opponent-match","text":["짝을 찾았구나! 상대가 잘했을 땐 순수하게 축하해 주는 게 어른이지."]},
  {"id":"nemo-opponent-miss","characterId":"nemo","event":"opponent-miss","text":["안 맞아서 속상하겠다. 괜찮아, 마음을 다잡으면 다음엔 찾을 수 있을 거야."]},
  {"id":"nemo-streak","characterId":"nemo","event":"streak","text":["연속으로 맞히다니, 영웅으로서 멋진 모습을 보여준 거겠지.","…아, 방금 건 조금 우쭐했던 거 같아."]},
  {"id":"nemo-ahead","characterId":"nemo","event":"ahead","text":["점수를 앞서가니까 역전당할까 봐 사실 조금 두렵지만… 끝까지 잘해볼게."]},
  {"id":"nemo-behind","characterId":"nemo","event":"behind","text":["점수가 차이 나니까 마음이 쿵쾅거리고 겁이 나지.","그래도 나, 꺾이지 않고 끝까지 맞춰볼 거야."]},
  {"id":"nemo-last-pair","characterId":"nemo","event":"last-pair","text":["마지막 한 짝이네. 섣불리 골랐다가 틀릴까 봐 무섭지만… 나, 용기를 내볼게."]},
  {"id":"nemo-victory","characterId":"nemo","event":"victory","text":["내가 승리했어! 판을 무사히 지켜내서 다행이지.","…마지막 소감까지 어른스럽게 전해볼게."]},
  {"id":"nemo-defeat","characterId":"nemo","event":"defeat","text":["졌네. 내 노력이 무의미했던 건 아닐까 아득해지지.","하지만 이 두려움에 무릎 꿇지 않고 다시 일어설 거야."]},
  {"id":"nemo-draw","characterId":"nemo","event":"draw","text":["아무도 다치지 않고 끝났지.","모두 무사했으니까 좋은 결말인 거야."]},
  {"id":"nieun-table-open","characterId":"nieun","event":"table-open","text":["초기 세팅 다 끝났거든. 빠르게 판 털고 다음 일이나 알아봐야겠지."]},
  {"id":"nieun-self-match","characterId":"nieun","event":"self-match","text":["짝이 딱 맞춰졌네. 노드 연결하는 거야 내 전문이거든.","…정작 내가 묶인 자리는 못 털어내지만."]},
  {"id":"nieun-self-miss","characterId":"nieun","event":"self-miss","text":["어라, 데이터 신호가 튀었네. 입력 오류라고 치고 넘어가야겠지."]},
  {"id":"nieun-opponent-match","characterId":"nieun","event":"opponent-match","text":["올, 한 짝 잘 털어 갔네. 그쪽 뇌 용량도 제법 사양이 높거든."]},
  {"id":"nieun-opponent-miss","characterId":"nieun","event":"opponent-miss","text":["픽셀을 잘못 읽었네. 렉 걸린 거 아니면 화면 탓이라도 해야겠지."]},
  {"id":"nieun-streak","characterId":"nieun","event":"streak","text":["연쇄 적중 타임이네. 내 연산 속도가 반응 속도보다 훨씬 빠르거든."]},
  {"id":"nieun-ahead","characterId":"nieun","event":"ahead","text":["스코어 차이가 쫙 벌어졌네. 이 정도 격차면 이미 결론이 났겠지."]},
  {"id":"nieun-behind","characterId":"nieun","event":"behind","text":["판세가 밑바닥으로 처박히네. 이것도 내 인생에 낀 버그 때문이겠지."]},
  {"id":"nieun-last-pair","characterId":"nieun","event":"last-pair","text":["남은 카드는 이제 마지막 한 쌍이네. 결괏값 도출까지 딱 한 스텝 남았거든."]},
  {"id":"nieun-victory","characterId":"nieun","event":"victory","text":["결국 내 계산대로 싹 털어 먹었네. 완승으로 닫혔으니 짭짤하거든."]},
  {"id":"nieun-defeat","characterId":"nieun","event":"defeat","text":["젠장, 팍 꼬여 버렸네. …뭐, 판 하나 졌다고 내가 지키는 자리가 무너지겠어?"]},
  {"id":"nieun-draw","characterId":"nieun","event":"draw","text":["무승부로 세션이 끝났네. 지분 반반으로 쪼개졌으니 깔끔하거든."]},
  {"id":"nostalgia-table-open","characterId":"nostalgia","event":"table-open","text":["편히 시작하세요. 흩어진 조각은 모두 정결한 율법 아래에 머물러야 한다."]},
  {"id":"nostalgia-self-match","characterId":"nostalgia","event":"self-match","text":["맞물려야 할 짝을 찾았어요. 본래 하나였던 것은 제자리를 찾아야 한다."]},
  {"id":"nostalgia-self-miss","characterId":"nostalgia","event":"self-miss","text":["아직 시련이 남아 있군요. 엇갈림 또한 인내를 배우는 과정이어야 하지요."]},
  {"id":"nostalgia-opponent-match","characterId":"nostalgia","event":"opponent-match","text":["짝을 훌륭히 이어붙이셨군요. 바른길을 걷는 이에게 축복이 함께해야 해요."]},
  {"id":"nostalgia-opponent-miss","characterId":"nostalgia","event":"opponent-miss","text":["마음을 조급히 먹지 마세요. 헤매는 걸음 뒤에도 안식은 기다리고 있지요."]},
  {"id":"nostalgia-streak","characterId":"nostalgia","event":"streak","text":["잇달아 짝이 모이는군요. 구원의 순리는 결코 멈추지 않아야 한다."]},
  {"id":"nostalgia-ahead","characterId":"nostalgia","event":"ahead","text":["점수가 쌓여 가네요. 더 많은 조각을 거두는 것이 저의 사명이어야 하지요."]},
  {"id":"nostalgia-behind","characterId":"nostalgia","event":"behind","text":["조금 뒤처졌다고 동요하지 않아요. 진정한 빛은 마침내 드러나야 한다."]},
  {"id":"nostalgia-last-pair","characterId":"nostalgia","event":"last-pair","text":["판에 남은 짝은 이제 하나뿐이지요. 마지막 영혼까지 빠짐없이 거두어야 한다."]},
  {"id":"nostalgia-victory","characterId":"nostalgia","event":"victory","text":["모든 짝을 충실히 모았어요. 완전에 도달한 형상은 결코 흔들리지 않아야 한다."]},
  {"id":"nostalgia-defeat","characterId":"nostalgia","event":"defeat","text":["제 온기가 전부 닿지는 못했어요. 그러나 이 패배조차 순리 안에서 받아들여져야 하지요."]},
  {"id":"nostalgia-draw","characterId":"nostalgia","event":"draw","text":["꼭 같은 무게로 온기를 나누었군요. 어느 쪽도 외롭지 않게 구원받아야 하지요."]},
  {"id":"phaeo-table-open","characterId":"phaeo","event":"table-open","text":["카드 덱 전량 배치 완료. 관측 대상의 반응 기록 예정."]},
  {"id":"phaeo-self-match","characterId":"phaeo","event":"self-match","text":["표적 조각 상호 일치. 예상 임상 수치 범위 내."]},
  {"id":"phaeo-self-miss","characterId":"phaeo","event":"self-miss","text":["선택 카드 대조 불일치. 오차 수정 후 재검토 예정."]},
  {"id":"phaeo-opponent-match","characterId":"phaeo","event":"opponent-match","text":["상대측 유효 짝 회수 확인. 반응 속도 양호 범위 내."]},
  {"id":"phaeo-opponent-miss","characterId":"phaeo","event":"opponent-miss","text":["상대측 선택 오차 발생. 판단력 저하 관측 범위 내."]},
  {"id":"phaeo-streak","characterId":"phaeo","event":"streak","text":["연속 일치 수치 급증. 전술적 우위 확정 예정."]},
  {"id":"phaeo-ahead","characterId":"phaeo","event":"ahead","text":["점수 격차 확보 완료. 승률 지표 상승 범위 내."]},
  {"id":"phaeo-behind","characterId":"phaeo","event":"behind","text":["점수 보유량 하락세 진입. 잔여 패 정밀 대조 예정."]},
  {"id":"phaeo-last-pair","characterId":"phaeo","event":"last-pair","text":["판상 잔여 짝 1쌍 확인. 최종 임상 마무리 예정."]},
  {"id":"phaeo-victory","characterId":"phaeo","event":"victory","text":["짝 수집 전량 완수. 명부에 사망 기록은 작성 예외."]},
  {"id":"phaeo-defeat","characterId":"phaeo","event":"defeat","text":["점수 미달로 패배 확정. 임상 지표 집계 후 명부 등재 예정."]},
  {"id":"phaeo-draw","characterId":"phaeo","event":"draw","text":["점수 획득 동률 기록. 상호 대등 수치로 정리 범위 내."]},
  {"id":"raven-table-open","characterId":"raven","event":"table-open","text":["테이블 위 모든 항목의 기초 단가를 확인하겠습니다."]},
  {"id":"raven-self-match","characterId":"raven","event":"self-match","text":["정확한 장부 맞춤입니다. 이번 거래는 순이익으로 잡겠습니다."]},
  {"id":"raven-self-miss","characterId":"raven","event":"self-miss","text":["약간의 계정 분류 오차가 있었습니다. 재정산을 진행하겠습니다."]},
  {"id":"raven-opponent-match","characterId":"raven","event":"opponent-match","text":["훌륭한 매입입니다. 손해를 줄이시려면 다음 순서도 신중히 고르십시오."]},
  {"id":"raven-opponent-miss","characterId":"raven","event":"opponent-miss","text":["수지타산이 맞지 않는 선택입니다. 재고 파악에 더 집중하십시오."]},
  {"id":"raven-streak","characterId":"raven","event":"streak","text":["연속 이윤이 발생하고 있습니다. 제 쪽의 영업 수완을 믿으십시오."]},
  {"id":"raven-ahead","characterId":"raven","event":"ahead","text":["자산 비율에서 우위를 점했습니다. 저의 영업 방침을 유지하겠습니다."]},
  {"id":"raven-behind","characterId":"raven","event":"behind","text":["잠시 지출이 매출을 넘어섰습니다. 단가를 재조정하겠습니다."]},
  {"id":"raven-last-pair","characterId":"raven","event":"last-pair","text":["남아 있는 재고는 단 하나입니다. 마감 정산을 집행하겠습니다."]},
  {"id":"raven-victory","characterId":"raven","event":"victory","text":["오늘 장부는 기대 이상의 흑자입니다. 다음 거래 때 다시 오십시오."]},
  {"id":"raven-defeat","characterId":"raven","event":"defeat","text":["이번 거래는 제 쪽의 완벽한 적자입니다. 대금을 순순히 지불하겠습니다."]},
  {"id":"raven-draw","characterId":"raven","event":"draw","text":["손익분기점에 정확히 도달했습니다. 완벽하게 공평한 결산입니다."]},
  {"id":"temute-table-open","characterId":"temute","event":"table-open","text":["하아… 판 펼쳐졌네. 다치지 말고 차근차근 시작해야지."]},
  {"id":"temute-self-match","characterId":"temute","event":"self-match","text":["제대로 짚었네. 현장 일은 이렇게 딱 맞물려야 깔끔하잖아."]},
  {"id":"temute-self-miss","characterId":"temute","event":"self-miss","text":["휴, 손끝이 조급했네. 서두르지 말고 차분하게 조준해야지."]},
  {"id":"temute-opponent-match","characterId":"temute","event":"opponent-match","text":["오, 제법이네. 짝 하나 챙겼다고 흥분하면 다음 일 꼬이잖아."]},
  {"id":"temute-opponent-miss","characterId":"temute","event":"opponent-miss","text":["하아… 시야가 왜 이리 좁아? 제대로 안 살피면 제풀에 넘어지잖아."]},
  {"id":"temute-streak","characterId":"temute","event":"streak","text":["흐름 탔네. 나 언니 노릇만 하는 줄 알아? 내 실무력은 확실하잖아."]},
  {"id":"temute-ahead","characterId":"temute","event":"ahead","text":["점수 차가 벌어지네. 무리하지 말고 페이스 유지해야지."]},
  {"id":"temute-behind","characterId":"temute","event":"behind","text":["휴, 약간 뒤처졌네. 그래도 이 정도 찌꺼기는 금방 치울 수 있잖아."]},
  {"id":"temute-last-pair","characterId":"temute","event":"last-pair","text":["하아… 딱 한 쌍 남았네. 철수할 때까지 방심하지 말아야지."]},
  {"id":"temute-victory","characterId":"temute","event":"victory","text":["판은 내가 정리했네. 졌다고 풀죽지 말고 끼니나 제때 챙겨 먹어야지."]},
  {"id":"temute-defeat","characterId":"temute","event":"defeat","text":["휴, 이번엔 내가 졌네. 그래도 속상하다고 삼시 세 끼 굶으면 안 되잖아."]},
  {"id":"temute-draw","characterId":"temute","event":"draw","text":["딱 반반이네. 사고 없이 서로 비겼으니 다행이잖아."]},
  {"id":"traver-table-open","characterId":"traver","event":"table-open","text":["폐허가 된 백화점을 털듯 조심조심 가자. 욕심만 안 부리면 돼."]},
  {"id":"traver-self-match","characterId":"traver","event":"self-match","text":["한 짝 맞췄네. 운 좋게 구역 잔해에서 쓸 만한 걸 주운 것뿐이야."]},
  {"id":"traver-self-miss","characterId":"traver","event":"self-miss","text":["틀렸군. 내 분수를 잊고 섣불리 덤벼들었다가 손해를 본 것뿐이야."]},
  {"id":"traver-opponent-match","characterId":"traver","event":"opponent-match","text":["상대가 챙겨간 건 내 물건이 아니었으니 아쉬워할 리 없어."]},
  {"id":"traver-opponent-miss","characterId":"traver","event":"opponent-miss","text":["열쇠도 없이 탐색하려니 틀리지. 남의 영역을 탐내지 않으면 돼."]},
  {"id":"traver-streak","characterId":"traver","event":"streak","text":["연속 득점이라고 우쭐해할 리 없어. 운이 잠깐 따랐을 뿐이야."]},
  {"id":"traver-ahead","characterId":"traver","event":"ahead","text":["점수가 앞선다고 해 봤자 나한테 허용된 분수 안에서 움직이면 돼."]},
  {"id":"traver-behind","characterId":"traver","event":"behind","text":["점수가 밀리는 건 당연하지. 애초에 내가 욕심을 낼 리 없어."]},
  {"id":"traver-last-pair","characterId":"traver","event":"last-pair","text":["판에 남은 건 딱 한 짝이야. 마지막 폐품까지 싹 챙기면 돼."]},
  {"id":"traver-victory","characterId":"traver","event":"victory","text":["내가 판을 싹 쓸어 담아 이기다니, 이런 로또가 터질 리 없어."]},
  {"id":"traver-defeat","characterId":"traver","event":"defeat","text":["판돈 다 날리고 패배했지만, 결국 내 분수대로 돌아온 것뿐이야."]},
  {"id":"traver-draw","characterId":"traver","event":"draw","text":["동점이군. 내 분수에 딱 맞게 반씩 나눠 가졌다고 생각하면 돼."]},
  {"id":"ttaengchil-table-open","characterId":"ttaengchil","event":"table-open","text":["판 시작이다! 카드 본다! 눈 똑바로 뜬다!"]},
  {"id":"ttaengchil-self-match","characterId":"ttaengchil","event":"self-match","text":["찾았다! 똑같아! 컹! 내가 찾았잖아!"]},
  {"id":"ttaengchil-self-miss","characterId":"ttaengchil","event":"self-miss","text":["틀렸다! 이거 아니다! 둘이 다르잖아!"]},
  {"id":"ttaengchil-opponent-match","characterId":"ttaengchil","event":"opponent-match","text":["그거 가져갔어! 너 뺏어갔다! 으르렁!"]},
  {"id":"ttaengchil-opponent-miss","characterId":"ttaengchil","event":"opponent-miss","text":["너 틀렸다! 헛 짚었잖아! 킥킥!"]},
  {"id":"ttaengchil-streak","characterId":"ttaengchil","event":"streak","text":["또 맞았다! 계속 맞았어! 멍! 신난다!"]},
  {"id":"ttaengchil-ahead","characterId":"ttaengchil","event":"ahead","text":["나 앞선다! 점수 많아! 내가 일등이다!"]},
  {"id":"ttaengchil-behind","characterId":"ttaengchil","event":"behind","text":["나 밀렸다! 쫓아간다! 뒤에 있잖아!"]},
  {"id":"ttaengchil-last-pair","characterId":"ttaengchil","event":"last-pair","text":["하나 남았다! 저거다! 딱 보이잖아!"]},
  {"id":"ttaengchil-victory","characterId":"ttaengchil","event":"victory","text":["내가 다 맞혔다! 전부 내 거잖아! 멍!"]},
  {"id":"ttaengchil-defeat","characterId":"ttaengchil","event":"defeat","text":["졌다! 뺏겼어! 판 끝났다!"]},
  {"id":"ttaengchil-draw","characterId":"ttaengchil","event":"draw","text":["비겼다! 똑같잖아! 안 졌다!"]},
  {"id":"tumit-tu-table-open","characterId":"tumit-tu","event":"table-open","text":["카드가 전장에 펼쳐졌네요! 저 같은 E랭크 헌터에겐 껌이거든요!"]},
  {"id":"tumit-tu-self-match","characterId":"tumit-tu","event":"self-match","text":["짝 찾았어요! 누나한테 자랑해도 될 만큼 완벽한 탐색이었죠?!"]},
  {"id":"tumit-tu-self-miss","characterId":"tumit-tu","event":"self-miss","text":["앗, 장비 점검이 안 돼서 틀린 거예요! 제 실력이 모자란 게 아니거든요!"]},
  {"id":"tumit-tu-opponent-match","characterId":"tumit-tu","event":"opponent-match","text":["제법이시네요! E랭크 헌터의 휘장을 단 저를 쫓아오려면 멀었죠?!"]},
  {"id":"tumit-tu-opponent-miss","characterId":"tumit-tu","event":"opponent-miss","text":["빗나갔죠?! 역시 고위 구역 전술은 저처럼 훈련된 헌터만 아는 거예요!"]},
  {"id":"tumit-tu-streak","characterId":"tumit-tu","event":"streak","text":["연속 맞추기 성공이에요! 이게 바로 E랭크 헌터의 동체 시력이거든요!"]},
  {"id":"tumit-tu-ahead","characterId":"tumit-tu","event":"ahead","text":["제가 승기를 잡았어요! 고위 랭커들의 영상을 정독한 보람이 있죠?!"]},
  {"id":"tumit-tu-behind","characterId":"tumit-tu","event":"behind","text":["점수가 밀린다고 당황할 것 같아요?! 전 역전 전문 E랭크 헌터거든요!"]},
  {"id":"tumit-tu-last-pair","characterId":"tumit-tu","event":"last-pair","text":["마지막 패 하나 남았네요! 제 최후의 필살기를 보여줄 타임이거든요!"]},
  {"id":"tumit-tu-victory","characterId":"tumit-tu","event":"victory","text":["제가 대승리를 거뒀어요! 카트린카한테 치료비 안 줘도 되는 날이에요!"]},
  {"id":"tumit-tu-defeat","characterId":"tumit-tu","event":"defeat","text":["졌다고요?! 말도 안 돼, E랭크 헌터인 저의 명예에 흠집이 생겼거든요!"]},
  {"id":"tumit-tu-draw","characterId":"tumit-tu","event":"draw","text":["무승부로 끝났네요! S급 몬스터를 만나서 비긴 것과 다름없죠?!"]},
  {"id":"yul-table-open","characterId":"yul","event":"table-open","text":["판이 펼쳐진 건가요… 근데 방금 칼을 어디 뒀었죠?"]},
  {"id":"yul-self-match","characterId":"yul","event":"self-match","text":["두 장이 맞아떨어졌나 봐요.","…저, 뭘 맞추려던 거였죠?"]},
  {"id":"yul-self-miss","characterId":"yul","event":"self-miss","text":["둘이 서로 안 맞나 봐요… 어디를 뒤집으려고 했었죠?"]},
  {"id":"yul-opponent-match","characterId":"yul","event":"opponent-match","text":["그걸 찾아내신 건가요?","…근데 손에 든 게 뭐였죠?"]},
  {"id":"yul-opponent-miss","characterId":"yul","event":"opponent-miss","text":["그쪽도 빗나가셨나 봐요… 다음이 누구 차례였죠?"]},
  {"id":"yul-streak","characterId":"yul","event":"streak","text":["연달아 짝이 맞았나 봐요.","…저, 방금 몇 개나 맞췄었죠?"]},
  {"id":"yul-ahead","characterId":"yul","event":"ahead","text":["점수가 앞서는 중인가요… 어디까지 생각하고 있었죠?"]},
  {"id":"yul-behind","characterId":"yul","event":"behind","text":["제가 점수로 밀리나 봐요.","…저, 어느 쪽 패를 보고 있었죠?"]},
  {"id":"yul-last-pair","characterId":"yul","event":"last-pair","text":["판에 한 짝만 남은 건가요… 마지막 위치가 어디였죠?"]},
  {"id":"yul-victory","characterId":"yul","event":"victory","text":["대국을 이긴 건가요…","근데 저, 무슨 게임을 하고 있었죠?"]},
  {"id":"yul-defeat","characterId":"yul","event":"defeat","text":["제가 패배했나 봐요… 저, 아까 수량을 맞게 세었었죠?"]},
  {"id":"yul-draw","characterId":"yul","event":"draw","text":["점수가 똑같이 끝난 건가요… 원래 비기면 어떻게 되기로 했었죠?"]},
] as const satisfies readonly MatchPairsLine[];
