import { IconArrowLeft, IconRefresh, IconShieldCheck } from "@tabler/icons-react";
import type { RestorationDeck, RestorationProblem } from "@lucky-arcade/extract";
import { Button } from "@lucky-arcade/ui";
import { useEffect, useRef, useState } from "react";
import { createRestorationState, reduceRestoration, restorationGrade } from "../index.ts";

export function RestorationScreen({ deck, loadAsset, onExit, onRetry }: { deck: RestorationDeck; loadAsset(id: string): Promise<string>; onExit(): void; onRetry(): void }) {
  const [state, setState] = useState(() => createRestorationState(deck));
  const started = useRef(performance.now());
  useEffect(() => { if (state.phase !== "question" || state.status !== "playing") return; started.current = performance.now(); const timer = window.setTimeout(() => setState((value) => reduceRestoration(value, { type: "timeout" }, deck)), 15_000); return () => window.clearTimeout(timer); }, [deck, state.index, state.phase, state.status]);
  if (state.status === "won") { const names = [...new Set(deck.problems.map((problem) => problem.originalName))]; return <main className="game-shell restoration-shell"><GameHeader onExit={onExit} index={deck.problems.length} total={deck.problems.length} /><section className="restoration-result"><IconShieldCheck size={52} /><span className="eyebrow">복구 완료</span><h2>{restorationGrade(state)} 등급 · {state.score.toLocaleString()}점</h2><p>복구한 인물들</p><div className="restored-names">{names.map((name) => <strong key={name}>{name}</strong>)}</div><div className="result-actions"><Button onClick={onRetry}><IconRefresh size={18} /> 새 문제</Button><Button onClick={onExit}>다른 놀이 보기</Button></div></section></main>; }
  const problem = deck.problems[state.index]; if (!problem) return null;
  const answer = state.answers.at(-1), reveal = state.phase === "reveal";
  const choose = (selection: string) => setState((value) => reduceRestoration(value, { type: "answer", selection, elapsedMs: performance.now() - started.current }, deck));
  return <main className="game-shell restoration-shell"><GameHeader onExit={onExit} index={state.index + 1} total={deck.problems.length} /><section className="restoration-board"><span className="eyebrow">이상한 곳을 누르세요</span><h2>{problem.type === "expression-intruder" ? `${problem.shownName}의 기록에 다른 인물이 섞였습니다` : "이름과 초상화 중 하나가 바뀌었습니다"}</h2>{problem.type === "expression-intruder" ? <Gallery problem={problem} loadAsset={loadAsset} disabled={reveal} choose={choose} /> : <Identity problem={problem} loadAsset={loadAsset} disabled={reveal} choose={choose} />}{reveal && <div className={`restoration-reveal ${answer?.correct ? "correct" : "wrong"}`}><strong>{answer?.correct ? "정확히 찾았습니다!" : "이 부분이 바뀌어 있었습니다."}</strong><span>원본: {problem.originalName}</span><Button onClick={() => setState((value) => reduceRestoration(value, { type: "next" }, deck))}>{state.index + 1 === deck.problems.length ? "결과 보기" : "다음 기록"}</Button></div>}</section></main>;
}

function GameHeader({ onExit, index, total }: { onExit(): void; index: number; total: number }) { return <header className="game-header"><button className="icon-button" onClick={onExit} aria-label="분석 화면으로 돌아가기"><IconArrowLeft /></button><div><span>LUCKY CABINET 02</span><h1>카드 복구반</h1></div><div className="game-meters"><span><b>{index}</b> / {total}</span><span>문제당 15초</span></div></header>; }
function Identity({ problem, loadAsset, disabled, choose }: { problem: Extract<RestorationProblem,{type:"portrait-swap"|"name-swap"}>; loadAsset(id:string):Promise<string>; disabled:boolean; choose(value:string):void }) { return <div className="identity-case"><button disabled={disabled} onClick={() => choose("portrait")}><Asset assetId={problem.shownAssetId} name={problem.shownName} loadAsset={loadAsset} /></button><button className="identity-name" disabled={disabled} onClick={() => choose("name")}>{problem.shownName}</button></div>; }
function Gallery({ problem, loadAsset, disabled, choose }: { problem: Extract<RestorationProblem,{type:"expression-intruder"}>; loadAsset(id:string):Promise<string>; disabled:boolean; choose(value:string):void }) { return <div className="intruder-grid">{problem.assetIds.map((id) => <button key={id} disabled={disabled} onClick={() => choose(id)}><Asset assetId={id} name={problem.shownName} loadAsset={loadAsset} /></button>)}</div>; }
function Asset({ assetId, name, loadAsset }: { assetId:string; name:string; loadAsset(id:string):Promise<string> }) { const [url,setUrl]=useState<string|null>(null); useEffect(()=>{let alive=true; setUrl(null); void loadAsset(assetId).then((value)=>{if(alive)setUrl(value)}).catch(()=>{}); return()=>{alive=false}},[assetId,loadAsset]); return <div className="restoration-image">{url?<img src={url} alt={name} decoding="async"/>:<span>이미지 준비 중…</span>}</div>; }
